// Code generated by storm (replaced). DO NOT EDIT.
// source: table order_lines

package orderline

import (
	"context"
	"errors"
	"net/netip"
	"time"

	"github.com/gsoultan/storm/runtime"
)

var (
	_ = time.Time{}
	_ = netip.Prefix{}
)

// Row is what a full read returns: the model struct with relations
// replaced by their scalar foreign keys and *T rewritten to Null[T].
type Row struct {
	ID        [16]byte
	CreatedAt time.Time
	UpdatedAt time.Time
	OrderID   [16]byte
	ProductID [16]byte
	Quantity  int32
	UnitPrice runtime.Decimal
}

// Operator ids. Argument-taking operators are numbered first, so the
// bind loop tests `op-1 < opsWithArg` with one unsigned compare.
const (
	opEq               runtime.Op = 1
	opNotEq            runtime.Op = 2
	opGt               runtime.Op = 3
	opGte              runtime.Op = 4
	opLt               runtime.Op = 5
	opLte              runtime.Op = 6
	opLike             runtime.Op = 7
	opILike            runtime.Op = 8
	opMatches          runtime.Op = 9
	opWebSearch        runtime.Op = 10
	opOverlaps         runtime.Op = 11
	opContainsRange    runtime.Op = 12
	opContainedBy      runtime.Op = 13
	opIn               runtime.Op = 14
	opNotIn            runtime.Op = 15
	opArrayContains    runtime.Op = 16
	opArrayContainedBy runtime.Op = 17
	opArrayOverlaps    runtime.Op = 18
	opIsNull           runtime.Op = 19
	opIsNotNull        runtime.Op = 20
	// Existence operators apply to PSEUDO-COLUMNS — relation slots past
	// the real columns in the frag table. Argless, like IsNull: the
	// fragment is constant, which is what lets a semi-join ride the
	// ordinary predicate machinery and compose under And/Or/Not free.
	opExists    runtime.Op = 21
	opNotExists runtime.Op = 22
)

const nCols = 7

// Query is a value type: composing one allocates nothing. Predicates
// are a postfix token stream, so disjunction and negation are
// representable — a per-column operator mask cannot express either.
type Query struct {
	toks [16]runtime.Tok
	nt   uint8
	top  uint8 // top-level conjuncts, ANDed at compile time

	nums            [6]int64
	raws            [4][16]byte
	tims            [4]time.Time
	decs            [4]runtime.Decimal
	nn, nr, ntm, nd uint8

	anyRaw     [3][][16]byte
	anyI32     [3][]int32
	nar, nai32 uint8

	// Order terms live in their own buffer and are appended to the stream
	// after the predicate tree. Sharing one buffer would let a Where after
	// an Order interleave the two, and the stream's order is its meaning.
	otoks [4]runtime.Tok
	no    uint8

	limit  int64
	offset int64
	// over records that the query outgrew its fixed buffers. Terminals
	// return it as an error rather than silently dropping a predicate.
	over bool

	// mixed records an After() over an ordering that is not all in one
	// direction. No single row comparison expresses that.
	mixed bool

	// noOrder suppresses the default ordering. See Unordered.
	noOrder  bool
	badAfter bool
}

// New starts a query.
func New() Query { return Query{limit: 1000} }

// Limit caps the result set.
func (q Query) Limit(n int64) Query { q.limit = n; return q }

// Offset skips rows.
//
// It is here because callers expect it, not because it is a good idea: the
// database still walks and discards every skipped row, so page 5,000 costs
// 5,000 pages of work, and a row inserted mid-scroll shifts every later
// page. Order by a unique key and filter past the last one you saw instead.
func (q Query) Offset(n int64) Query { q.offset = n; return q }

// After filters past a row already seen: keyset pagination.
//
// The comparison follows the ACTIVE ordering, because it has to. Paging
// `ORDER BY email DESC` with `> $1` walks away from the rows you have
// not seen yet, and silently returns a wrong page rather than an error.
// So After reads the ordering off the query and builds the matching row
// comparison: (a, b) > ($1, $2) for ascending, < for descending.
//
// Unlike Offset the database does not walk the skipped rows — the
// comparison seeks straight into the index — and a row inserted
// mid-scroll cannot shift a page, because the cursor is a position in the
// data rather than a count.
//
// Mixing ascending and descending terms in one ordering is a query error:
// no single row comparison expresses it, and expanding it into ORs would
// silently give up the index walk that makes this worth doing.
func (q Query) After(r Row) Query {
	terms := q.otoks[:q.no]
	if q.no == 0 {
		if q.noOrder {
			// A keyset cursor without an order is a position in nothing.
			q.badAfter = true
			return q
		}
		terms = defaultOrder[:]
	}
	if len(terms) == 0 {
		return q
	}
	desc := terms[0].Op() == runtime.Desc || terms[0].Op() == runtime.DescNullsLast
	for _, t := range terms {
		d := t.Op() == runtime.Desc || t.Op() == runtime.DescNullsLast
		if d != desc {
			q.mixed = true
			return q
		}
	}
	for _, t := range terms {
		q.push(runtime.MakeCol(t.Col()))
		q.cursor(t.Col(), r)
	}
	op := runtime.CmpGt
	if desc {
		op = runtime.CmpLt
	}
	q.push(runtime.MakeRowCmp(op, uint32(len(terms))))
	q.top++
	return q
}

// cursor stores the bound value for one column of a keyset comparison.
func (q *Query) cursor(col uint32, r Row) {
	switch col {
	case 0:
		if int(q.nr) >= len(q.raws) {
			q.over = true
			return
		}
		q.raws[q.nr] = r.ID
		q.nr++
	case 1:
		if int(q.ntm) >= len(q.tims) {
			q.over = true
			return
		}
		q.tims[q.ntm] = r.CreatedAt
		q.ntm++
	case 2:
		if int(q.ntm) >= len(q.tims) {
			q.over = true
			return
		}
		q.tims[q.ntm] = r.UpdatedAt
		q.ntm++
	case 3:
		if int(q.nr) >= len(q.raws) {
			q.over = true
			return
		}
		q.raws[q.nr] = r.OrderID
		q.nr++
	case 4:
		if int(q.nr) >= len(q.raws) {
			q.over = true
			return
		}
		q.raws[q.nr] = r.ProductID
		q.nr++
	case 5:
		if int(q.nn) >= len(q.nums) {
			q.over = true
			return
		}
		q.nums[q.nn] = int64(r.Quantity)
		q.nn++
	case 6:
		if int(q.nd) >= len(q.decs) {
			q.over = true
			return
		}
		q.decs[q.nd] = r.UnitPrice
		q.nd++
	}
}

// Unordered drops the default ordering, for results consumed in an
// order-independent way — a batch loader that buckets rows into a map,
// an aggregation, a bulk export.
//
// The default exists because paging an unordered read is a bug; the
// escape exists because ordering a read NOBODY PAGES is a server-side
// sort for free. Measured on a 50k-row relation load: an external merge
// sort spilling 5MB to disk, for an order the loader's map bucketing
// destroyed on arrival. An explicit Order() still applies; After() on an
// unordered query with no explicit order is an error, because a keyset
// cursor without an order is a position in nothing.
func (q Query) Unordered() Query { q.noOrder = true; return q }

// Sort is one ORDER BY term, produced by a column handle: Email.Asc().
type Sort runtime.Tok

// Order replaces the ordering. Passing none restores the default.
//
// An ordering is part of a statement's identity, not a decoration on it:
// two queries differing only in ORDER BY are different statements, so the
// terms join the token stream that keys the compiled-statement cache.
func (q Query) Order(ts ...Sort) Query {
	q.no = 0
	for _, t := range ts {
		if int(q.no) >= len(q.otoks) {
			q.over = true
			return q
		}
		q.otoks[q.no] = runtime.Tok(t)
		q.no++
	}
	return q
}

// Err reports a query that outgrew its buffers.
func (q Query) Err() error {
	if q.over {
		return errTooComplex
	}
	if q.mixed {
		return errMixedOrder
	}
	if q.badAfter {
		return errAfterUnordered
	}
	return nil
}

var errAfterUnordered = errors.New(
	"storm: After() on an Unordered() query with no explicit Order — a keyset cursor without an ordering is a position in nothing")

var errMixedOrder = errors.New(
	"storm: After() needs every ORDER BY term in the same direction; a mixed ordering has no single row comparison, and expanding it into ORs gives up the index walk that makes keyset pagination worth doing")

var errTooComplex = errors.New(
	"storm: query has more predicates than the generated buffers hold; split it, or raise the limits in codegen")

// push and leaf mutate through a pointer so the builder loop does not
// copy the whole Query twice per predicate. They are only ever called on
// a local, so the public API keeps value semantics: q2 := q1.Where(x)
// must not mutate q1.
func (q *Query) push(t runtime.Tok) {
	if int(q.nt) >= len(q.toks) {
		q.over = true
		return
	}
	q.toks[q.nt] = t
	q.nt++
}

// preds returns the predicate stream with top-level conjuncts ANDed.
// A count uses this: ordering a scalar is wasted work, and including the
// terms would compile a second statement per ordering for no difference.
func (q Query) preds(buf *[21]runtime.Tok) []runtime.Tok {
	n := copy(buf[:], q.toks[:q.nt])
	if q.top > 1 {
		buf[n] = runtime.MakeGroup(runtime.KAnd, uint32(q.top))
		n++
	}
	return buf[:n]
}

// stream is the predicates followed by the ordering — the whole statement
// key. Order tokens go last so a splicer can find the boundary by kind.
func (q Query) stream(buf *[21]runtime.Tok) []runtime.Tok {
	n := len(q.preds(buf))
	if q.no == 0 {
		if q.noOrder {
			return buf[:n]
		}
		n += copy(buf[n:], defaultOrder[:])
		return buf[:n]
	}
	n += copy(buf[n:], q.otoks[:q.no])
	return buf[:n]
}

// Pred is one predicate, produced by a typed column handle. A value with
// a small union payload: no interface, nothing to allocate. Structure is
// assembled by Query into a token stream — see Where/Any/Not.
type Pred struct {
	col    uint8
	op     runtime.Op
	num    int64
	raw    [16]byte
	tim    time.Time
	dec    runtime.Decimal
	anyRaw [][16]byte
	anyI32 []int32
}

// Typed column handles. The type of the handle is what makes
// Age.Like(...) fail to compile.
var (
	ID        = UUIDCol{0}
	CreatedAt = TimeCol{1}
	UpdatedAt = TimeCol{2}
	OrderID   = UUIDCol{3}
	ProductID = UUIDCol{4}
	Quantity  = Int32Col{5}
	UnitPrice = DecimalCol{6}
)

// UUIDCol addresses a uuid column.
type UUIDCol struct{ c uint8 }

func (h UUIDCol) Asc() Sort  { return Sort(runtime.MakeOrder(runtime.Asc, uint32(h.c))) }
func (h UUIDCol) Desc() Sort { return Sort(runtime.MakeOrder(runtime.Desc, uint32(h.c))) }
func (h UUIDCol) AscNullsFirst() Sort {
	return Sort(runtime.MakeOrder(runtime.AscNullsFirst, uint32(h.c)))
}
func (h UUIDCol) DescNullsLast() Sort {
	return Sort(runtime.MakeOrder(runtime.DescNullsLast, uint32(h.c)))
}

func (h UUIDCol) Eq(v [16]byte) Pred    { return Pred{col: h.c, op: opEq, raw: v} }
func (h UUIDCol) NotEq(v [16]byte) Pred { return Pred{col: h.c, op: opNotEq, raw: v} }
func (h UUIDCol) In(v ...[16]byte) Pred { return Pred{col: h.c, op: opIn, anyRaw: v} }

// NotIn is `<> ALL($1)`. A NULL anywhere in v makes the
// comparison NULL for every row and the result empty —
// PostgreSQL's rule for NOT IN, not storm's.
func (h UUIDCol) NotIn(v ...[16]byte) Pred { return Pred{col: h.c, op: opNotIn, anyRaw: v} }

// TimeCol addresses a timestamptz column.
type TimeCol struct{ c uint8 }

func (h TimeCol) Asc() Sort  { return Sort(runtime.MakeOrder(runtime.Asc, uint32(h.c))) }
func (h TimeCol) Desc() Sort { return Sort(runtime.MakeOrder(runtime.Desc, uint32(h.c))) }
func (h TimeCol) AscNullsFirst() Sort {
	return Sort(runtime.MakeOrder(runtime.AscNullsFirst, uint32(h.c)))
}
func (h TimeCol) DescNullsLast() Sort {
	return Sort(runtime.MakeOrder(runtime.DescNullsLast, uint32(h.c)))
}

func (h TimeCol) Eq(v time.Time) Pred    { return Pred{col: h.c, op: opEq, tim: v} }
func (h TimeCol) NotEq(v time.Time) Pred { return Pred{col: h.c, op: opNotEq, tim: v} }
func (h TimeCol) Gt(v time.Time) Pred    { return Pred{col: h.c, op: opGt, tim: v} }
func (h TimeCol) Gte(v time.Time) Pred   { return Pred{col: h.c, op: opGte, tim: v} }
func (h TimeCol) Lt(v time.Time) Pred    { return Pred{col: h.c, op: opLt, tim: v} }
func (h TimeCol) Lte(v time.Time) Pred   { return Pred{col: h.c, op: opLte, tim: v} }

// Int32Col addresses a int4 column.
type Int32Col struct{ c uint8 }

func (h Int32Col) Asc() Sort  { return Sort(runtime.MakeOrder(runtime.Asc, uint32(h.c))) }
func (h Int32Col) Desc() Sort { return Sort(runtime.MakeOrder(runtime.Desc, uint32(h.c))) }
func (h Int32Col) AscNullsFirst() Sort {
	return Sort(runtime.MakeOrder(runtime.AscNullsFirst, uint32(h.c)))
}
func (h Int32Col) DescNullsLast() Sort {
	return Sort(runtime.MakeOrder(runtime.DescNullsLast, uint32(h.c)))
}

func (h Int32Col) Eq(v int32) Pred    { return Pred{col: h.c, op: opEq, num: int64(v)} }
func (h Int32Col) NotEq(v int32) Pred { return Pred{col: h.c, op: opNotEq, num: int64(v)} }
func (h Int32Col) Gt(v int32) Pred    { return Pred{col: h.c, op: opGt, num: int64(v)} }
func (h Int32Col) Gte(v int32) Pred   { return Pred{col: h.c, op: opGte, num: int64(v)} }
func (h Int32Col) Lt(v int32) Pred    { return Pred{col: h.c, op: opLt, num: int64(v)} }
func (h Int32Col) Lte(v int32) Pred   { return Pred{col: h.c, op: opLte, num: int64(v)} }
func (h Int32Col) In(v ...int32) Pred { return Pred{col: h.c, op: opIn, anyI32: v} }

// NotIn is `<> ALL($1)`. A NULL anywhere in v makes the
// comparison NULL for every row and the result empty —
// PostgreSQL's rule for NOT IN, not storm's.
func (h Int32Col) NotIn(v ...int32) Pred { return Pred{col: h.c, op: opNotIn, anyI32: v} }

// DecimalCol addresses a numeric(12,2) column.
type DecimalCol struct{ c uint8 }

func (h DecimalCol) Asc() Sort  { return Sort(runtime.MakeOrder(runtime.Asc, uint32(h.c))) }
func (h DecimalCol) Desc() Sort { return Sort(runtime.MakeOrder(runtime.Desc, uint32(h.c))) }
func (h DecimalCol) AscNullsFirst() Sort {
	return Sort(runtime.MakeOrder(runtime.AscNullsFirst, uint32(h.c)))
}
func (h DecimalCol) DescNullsLast() Sort {
	return Sort(runtime.MakeOrder(runtime.DescNullsLast, uint32(h.c)))
}

func (h DecimalCol) Eq(v runtime.Decimal) Pred    { return Pred{col: h.c, op: opEq, dec: v} }
func (h DecimalCol) NotEq(v runtime.Decimal) Pred { return Pred{col: h.c, op: opNotEq, dec: v} }
func (h DecimalCol) Gt(v runtime.Decimal) Pred    { return Pred{col: h.c, op: opGt, dec: v} }
func (h DecimalCol) Gte(v runtime.Decimal) Pred   { return Pred{col: h.c, op: opGte, dec: v} }
func (h DecimalCol) Lt(v runtime.Decimal) Pred    { return Pred{col: h.c, op: opLt, dec: v} }
func (h DecimalCol) Lte(v runtime.Decimal) Pred   { return Pred{col: h.c, op: opLte, dec: v} }

// Where applies predicates, ANDed together.
func (q Query) Where(ps ...Pred) Query {
	for i := range ps {
		q.leaf(ps[i])
		q.top++
	}
	return q
}

// WhenSet applies f(*v) only when v is non-nil — the optional-filter
// idiom without an if, and without the nil dereference WhereIf invites.
//
//	q = user.WhenSet(q, f.MinAge, user.Age.Gte)
//
// WhereIf takes an already-built Pred, so the caller has to evaluate
// user.Age.Gte(*f.MinAge) BEFORE the condition is tested — which panics
// on exactly the nil the condition was checking for. This takes the
// constructor instead, so nothing is dereferenced unless it is there.
//
// It still sets exactly one bit in the shape mask: a filter that is
// absent is a different SHAPE, compiled once, not a different value.
func WhenSet[T any](q Query, v *T, f func(T) Pred) Query {
	if v == nil {
		return q
	}
	return q.Where(f(*v))
}

// WhereIf applies a predicate only when cond holds.
func (q Query) WhereIf(cond bool, p Pred) Query {
	if !cond {
		return q
	}
	return q.Where(p)
}

// Any ORs its arguments and ANDs the group with the rest of the query:
// Where(a).Any(b, c) is a AND (b OR c).
func (q Query) Any(ps ...Pred) Query {
	if len(ps) == 0 {
		return q
	}
	for i := range ps {
		q.leaf(ps[i])
	}
	q.push(runtime.MakeGroup(runtime.KOr, uint32(len(ps))))
	q.top++
	return q
}

// Not negates one predicate and ANDs it with the rest.
func (q Query) Not(p Pred) Query {
	q.leaf(p)
	q.push(runtime.MakeGroup(runtime.KNot, 1))
	q.top++
	return q
}

// NotAny negates a disjunction: NOT (a OR b).
func (q Query) NotAny(ps ...Pred) Query {
	if len(ps) == 0 {
		return q
	}
	for i := range ps {
		q.leaf(ps[i])
	}
	q.push(runtime.MakeGroup(runtime.KOr, uint32(len(ps))))
	q.push(runtime.MakeGroup(runtime.KNot, 1))
	q.top++
	return q
}

// leaf records one predicate: its value goes to the arena for its type,
// its structure to the token stream.
func (q *Query) leaf(p Pred) {
	if p.op == opIn || p.op == opNotIn || p.op == opArrayContains || p.op == opArrayContainedBy || p.op == opArrayOverlaps {
		switch p.col {
		case 0:
			if int(q.nar) >= 3 {
				q.over = true
				return
			}
			q.anyRaw[q.nar] = p.anyRaw
			q.nar++
		case 3:
			if int(q.nar) >= 3 {
				q.over = true
				return
			}
			q.anyRaw[q.nar] = p.anyRaw
			q.nar++
		case 4:
			if int(q.nar) >= 3 {
				q.over = true
				return
			}
			q.anyRaw[q.nar] = p.anyRaw
			q.nar++
		case 5:
			if int(q.nai32) >= 3 {
				q.over = true
				return
			}
			q.anyI32[q.nai32] = p.anyI32
			q.nai32++
		}
		q.push(runtime.MakeLeaf(uint32(p.op), uint32(p.col)))
		return
	}
	switch p.col {
	case 0:
		if int(q.nr) >= 4 {
			q.over = true
			return
		}
		q.raws[q.nr] = p.raw
		q.nr++
	case 1:
		if int(q.ntm) >= 4 {
			q.over = true
			return
		}
		q.tims[q.ntm] = p.tim
		q.ntm++
	case 2:
		if int(q.ntm) >= 4 {
			q.over = true
			return
		}
		q.tims[q.ntm] = p.tim
		q.ntm++
	case 3:
		if int(q.nr) >= 4 {
			q.over = true
			return
		}
		q.raws[q.nr] = p.raw
		q.nr++
	case 4:
		if int(q.nr) >= 4 {
			q.over = true
			return
		}
		q.raws[q.nr] = p.raw
		q.nr++
	case 5:
		if int(q.nn) >= 6 {
			q.over = true
			return
		}
		q.nums[q.nn] = p.num
		q.nn++
	case 6:
		if int(q.nd) >= 4 {
			q.over = true
			return
		}
		q.decs[q.nd] = p.dec
		q.nd++
	}
	q.push(runtime.MakeLeaf(uint32(p.op), uint32(p.col)))
}

// Chained predicate sugar. Identical to Where(Col.Op(v)).
func (q Query) IDEq(v [16]byte) Query                  { return q.Where(ID.Eq(v)) }
func (q Query) IDNotEq(v [16]byte) Query               { return q.Where(ID.NotEq(v)) }
func (q Query) IDIn(v ...[16]byte) Query               { return q.Where(ID.In(v...)) }
func (q Query) IDNotIn(v ...[16]byte) Query            { return q.Where(ID.NotIn(v...)) }
func (q Query) CreatedAtEq(v time.Time) Query          { return q.Where(CreatedAt.Eq(v)) }
func (q Query) CreatedAtNotEq(v time.Time) Query       { return q.Where(CreatedAt.NotEq(v)) }
func (q Query) CreatedAtGt(v time.Time) Query          { return q.Where(CreatedAt.Gt(v)) }
func (q Query) CreatedAtGte(v time.Time) Query         { return q.Where(CreatedAt.Gte(v)) }
func (q Query) CreatedAtLt(v time.Time) Query          { return q.Where(CreatedAt.Lt(v)) }
func (q Query) CreatedAtLte(v time.Time) Query         { return q.Where(CreatedAt.Lte(v)) }
func (q Query) UpdatedAtEq(v time.Time) Query          { return q.Where(UpdatedAt.Eq(v)) }
func (q Query) UpdatedAtNotEq(v time.Time) Query       { return q.Where(UpdatedAt.NotEq(v)) }
func (q Query) UpdatedAtGt(v time.Time) Query          { return q.Where(UpdatedAt.Gt(v)) }
func (q Query) UpdatedAtGte(v time.Time) Query         { return q.Where(UpdatedAt.Gte(v)) }
func (q Query) UpdatedAtLt(v time.Time) Query          { return q.Where(UpdatedAt.Lt(v)) }
func (q Query) UpdatedAtLte(v time.Time) Query         { return q.Where(UpdatedAt.Lte(v)) }
func (q Query) OrderIDEq(v [16]byte) Query             { return q.Where(OrderID.Eq(v)) }
func (q Query) OrderIDNotEq(v [16]byte) Query          { return q.Where(OrderID.NotEq(v)) }
func (q Query) OrderIDIn(v ...[16]byte) Query          { return q.Where(OrderID.In(v...)) }
func (q Query) OrderIDNotIn(v ...[16]byte) Query       { return q.Where(OrderID.NotIn(v...)) }
func (q Query) ProductIDEq(v [16]byte) Query           { return q.Where(ProductID.Eq(v)) }
func (q Query) ProductIDNotEq(v [16]byte) Query        { return q.Where(ProductID.NotEq(v)) }
func (q Query) ProductIDIn(v ...[16]byte) Query        { return q.Where(ProductID.In(v...)) }
func (q Query) ProductIDNotIn(v ...[16]byte) Query     { return q.Where(ProductID.NotIn(v...)) }
func (q Query) QuantityEq(v int32) Query               { return q.Where(Quantity.Eq(v)) }
func (q Query) QuantityNotEq(v int32) Query            { return q.Where(Quantity.NotEq(v)) }
func (q Query) QuantityGt(v int32) Query               { return q.Where(Quantity.Gt(v)) }
func (q Query) QuantityGte(v int32) Query              { return q.Where(Quantity.Gte(v)) }
func (q Query) QuantityLt(v int32) Query               { return q.Where(Quantity.Lt(v)) }
func (q Query) QuantityLte(v int32) Query              { return q.Where(Quantity.Lte(v)) }
func (q Query) QuantityIn(v ...int32) Query            { return q.Where(Quantity.In(v...)) }
func (q Query) QuantityNotIn(v ...int32) Query         { return q.Where(Quantity.NotIn(v...)) }
func (q Query) UnitPriceEq(v runtime.Decimal) Query    { return q.Where(UnitPrice.Eq(v)) }
func (q Query) UnitPriceNotEq(v runtime.Decimal) Query { return q.Where(UnitPrice.NotEq(v)) }
func (q Query) UnitPriceGt(v runtime.Decimal) Query    { return q.Where(UnitPrice.Gt(v)) }
func (q Query) UnitPriceGte(v runtime.Decimal) Query   { return q.Where(UnitPrice.Gte(v)) }
func (q Query) UnitPriceLt(v runtime.Decimal) Query    { return q.Where(UnitPrice.Lt(v)) }
func (q Query) UnitPriceLte(v runtime.Decimal) Query   { return q.Where(UnitPrice.Lte(v)) }

const selectPrefix = `SELECT "id", "created_at", "updated_at", "order_id", "product_id", "quantity", "unit_price" FROM "order_lines"`
const countPrefix = `SELECT count(*) FROM "order_lines"`
const existsPrefix = `SELECT 1 FROM "order_lines"`
const existsSuffix = ` LIMIT 1`
const limitSuffix = ` LIMIT $`
const limitOffsetSuffix = ` LIMIT $ OFFSET $`

// orderTable is every ordering this table can express, lowered at build
// time. ORDER BY is chosen per query, so it cannot be a constant — but it
// still must not be built from strings at run time.
var orderTable = [nCols][4]string{
	{ // id
		"\"id\"",
		"\"id\" DESC",
		"\"id\" ASC NULLS FIRST",
		"\"id\" DESC NULLS LAST",
	},
	{ // created_at
		"\"created_at\"",
		"\"created_at\" DESC",
		"\"created_at\" ASC NULLS FIRST",
		"\"created_at\" DESC NULLS LAST",
	},
	{ // updated_at
		"\"updated_at\"",
		"\"updated_at\" DESC",
		"\"updated_at\" ASC NULLS FIRST",
		"\"updated_at\" DESC NULLS LAST",
	},
	{ // order_id
		"\"order_id\"",
		"\"order_id\" DESC",
		"\"order_id\" ASC NULLS FIRST",
		"\"order_id\" DESC NULLS LAST",
	},
	{ // product_id
		"\"product_id\"",
		"\"product_id\" DESC",
		"\"product_id\" ASC NULLS FIRST",
		"\"product_id\" DESC NULLS LAST",
	},
	{ // quantity
		"\"quantity\"",
		"\"quantity\" DESC",
		"\"quantity\" ASC NULLS FIRST",
		"\"quantity\" DESC NULLS LAST",
	},
	{ // unit_price
		"\"unit_price\"",
		"\"unit_price\" DESC",
		"\"unit_price\" ASC NULLS FIRST",
		"\"unit_price\" DESC NULLS LAST",
	},
}

// identTable is each column's bare quoted name, for the left side of a
// row comparison.
var identTable = [nCols]string{
	"\"id\"",
	"\"created_at\"",
	"\"updated_at\"",
	"\"order_id\"",
	"\"product_id\"",
	"\"quantity\"",
	"\"unit_price\"",
}

var lowering = runtime.Lowering{
	Frag:  fragOf,
	Order: orderOf,
	OB:    runtime.Order{Lead: " ORDER BY ", Sep: ", "},
	Ident: func(col uint32) string {
		if col >= nCols {
			return ""
		}
		return identTable[col]
	},
	RowCmp: func(op uint32) string {
		if op == runtime.CmpLt {
			return " < "
		}
		return " > "
	},
	TupleOpen:  "(",
	TupleSep:   ", ",
	TupleClose: ")",
}

func orderOf(dir, col uint32) string {
	if col >= nCols || int(dir) >= len(orderTable[0]) {
		return ""
	}
	return orderTable[col][dir]
}

// fragTable is every predicate this table can produce, lowered at build
// time. Runtime splices; it never formats.
var fragTable = [7][23]runtime.Frag{
	{ // id
		{}, // opNone
		{A: "\"id\" = $", B: ""},
		{A: "\"id\" <> $", B: ""},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{A: "\"id\" = ANY($", B: ")"},
		{A: "\"id\" <> ALL($", B: ")"},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
	},
	{ // created_at
		{}, // opNone
		{A: "\"created_at\" = $", B: ""},
		{A: "\"created_at\" <> $", B: ""},
		{A: "\"created_at\" > $", B: ""},
		{A: "\"created_at\" >= $", B: ""},
		{A: "\"created_at\" < $", B: ""},
		{A: "\"created_at\" <= $", B: ""},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
	},
	{ // updated_at
		{}, // opNone
		{A: "\"updated_at\" = $", B: ""},
		{A: "\"updated_at\" <> $", B: ""},
		{A: "\"updated_at\" > $", B: ""},
		{A: "\"updated_at\" >= $", B: ""},
		{A: "\"updated_at\" < $", B: ""},
		{A: "\"updated_at\" <= $", B: ""},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
	},
	{ // order_id
		{}, // opNone
		{A: "\"order_id\" = $", B: ""},
		{A: "\"order_id\" <> $", B: ""},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{A: "\"order_id\" = ANY($", B: ")"},
		{A: "\"order_id\" <> ALL($", B: ")"},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
	},
	{ // product_id
		{}, // opNone
		{A: "\"product_id\" = $", B: ""},
		{A: "\"product_id\" <> $", B: ""},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{A: "\"product_id\" = ANY($", B: ")"},
		{A: "\"product_id\" <> ALL($", B: ")"},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
	},
	{ // quantity
		{}, // opNone
		{A: "\"quantity\" = $", B: ""},
		{A: "\"quantity\" <> $", B: ""},
		{A: "\"quantity\" > $", B: ""},
		{A: "\"quantity\" >= $", B: ""},
		{A: "\"quantity\" < $", B: ""},
		{A: "\"quantity\" <= $", B: ""},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{A: "\"quantity\" = ANY($", B: ")"},
		{A: "\"quantity\" <> ALL($", B: ")"},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
	},
	{ // unit_price
		{}, // opNone
		{A: "\"unit_price\" = $", B: ""},
		{A: "\"unit_price\" <> $", B: ""},
		{A: "\"unit_price\" > $", B: ""},
		{A: "\"unit_price\" >= $", B: ""},
		{A: "\"unit_price\" < $", B: ""},
		{A: "\"unit_price\" <= $", B: ""},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
	},
}

func fragOf(op, col uint32) runtime.Frag {
	// Bounded by the table, not nCols: existence pseudo-columns live past
	// the real ones. Order, ident and arena lookups stay nCols-bounded,
	// so a pseudo-column can never be ordered by, cursored on, or bound.
	if int(col) >= len(fragTable) || int(op) >= len(fragTable[0]) {
		return runtime.Frag{}
	}
	return fragTable[col][op]
}

// defaultOrder is what a query with no Order() uses.
//
// It is never empty. A read without ORDER BY has no defined order, so
// paging one is a bug waiting for a plan change to expose it — and the
// primary key is the cheapest total order available.
var defaultOrder = [1]runtime.Tok{
	runtime.MakeOrder(runtime.Asc, 0), // id
}

var (
	cache       = runtime.NewTreeCache()
	offsetCache = runtime.NewTreeCache()
	countCache  = runtime.NewTreeCache()
	existsCache = runtime.NewTreeCache()
)

// Shapes reports how many distinct query structures have compiled.
// `storm lint` uses it to catch a builder minting a statement per request.
func Shapes() int { return cache.Shapes() }

// ShapeFlushes reports how many times a shape cache in this package hit
// runtime.ShapeCap and dropped. Zero is the expected value forever:
// nonzero means a call site is minting structures from request data
// rather than from code, and the fix is that call site, not a bigger
// cap. Export it as a gauge — it is the cheapest early warning that a
// filter screen turned into 2^n statements.
func ShapeFlushes() int {
	return cache.Flushes() + offsetCache.Flushes() +
		countCache.Flushes() + existsCache.Flushes()
}

// stmtFor compiles a read. LIMIT and LIMIT/OFFSET are different
// statements with different placeholder counts, so they get different
// caches rather than a sentinel token muddying the key.
func stmtFor(toks []runtime.Tok, withOffset bool) *runtime.Stmt {
	c, suffix := cache, limitSuffix
	if withOffset {
		c, suffix = offsetCache, limitOffsetSuffix
	}
	if st := c.Get(toks); st != nil {
		return st
	}
	return c.Put(toks, runtime.SpliceTree(selectPrefix, toks, lowering, suffix))
}

// existsStmtFor compiles the existence probe: SELECT 1, no ORDER BY,
// LIMIT 1 — the planner stops at the first matching tuple instead of
// sorting every match to return the "first" of an order nobody reads.
func existsStmtFor(toks []runtime.Tok) *runtime.Stmt {
	if st := existsCache.Get(toks); st != nil {
		return st
	}
	return existsCache.Put(toks, runtime.SpliceTree(existsPrefix, toks, lowering, existsSuffix))
}

func countStmtFor(toks []runtime.Tok) *runtime.Stmt {
	if st := countCache.Get(toks); st != nil {
		return st
	}
	// A count ignores ordering as well as LIMIT: ordering a scalar is
	// wasted work, and the token stream is trimmed before it gets here.
	return countCache.Put(toks, runtime.SpliceTree(countPrefix, toks, lowering, ""))
}

// Composition seams, for the generated CONTEXT package and it alone:
// cross-table statements (a filtered semi-join spans two packages) are
// assembled there from each side's tokens, fragments and bindings. Ids
// only — no SQL text and no value crosses here.

// FragOf is the compiled fragment table, exported for composition.
func FragOf(op, col uint32) runtime.Frag { return fragOf(op, col) }

// Lowering is this package's back-end text, exported for composition.
func Lowering() runtime.Lowering { return lowering }

// StmtPieces are the statement's constant parts, exported for composition.
func StmtPieces() (selectPfx, countPfx, limitSfx string) {
	return selectPrefix, countPrefix, limitSuffix
}

// PredToks appends this query's predicate stream to dst: top-level
// conjuncts reduced to one entry, order excluded.
func (q Query) PredToks(dst []runtime.Tok) []runtime.Tok {
	var buf [21]runtime.Tok
	return append(dst, q.preds(&buf)...)
}

// OrderToks appends this query's ordering — explicit, or the default
// unless Unordered.
func (q Query) OrderToks(dst []runtime.Tok) []runtime.Tok {
	if q.no == 0 {
		if q.noOrder {
			return dst
		}
		return append(dst, defaultOrder[:]...)
	}
	return append(dst, q.otoks[:q.no]...)
}

// BindPreds binds this query's predicate values into b, appending to v.
func (q Query) BindPreds(b *Binder, v []any) []any {
	return append(v, q.bindPreds(b)...)
}

// BindPaging appends the LIMIT (and OFFSET when set) arguments.
func (q Query) BindPaging(b *Binder, v []any) []any {
	b.limit = q.limit
	v = append(v, &b.limit)
	if q.offset > 0 {
		b.offset = q.offset
		v = append(v, &b.offset)
	}
	return v
}

// Shape is a fingerprint of this query's structure — equal shapes share a
// compiled statement. Values do not contribute, which is the point.
func (q Query) Shape() uint64 {
	var buf [21]runtime.Tok
	return runtime.HashToks(q.stream(&buf))
}

// SQL returns the compiled text for this query's structure.
func (q Query) SQL() string {
	var buf [21]runtime.Tok
	return stmtFor(q.stream(&buf), q.offset > 0).SQL
}

// Scan decodes one row from raw wire bytes into r, copying text into sl.
//
// Exported for the context package, which assembles batched results and
// therefore has to decode rows it did not issue the query for.
func Scan(rv [][]byte, r *Row, sl *runtime.Slab) error { return scan(rv, r, sl) }

// scan decodes one row straight from the wire. No reflect, no `any`, no
// driver.Value: the generator knows every column's type already.
//
// It returns an error only for a value the Go type cannot carry — a
// numeric past 18 significant digits, or a NaN. Those must not become a
// plausible zero, and a row scanner is the last place that can tell.
func scan(rv [][]byte, r *Row, sl *runtime.Slab) error {
	var decErr error
	copy(r.ID[:], rv[0])
	r.CreatedAt = runtime.Timestamptz(rv[1])
	r.UpdatedAt = runtime.Timestamptz(rv[2])
	copy(r.OrderID[:], rv[3])
	copy(r.ProductID[:], rv[4])
	r.Quantity = runtime.Int4(rv[5])
	r.UnitPrice, decErr = runtime.NumericErr(rv[6])
	if decErr != nil {
		return decErr
	}
	return decErr
}

type binder struct {
	vals   []any
	nums   [6]int64
	raws   [4][16]byte
	tims   [4]time.Time
	decs   [4]runtime.Decimal
	anyRaw [3][][16]byte
	anyI32 [3][]int32
	limit  int64
	offset int64
}

var binders = runtime.NewPool(func() *binder {
	return &binder{vals: make([]any, 0, 17)}
})

// Binder is the pooled argument buffer.
type Binder = binder

func GetBinder() *Binder  { return binders.Get() }
func PutBinder(b *Binder) { putBinder(b) }

// putBinder clears every field that references memory OUTSIDE the binder
// before pooling it. A pooled binder otherwise PINS the caller's data —
// the slice behind an In(...) and the bytes behind every bound string —
// for as long as the pool holds it, which is forever. The numeric, time
// and uuid arenas are value arrays and pin nothing; vals points at the
// binder's own fields. A few nil stores against a round trip is free.
func putBinder(b *binder) {
	for i := range b.anyRaw {
		b.anyRaw[i] = nil
	}
	for i := range b.anyI32 {
		b.anyI32[i] = nil
	}
	binders.Put(b)
}

// bindPreds copies arena values into the pooled buffer and points the
// []any at the buffer's own fields — boxing a pointer does not allocate.
// Count and Exists stop here: their statements carry no LIMIT or OFFSET.
func (q Query) bindPreds(b *binder) []any {
	v := b.vals[:0]
	var nn, nr, ntm, nd, nar, nai32 uint8
	for i := uint8(0); i < q.nt; i++ {
		t := q.toks[i]
		// KLeaf binds a predicate's value; KCol binds a keyset cursor's.
		// Both live in the same per-type arenas in stream order, so the
		// column switch below handles them identically. A KCol carries no
		// operator — its op is opNone, which matches no case in the
		// operator switch and falls straight through.
		if k := t.Kind(); k != runtime.KLeaf && k != runtime.KCol {
			continue
		}
		switch runtime.Op(t.Op()) {
		case opIsNull, opIsNotNull:
			continue
		case opIn, opNotIn, opArrayContains, opArrayContainedBy, opArrayOverlaps:
			switch t.Col() {
			case 0:
				b.anyRaw[nar] = q.anyRaw[nar]
				v = append(v, &b.anyRaw[nar])
				nar++
			case 3:
				b.anyRaw[nar] = q.anyRaw[nar]
				v = append(v, &b.anyRaw[nar])
				nar++
			case 4:
				b.anyRaw[nar] = q.anyRaw[nar]
				v = append(v, &b.anyRaw[nar])
				nar++
			case 5:
				b.anyI32[nai32] = q.anyI32[nai32]
				v = append(v, &b.anyI32[nai32])
				nai32++
			}
			continue
		}
		switch t.Col() {
		case 0:
			b.raws[nr] = q.raws[nr]
			v = append(v, &b.raws[nr])
			nr++
		case 1:
			b.tims[ntm] = q.tims[ntm]
			v = append(v, &b.tims[ntm])
			ntm++
		case 2:
			b.tims[ntm] = q.tims[ntm]
			v = append(v, &b.tims[ntm])
			ntm++
		case 3:
			b.raws[nr] = q.raws[nr]
			v = append(v, &b.raws[nr])
			nr++
		case 4:
			b.raws[nr] = q.raws[nr]
			v = append(v, &b.raws[nr])
			nr++
		case 5:
			b.nums[nn] = q.nums[nn]
			v = append(v, &b.nums[nn])
			nn++
		case 6:
			b.decs[nd] = q.decs[nd]
			v = append(v, &b.decs[nd])
			nd++
		}
	}
	b.vals = v
	return v
}

// bind is bindPreds plus the paging arguments, in suffix order.
func (q Query) bind(b *binder) []any {
	v := q.bindPreds(b)
	b.limit = q.limit
	v = append(v, &b.limit)
	// An offset of zero is absent from the statement, so binding it
	// would leave an argument nothing consumes.
	if q.offset > 0 {
		b.offset = q.offset
		v = append(v, &b.offset)
	}
	b.vals = v
	return v
}

// All runs the query and decodes every row.
func (q Query) All(ctx context.Context, ex runtime.Executor, dst []Row) ([]Row, error) {
	var sl runtime.Slab
	return q.AllInto(ctx, ex, dst, &sl)
}

// AllInto lets the caller own the string arena.
func (q Query) AllInto(ctx context.Context, ex runtime.Executor, dst []Row, sl *runtime.Slab) ([]Row, error) {
	if err := q.Err(); err != nil {
		return dst, err
	}
	var buf [21]runtime.Tok
	st := stmtFor(q.stream(&buf), q.offset > 0)
	if st.Err != nil {
		// A malformed token stream is a code-generation bug. Executing it
		// would run a query whose filter is not the one that was asked for.
		return dst, st.Err
	}
	sl.Reserve(st.SlabHint())
	b := binders.Get()
	defer putBinder(b)

	rows, err := ex.Query(ctx, st.SQL, q.bind(b))
	if err != nil {
		return dst, err
	}
	defer rows.Close()
	for rows.Next() {
		dst = append(dst, Row{})
		if err := scan(rows.RawValues(), &dst[len(dst)-1], sl); err != nil {
			return dst, err
		}
	}
	st.ObserveSlab(sl.Size())
	return dst, rows.Err()
}

// One returns the first row, if any.
func (q Query) One(ctx context.Context, ex runtime.Executor) (Row, bool, error) {
	var sl runtime.Slab
	var buf [1]Row
	out, err := q.Limit(1).AllInto(ctx, ex, buf[:0], &sl)
	if err != nil || len(out) == 0 {
		return Row{}, false, err
	}
	return out[0], true, nil
}

// Count ignores Limit: counting a truncated set is a bug, not a feature.
func (q Query) Count(ctx context.Context, ex runtime.Executor) (int64, error) {
	if err := q.Err(); err != nil {
		return 0, err
	}
	var buf [21]runtime.Tok
	st := countStmtFor(q.preds(&buf))
	if st.Err != nil {
		// A malformed token stream is a code-generation bug. Executing it
		// would run a query whose filter is not the one that was asked for.
		return 0, st.Err
	}
	b := binders.Get()
	defer putBinder(b)
	// bindPreds, not bind: a count has no LIMIT and no OFFSET. The old
	// form bound everything and sliced the last argument off, which was
	// the limit — unless Offset was set, in which case it silently kept
	// the limit and dropped the offset, and the statement mismatched.
	rows, err := ex.Query(ctx, st.SQL, q.bindPreds(b))
	if err != nil {
		return 0, err
	}
	defer rows.Close()
	var n int64
	if rows.Next() {
		n = runtime.Int8(rows.RawValues()[0])
	}
	return n, rows.Err()
}

// Exists asks the one-bit question with a one-bit statement: SELECT 1,
// no ORDER BY, LIMIT 1. It was previously One() with the row thrown
// away, which projected every column AND carried the default ordering —
// measured on 50k rows, the planner top-N-sorted all 16,667 matches to
// return the "first" of an order nobody was going to read.
func (q Query) Exists(ctx context.Context, ex runtime.Executor) (bool, error) {
	if err := q.Err(); err != nil {
		return false, err
	}
	var buf [21]runtime.Tok
	st := existsStmtFor(q.preds(&buf))
	if st.Err != nil {
		return false, st.Err
	}
	b := binders.Get()
	defer putBinder(b)
	rows, err := ex.Query(ctx, st.SQL, q.bindPreds(b))
	if err != nil {
		return false, err
	}
	defer rows.Close()
	return rows.Next(), rows.Err()
}

// Prepare resolves the structure and binds arguments without executing.
func (q Query) Prepare(b *Binder) (string, []any) {
	var buf [21]runtime.Tok
	return stmtFor(q.stream(&buf), q.offset > 0).SQL, q.bind(b)
}

// Greatest-n-per-group: at most n children per parent, in ONE query.
//
// The ordering is REQUIRED and must be a strict total order. "The first
// three by date" with ties on that date returns an arbitrary three, and
// a different arbitrary three on the next call — a paging bug that only
// appears under data the developer did not have. Add the primary key as
// a final term if the natural ordering is not unique.
var errNoTopOrder = errors.New(
	"storm: a per-parent limit needs an ordering — without one \"the first three\" is an arbitrary three, and a different three next time")

// BatchTopByOrderID fetches at most n rows for each id, ordered by order.
//
// ONE round trip regardless of how many ids are passed — the per-parent
// limit is expressed in SQL, not by looping. It delegates to the lowering
// chosen at BUILD time by measurement (bench/RESULTS.md); the strategy is
// never sniffed at run time.
func BatchTopByOrderID(ctx context.Context, ex runtime.Executor, ids [][16]byte, n int64, order ...Sort) ([]Row, error) {
	return BatchTopByOrderIDLateral(ctx, ex, ids, n, order...)
}

// BatchTopByOrderIDWindow runs the window lowering.
//
// Both forms are exported so a benchmark can compare them on identical
// generated code rather than on two hand-written approximations, and so
// a caller whose data defeats the default has a way out that does not
// involve writing SQL.
func BatchTopByOrderIDWindow(ctx context.Context, ex runtime.Executor, ids [][16]byte, n int64, order ...Sort) ([]Row, error) {
	return batchTopByOrderIDRun(ctx, ex, batchTopByOrderIDWindowSQL(order), ids, n)
}

// BatchTopByOrderIDLateral runs the lateral lowering.
//
// Both forms are exported so a benchmark can compare them on identical
// generated code rather than on two hand-written approximations, and so
// a caller whose data defeats the default has a way out that does not
// involve writing SQL.
func BatchTopByOrderIDLateral(ctx context.Context, ex runtime.Executor, ids [][16]byte, n int64, order ...Sort) ([]Row, error) {
	return batchTopByOrderIDRun(ctx, ex, batchTopByOrderIDLateralSQL(order), ids, n)
}

// batchTopByOrderIDRun executes one lowered statement.
func batchTopByOrderIDRun(ctx context.Context, ex runtime.Executor, sql string, ids [][16]byte, n int64) ([]Row, error) {
	if len(ids) == 0 || n <= 0 {
		return nil, nil
	}
	if sql == "" {
		return nil, errNoTopOrder
	}
	rows, err := ex.Query(ctx, sql, []any{ids, n})
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var sl runtime.Slab
	out := make([]Row, 0, int64(len(ids))*n)
	for rows.Next() {
		out = append(out, Row{})
		if err := scan(rows.RawValues(), &out[len(out)-1], &sl); err != nil {
			return nil, err
		}
	}
	return out, rows.Err()
}

var batchTopByOrderIDWindowCache = runtime.NewTreeCache()

// batchTopByOrderIDWindowSQL compiles one ordering, once. The ordering is the key, exactly
// as it is for an ordinary read; an empty ordering yields "", which the
// runner turns into errNoTopOrder.
func batchTopByOrderIDWindowSQL(order []Sort) string {
	if len(order) == 0 {
		return ""
	}
	toks := make([]runtime.Tok, len(order))
	for i, s := range order {
		toks[i] = runtime.Tok(s)
	}
	if st := batchTopByOrderIDWindowCache.Get(toks); st != nil {
		return st.SQL
	}
	terms := make([]string, len(toks))
	for i, t := range toks {
		terms[i] = orderOf(t.Op(), t.Col())
	}
	sql := runtime.SpliceOrder("SELECT \"id\", \"created_at\", \"updated_at\", \"order_id\", \"product_id\", \"quantity\", \"unit_price\" FROM (SELECT \"id\", \"created_at\", \"updated_at\", \"order_id\", \"product_id\", \"quantity\", \"unit_price\", row_number() OVER (PARTITION BY \"order_id\"\x00order\x00) AS \"_storm_rn\" FROM \"order_lines\" WHERE \"order_id\" = ANY($1)) \"_storm_t\" WHERE \"_storm_rn\" <= $2", terms, " ORDER BY ", ", ")
	return batchTopByOrderIDWindowCache.Put(toks, &runtime.Stmt{SQL: sql, NArg: 2}).SQL
}

var batchTopByOrderIDLateralCache = runtime.NewTreeCache()

// batchTopByOrderIDLateralSQL compiles one ordering, once. The ordering is the key, exactly
// as it is for an ordinary read; an empty ordering yields "", which the
// runner turns into errNoTopOrder.
func batchTopByOrderIDLateralSQL(order []Sort) string {
	if len(order) == 0 {
		return ""
	}
	toks := make([]runtime.Tok, len(order))
	for i, s := range order {
		toks[i] = runtime.Tok(s)
	}
	if st := batchTopByOrderIDLateralCache.Get(toks); st != nil {
		return st.SQL
	}
	terms := make([]string, len(toks))
	for i, t := range toks {
		terms[i] = orderOf(t.Op(), t.Col())
	}
	sql := runtime.SpliceOrder("SELECT \"_storm_c\".\"id\", \"_storm_c\".\"created_at\", \"_storm_c\".\"updated_at\", \"_storm_c\".\"order_id\", \"_storm_c\".\"product_id\", \"_storm_c\".\"quantity\", \"_storm_c\".\"unit_price\" FROM unnest($1::uuid[]) AS \"_storm_p\"(\"_storm_k\") CROSS JOIN LATERAL (SELECT \"id\", \"created_at\", \"updated_at\", \"order_id\", \"product_id\", \"quantity\", \"unit_price\" FROM \"order_lines\" WHERE \"order_id\" = \"_storm_p\".\"_storm_k\"\x00order\x00 LIMIT $2) \"_storm_c\"", terms, " ORDER BY ", ", ")
	return batchTopByOrderIDLateralCache.Put(toks, &runtime.Stmt{SQL: sql, NArg: 2}).SQL
}

// insertSQL does not vary: the column list is fixed by the table, so
// the placeholders are known at build time and nothing is spliced.
const insertSQL = `INSERT INTO "order_lines" ("id", "created_at", "updated_at", "order_id", "product_id", "quantity", "unit_price") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id", "created_at", "updated_at", "order_id", "product_id", "quantity", "unit_price"`

const updatePrefix = `UPDATE "order_lines" SET `
const deletePrefix = `DELETE FROM "order_lines"`

// Dirty bits. One per updatable column; the set of them is an UPDATE's
// identity, exactly as a token stream is a SELECT's.
const (
	dUpdatedAt uint64 = 1 << 0
	dOrderID   uint64 = 1 << 1
	dProductID uint64 = 1 << 2
	dQuantity  uint64 = 1 << 3
	dUnitPrice uint64 = 1 << 4
)

const nUpdatable = 5

// setFrags is every assignment this table can make, lowered at build time.
var setFrags = [nUpdatable]runtime.Frag{
	{A: "\"updated_at\" = $", B: ""}, // updated_at
	{A: "\"order_id\" = $", B: ""},   // order_id
	{A: "\"product_id\" = $", B: ""}, // product_id
	{A: "\"quantity\" = $", B: ""},   // quantity
	{A: "\"unit_price\" = $", B: ""}, // unit_price
}

// pkFrags addresses one row.
var pkFrags = [1]runtime.Frag{
	{A: "\"id\" = $", B: ""}, // id
}

// Insert bits. A masked INSERT names only the columns the caller
// assigned, so every other column takes its database default — which is
// the only way a DEFAULT gen_random_uuid() can ever fire.
const (
	iID        uint64 = 1 << 0
	iCreatedAt uint64 = 1 << 1
	iUpdatedAt uint64 = 1 << 2
	iOrderID   uint64 = 1 << 3
	iProductID uint64 = 1 << 4
	iQuantity  uint64 = 1 << 5
	iUnitPrice uint64 = 1 << 6
)

const nInsertable = 7

// insCols is the quoted column name for each insert bit.
var insCols = [nInsertable]string{
	"\"id\"",
	"\"created_at\"",
	"\"updated_at\"",
	"\"order_id\"",
	"\"product_id\"",
	"\"quantity\"",
	"\"unit_price\"",
}

// insParts and insPlaceholder come from the back end at build time; the
// runtime splicer chooses none of them.
var insParts = runtime.InsertParts{Open: " (", Sep: ", ", Mid: ") VALUES (", Close: ")"}

const insPlaceholder = "$"
const insPrefix = "INSERT INTO \"order_lines\""
const insReturning = " RETURNING \"id\", \"created_at\", \"updated_at\", \"order_id\", \"product_id\", \"quantity\", \"unit_price\""

var insCache = runtime.NewMaskCache()
var updCache = runtime.NewMaskCache()

// Masks reports how many distinct UPDATE shapes have compiled.
func Masks() int { return updCache.Masks() }

// Mut is a row staged for update: the values, plus which of them were
// actually assigned. An UPDATE writes the assigned ones and no others,
// so a read-modify-write cannot clobber a column it never looked at.
type Mut struct {
	row   Row
	dirty uint64
}

// Mutate stages a row read from the database.
func Mutate(r Row) Mut { return Mut{row: r} }

// Row returns the staged values.
func (m Mut) Row() Row { return m.row }

// Dirty reports the assigned-column mask, which is also the statement key.
func (m Mut) Dirty() uint64 { return m.dirty }

// Setters. There is deliberately no setter for the primary key, for an
// Immutable column, or for the version column: the absence of a method is
// the enforcement, so misuse does not compile rather than failing later.
func (m *Mut) SetUpdatedAt(v time.Time) {
	m.row.UpdatedAt = v
	m.dirty |= dUpdatedAt
}

func (m *Mut) SetOrderID(v [16]byte) {
	m.row.OrderID = v
	m.dirty |= dOrderID
}

func (m *Mut) SetProductID(v [16]byte) {
	m.row.ProductID = v
	m.dirty |= dProductID
}

func (m *Mut) SetQuantity(v int32) {
	m.row.Quantity = v
	m.dirty |= dQuantity
}

func (m *Mut) SetUnitPrice(v runtime.Decimal) {
	m.row.UnitPrice = v
	m.dirty |= dUnitPrice
}

// Ins stages a new row. Unlike Mut it has a setter for every insertable
// column including the primary key and Immutable ones — supplying your
// own id is legitimate, changing it later is not.
//
// A column left unset is absent from the statement, so the database
// applies its default. Absence is tracked by the mask, never inferred
// from a zero value: that inference is why other ORMs cannot insert a
// false, a 0 or an empty string into a column that has a default.
type Ins struct {
	row Row
	set uint64

	// conflict is the upsert target, as a bit per unique-constraint
	// column set. Zero means a plain insert, and a duplicate is an error
	// — which is the right default: silently updating a row you meant to
	// create is a data-loss bug that looks like success.
	conflict uint8
}

// Create stages a new row.
func Create() Ins { return Ins{} }

// Assigned reports the mask, which is also the statement key.
func (n Ins) Assigned() uint64 { return n.set }

func (n *Ins) SetID(v [16]byte) {
	n.row.ID = v
	n.set |= iID
}

func (n *Ins) SetCreatedAt(v time.Time) {
	n.row.CreatedAt = v
	n.set |= iCreatedAt
}

func (n *Ins) SetUpdatedAt(v time.Time) {
	n.row.UpdatedAt = v
	n.set |= iUpdatedAt
}

func (n *Ins) SetOrderID(v [16]byte) {
	n.row.OrderID = v
	n.set |= iOrderID
}

func (n *Ins) SetProductID(v [16]byte) {
	n.row.ProductID = v
	n.set |= iProductID
}

func (n *Ins) SetQuantity(v int32) {
	n.row.Quantity = v
	n.set |= iQuantity
}

func (n *Ins) SetUnitPrice(v runtime.Decimal) {
	n.row.UnitPrice = v
	n.set |= iUnitPrice
}

// upsertTails builds the ON CONFLICT tail for one target, given the
// insert mask — an upsert must only overwrite the columns the caller
// assigned, or it silently reverts every column it did not.
var upsertTails = []func(uint64) string{
	func(mask uint64) string {
		set := make([]string, 0, 5)
		if mask&(1<<2) != 0 {
			set = append(set, "updated_at")
		}
		if mask&(1<<3) != 0 {
			set = append(set, "order_id")
		}
		if mask&(1<<4) != 0 {
			set = append(set, "product_id")
		}
		if mask&(1<<5) != 0 {
			set = append(set, "quantity")
		}
		if mask&(1<<6) != 0 {
			set = append(set, "unit_price")
		}
		return onConflictID(set)
	},
}

func onConflictID(set []string) string {
	switch len(set) {
	case 0:
		return " ON CONFLICT (\"id\") DO NOTHING"
	}
	return " ON CONFLICT (\"id\") DO UPDATE SET " + joinAssign(set)
}

// OnConflictID upserts on the unique key (id).
func (n *Ins) OnConflictID() *Ins {
	n.conflict = 1
	return n
}

// joinAssign renders the DO UPDATE SET list for the columns the caller
// assigned. The punctuation comes from the back end, never from here.
func joinAssign(set []string) string {
	out := ""
	for i, c := range set {
		if i > 0 {
			out += ", "
		}
		out += assignExcluded(c)
	}
	return out
}

var assignFor = map[string]string{
	"updated_at": "\"updated_at\" = EXCLUDED.\"updated_at\"",
	"order_id":   "\"order_id\" = EXCLUDED.\"order_id\"",
	"product_id": "\"product_id\" = EXCLUDED.\"product_id\"",
	"quantity":   "\"quantity\" = EXCLUDED.\"quantity\"",
	"unit_price": "\"unit_price\" = EXCLUDED.\"unit_price\"",
}

func assignExcluded(c string) string { return assignFor[c] }

func stmtForInsert(mask uint64, conflict uint8) *runtime.Stmt {
	// The conflict target is part of the statement, so it must be part of
	// the key. Packing it above the column bits keeps one cache for both.
	key := mask | uint64(conflict)<<nInsertable
	if st := insCache.Get(key); st != nil {
		return st
	}
	cols := make([]string, 0, nInsertable)
	for i := 0; i < nInsertable; i++ {
		if mask&(1<<uint(i)) != 0 {
			cols = append(cols, insCols[i])
		}
	}
	suffix := insReturning
	if conflict > 0 {
		suffix = upsertTails[conflict-1](mask) + insReturning
	}
	return insCache.Put(key, runtime.SpliceInsert(insPrefix, insParts, cols, insPlaceholder, suffix))
}

// Insert writes the assigned columns and reads every column back, so
// database-computed values land in the returned Row rather than needing a
// second SELECT that would race every other writer.
func (n *Ins) Insert(ctx context.Context, ex runtime.Executor) (Row, error) {
	if n.set == 0 {
		return Row{}, runtime.ErrNothingAssigned
	}
	st := stmtForInsert(n.set, n.conflict)
	if st.Err != nil {
		// A malformed token stream is a code-generation bug. Executing it
		// would run a query whose filter is not the one that was asked for.
		return Row{}, st.Err
	}
	args := make([]any, 0, st.NArg)
	for i := 0; i < nInsertable; i++ {
		if n.set&(1<<uint(i)) == 0 {
			continue
		}
		switch i {
		case 0:
			args = append(args, n.row.ID)
		case 1:
			args = append(args, n.row.CreatedAt)
		case 2:
			args = append(args, n.row.UpdatedAt)
		case 3:
			args = append(args, n.row.OrderID)
		case 4:
			args = append(args, n.row.ProductID)
		case 5:
			args = append(args, n.row.Quantity)
		case 6:
			args = append(args, n.row.UnitPrice)
		}
	}
	var out Row
	rows, err := ex.Query(ctx, st.SQL, args)
	if err != nil {
		return out, err
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return out, err
		}
		return out, runtime.ErrNoRow
	}
	var sl runtime.Slab
	if err := scan(rows.RawValues(), &out, &sl); err != nil {
		return out, err
	}
	return out, rows.Err()
}

// Inserts reports how many distinct INSERT column sets have compiled.
func Inserts() int { return insCache.Masks() }

// Insert writes one row and reads back every column, so database-computed
// defaults — a generated id, a now() timestamp — land in r rather than
// needing a second SELECT that would race every other writer.
//
// Every insertable column is written, including zero values. storm does
// not treat a zero as 'unset': that guess is why other ORMs cannot insert
// a false, a 0 or an empty string into a column with a default.
func Insert(ctx context.Context, ex runtime.Executor, r *Row) error {
	args := make([]any, 0, 7)
	args = append(args, r.ID)
	args = append(args, r.CreatedAt)
	args = append(args, r.UpdatedAt)
	args = append(args, r.OrderID)
	args = append(args, r.ProductID)
	args = append(args, r.Quantity)
	args = append(args, r.UnitPrice)
	rows, err := ex.Query(ctx, insertSQL, args)
	if err != nil {
		return err
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return err
		}
		return runtime.ErrNoRow
	}
	// The returned strings live as long as this Slab, and the Slab lives
	// as long as r — a Row from an insert owns its own arena, unlike a Row
	// from a scan, which shares the result set's.
	var sl runtime.Slab
	if err := scan(rows.RawValues(), r, &sl); err != nil {
		return err
	}
	return rows.Err()
}

// copyCols is the fixed column list of a bulk load. Unlike Ins there is
// no mask: COPY sends one shape for the whole stream, so every row must
// supply every column and database defaults do not apply. Fill the row
// yourself, or use Create() per row and give up the bulk path.
var copyCols = []string{
	"id",
	"created_at",
	"updated_at",
	"order_id",
	"product_id",
	"quantity",
	"unit_price",
}

// rowSource walks a []Row for CopyFrom without copying any of it.
type rowSource struct {
	rows []Row
	i    int
	buf  [7]any
}

func (s *rowSource) Next() bool {
	s.i++
	return s.i <= len(s.rows)
}

// Values reuses one buffer across every row, and fills it with POINTERS
// into the caller's slice rather than copies.
//
// Both halves matter. The driver consumes each slice before asking for
// the next, so one buffer is safe. And boxing a pointer into an `any`
// does not allocate while boxing a value does — at a thousand rows that
// is one allocation per column per row, or none. Measured: the first cut
// boxed values and cost 7 allocations per row.
func (s *rowSource) Values() []any {
	r := &s.rows[s.i-1]
	s.buf[0] = &r.ID
	s.buf[1] = &r.CreatedAt
	s.buf[2] = &r.UpdatedAt
	s.buf[3] = &r.OrderID
	s.buf[4] = &r.ProductID
	s.buf[5] = &r.Quantity
	s.buf[6] = &r.UnitPrice
	return s.buf[:]
}

func (s *rowSource) Err() error { return nil }

// InsertAll bulk-loads rows through the driver's COPY protocol: ONE round
// trip regardless of row count, because COPY is a different wire path and
// not a faster loop over INSERT.
//
// It returns no rows. COPY has no RETURNING, so a caller who needs
// database-generated ids must supply them — which is why the primary key
// is in copyCols and must be set on every row.
func InsertAll(ctx context.Context, ex runtime.Executor, rows []Row) (int64, error) {
	if len(rows) == 0 {
		return 0, nil
	}
	src := &rowSource{rows: rows}
	return ex.CopyFrom(ctx, "order_lines", copyCols, src)
}

// InsertOp is an insert as a queueable statement. It writes every
// insertable column, because a batch of a thousand rows that each chose
// a different column set would compile a thousand statements and defeat
// the point of batching them.
//
// WantRows is false: a batched insert reports a count. Asking for
// RETURNING here would mean scanning a result per statement, which is
// exactly the per-row work a batch exists to avoid.
func InsertOp(r Row) runtime.BatchOp {
	var mask uint64
	mask |= 1 << 0
	mask |= 1 << 1
	mask |= 1 << 2
	mask |= 1 << 3
	mask |= 1 << 4
	mask |= 1 << 5
	mask |= 1 << 6
	st := stmtForInsert(mask, 0)
	args := make([]any, 0, 7)
	args = append(args, r.ID)
	args = append(args, r.CreatedAt)
	args = append(args, r.UpdatedAt)
	args = append(args, r.OrderID)
	args = append(args, r.ProductID)
	args = append(args, r.Quantity)
	args = append(args, r.UnitPrice)
	return runtime.BatchOp{SQL: st.SQL, Args: args}
}

// UpdateOp is this Mut's update as a queueable statement.
//
// The optimistic lock still applies, but the caller must check the
// affected count the batch reports: a stale write inside a batch is not
// an error the driver raises, it is a zero the caller has to notice.
func (m *Mut) UpdateOp() (runtime.BatchOp, bool) {
	if m.dirty == 0 {
		return runtime.BatchOp{}, false
	}
	st := stmtForMask(m.dirty)
	args := make([]any, 0, st.NArg)
	for i := 0; i < nUpdatable; i++ {
		if m.dirty&(1<<uint(i)) == 0 {
			continue
		}
		switch i {
		case 0:
			args = append(args, m.row.UpdatedAt)
		case 1:
			args = append(args, m.row.OrderID)
		case 2:
			args = append(args, m.row.ProductID)
		case 3:
			args = append(args, m.row.Quantity)
		case 4:
			args = append(args, m.row.UnitPrice)
		}
	}
	args = append(args, m.row.ID)
	return runtime.BatchOp{SQL: st.SQL, Args: args}, true
}

// DeleteOp is a delete as a queueable statement.
func DeleteOp(iD [16]byte) runtime.BatchOp {
	return runtime.BatchOp{SQL: deleteSQL, Args: []any{iD}}
}

// Table is the table these statements write, so a Unit can order a mixed
// batch by foreign key without knowing what any of them are.
const Table = "order_lines"

// stmtForMask compiles the UPDATE for one dirty mask, once.
func stmtForMask(mask uint64) *runtime.Stmt {
	if st := updCache.Get(mask); st != nil {
		return st
	}
	set := make([]runtime.Frag, 0, nUpdatable+1)
	for i := 0; i < nUpdatable; i++ {
		if mask&(1<<uint(i)) != 0 {
			set = append(set, setFrags[i])
		}
	}
	where := make([]runtime.Frag, 0, 2)
	where = append(where, pkFrags[:]...)
	return updCache.Put(mask, runtime.SpliceSections(updatePrefix, []runtime.Section{
		{Lead: "", Sep: ", ", Frags: set},
		{Lead: " WHERE ", Sep: " AND ", Frags: where},
	}, ""))
}

// Update writes the assigned columns of one row.
//
// Assigning nothing is not an error and issues no statement — an UPDATE
// with an empty SET list is not valid SQL, and a caller looping over
// possibly-changed fields should not have to special-case the empty case.
func (m *Mut) Update(ctx context.Context, ex runtime.Executor) error {
	if m.dirty == 0 {
		return nil
	}
	st := stmtForMask(m.dirty)
	if st.Err != nil {
		// A malformed token stream is a code-generation bug. Executing it
		// would run a query whose filter is not the one that was asked for.
		return st.Err
	}
	args := make([]any, 0, st.NArg)
	for i := 0; i < nUpdatable; i++ {
		if m.dirty&(1<<uint(i)) == 0 {
			continue
		}
		switch i {
		case 0:
			args = append(args, m.row.UpdatedAt)
		case 1:
			args = append(args, m.row.OrderID)
		case 2:
			args = append(args, m.row.ProductID)
		case 3:
			args = append(args, m.row.Quantity)
		case 4:
			args = append(args, m.row.UnitPrice)
		}
	}
	args = append(args, m.row.ID)
	n, err := ex.Exec(ctx, st.SQL, args)
	if err != nil {
		return err
	}
	if n == 0 {
		return runtime.ErrNoRow
	}
	m.dirty = 0
	return nil
}

var deleteSQL = runtime.SpliceSections(deletePrefix, []runtime.Section{
	{Lead: " WHERE ", Sep: " AND ", Frags: pkFrags[:]},
}, "").SQL

// Delete removes one row by primary key. A row that was already gone is
// runtime.ErrNoRow, not success: a caller deleting something that is not
// there usually has a bug, and swallowing it hides the bug.
func Delete(ctx context.Context, ex runtime.Executor, iD [16]byte) error {
	n, err := ex.Exec(ctx, deleteSQL, []any{iD})
	if err != nil {
		return err
	}
	if n == 0 {
		return runtime.ErrNoRow
	}
	return nil
}
