// Code generated by raorm. DO NOT EDIT.
// source: table users

package user

import (
	"context"
	"errors"
	"time"

	"github.com/gsoultan/raorm/runtime"
)

var _ = time.Time{}

// Row is what a full read returns: the model struct with relations
// replaced by their scalar foreign keys and *T rewritten to Null[T].
type Row struct {
	ID        [16]byte
	CreatedAt time.Time
	UpdatedAt time.Time
	Version   int32
	DeletedAt runtime.Null[time.Time]
	Email     string
	Name      string
	Status    string
	Prefs     runtime.JSON
	Scopes    []string
	Age       runtime.Null[int16]
	LastIP    runtime.Null[string]
	Balance   runtime.Decimal
	Credit    runtime.Null[runtime.Decimal]
	OrgID     [16]byte
}

// Operator ids. Argument-taking operators are numbered first, so the
// bind loop tests `op-1 < opsWithArg` with one unsigned compare.
const (
	opEq        runtime.Op = 1
	opNotEq     runtime.Op = 2
	opGt        runtime.Op = 3
	opGte       runtime.Op = 4
	opLt        runtime.Op = 5
	opLte       runtime.Op = 6
	opLike      runtime.Op = 7
	opIn        runtime.Op = 8
	opIsNull    runtime.Op = 9
	opIsNotNull runtime.Op = 10
)

const nCols = 15

// Query is a value type: composing one allocates nothing. Predicates
// are a postfix token stream, so disjunction and negation are
// representable — a per-column operator mask cannot express either.
type Query struct {
	toks [16]runtime.Tok
	nt   uint8
	top  uint8 // top-level conjuncts, ANDed at compile time

	strs                    [6]string
	nums                    [6]int64
	raws                    [4][16]byte
	tims                    [4]time.Time
	f64s                    [4]float64
	decs                    [4]runtime.Decimal
	ns, nn, nr, ntm, nf, nd uint8

	anyRaw [][16]byte
	anyStr []string
	hasAny bool

	// Order terms live in their own buffer and are appended to the stream
	// after the predicate tree. Sharing one buffer would let a Where after
	// an Order interleave the two, and the stream's order is its meaning.
	otoks [4]runtime.Tok
	no    uint8

	limit  int64
	offset int64
	// over records that the query outgrew its fixed buffers. Terminals
	// return it as an error rather than silently dropping a predicate.
	over bool

	// mixed records an After() over an ordering that is not all in one
	// direction. No single row comparison expresses that.
	mixed bool
}

// New starts a query.
func New() Query { return Query{limit: 1000} }

// Limit caps the result set.
func (q Query) Limit(n int64) Query { q.limit = n; return q }

// Offset skips rows.
//
// It is here because callers expect it, not because it is a good idea: the
// database still walks and discards every skipped row, so page 5,000 costs
// 5,000 pages of work, and a row inserted mid-scroll shifts every later
// page. Order by a unique key and filter past the last one you saw instead.
func (q Query) Offset(n int64) Query { q.offset = n; return q }

// After filters past a row already seen: keyset pagination.
//
// The comparison follows the ACTIVE ordering, because it has to. Paging
// `ORDER BY email DESC` with `> $1` walks away from the rows you have
// not seen yet, and silently returns a wrong page rather than an error.
// So After reads the ordering off the query and builds the matching row
// comparison: (a, b) > ($1, $2) for ascending, < for descending.
//
// Unlike Offset the database does not walk the skipped rows — the
// comparison seeks straight into the index — and a row inserted
// mid-scroll cannot shift a page, because the cursor is a position in the
// data rather than a count.
//
// Mixing ascending and descending terms in one ordering is a query error:
// no single row comparison expresses it, and expanding it into ORs would
// silently give up the index walk that makes this worth doing.
func (q Query) After(r Row) Query {
	terms := q.otoks[:q.no]
	if q.no == 0 {
		terms = defaultOrder[:]
	}
	if len(terms) == 0 {
		return q
	}
	desc := terms[0].Op() == runtime.Desc || terms[0].Op() == runtime.DescNullsLast
	for _, t := range terms {
		d := t.Op() == runtime.Desc || t.Op() == runtime.DescNullsLast
		if d != desc {
			q.mixed = true
			return q
		}
	}
	for _, t := range terms {
		q.push(runtime.MakeCol(t.Col()))
		q.cursor(t.Col(), r)
	}
	op := runtime.CmpGt
	if desc {
		op = runtime.CmpLt
	}
	q.push(runtime.MakeRowCmp(op, uint32(len(terms))))
	q.top++
	return q
}

// cursor stores the bound value for one column of a keyset comparison.
func (q *Query) cursor(col uint32, r Row) {
	switch col {
	case 0:
		if int(q.nr) >= len(q.raws) {
			q.over = true
			return
		}
		q.raws[q.nr] = r.ID
		q.nr++
	case 1:
		if int(q.ntm) >= len(q.tims) {
			q.over = true
			return
		}
		q.tims[q.ntm] = r.CreatedAt
		q.ntm++
	case 2:
		if int(q.ntm) >= len(q.tims) {
			q.over = true
			return
		}
		q.tims[q.ntm] = r.UpdatedAt
		q.ntm++
	case 3:
		if int(q.nn) >= len(q.nums) {
			q.over = true
			return
		}
		q.nums[q.nn] = int64(r.Version)
		q.nn++
	case 4:
		if int(q.ntm) >= len(q.tims) {
			q.over = true
			return
		}
		q.tims[q.ntm] = r.DeletedAt.V
		q.ntm++
	case 5:
		if int(q.ns) >= len(q.strs) {
			q.over = true
			return
		}
		q.strs[q.ns] = r.Email
		q.ns++
	case 6:
		if int(q.ns) >= len(q.strs) {
			q.over = true
			return
		}
		q.strs[q.ns] = r.Name
		q.ns++
	case 7:
		if int(q.ns) >= len(q.strs) {
			q.over = true
			return
		}
		q.strs[q.ns] = r.Status
		q.ns++
	case 10:
		if int(q.nn) >= len(q.nums) {
			q.over = true
			return
		}
		q.nums[q.nn] = int64(r.Age.V)
		q.nn++
	case 11:
		if int(q.ns) >= len(q.strs) {
			q.over = true
			return
		}
		q.strs[q.ns] = r.LastIP.V
		q.ns++
	case 12:
		if int(q.nd) >= len(q.decs) {
			q.over = true
			return
		}
		q.decs[q.nd] = r.Balance
		q.nd++
	case 13:
		if int(q.nd) >= len(q.decs) {
			q.over = true
			return
		}
		q.decs[q.nd] = r.Credit.V
		q.nd++
	case 14:
		if int(q.nr) >= len(q.raws) {
			q.over = true
			return
		}
		q.raws[q.nr] = r.OrgID
		q.nr++
	}
}

// Sort is one ORDER BY term, produced by a column handle: Email.Asc().
type Sort runtime.Tok

// Order replaces the ordering. Passing none restores the default.
//
// An ordering is part of a statement's identity, not a decoration on it:
// two queries differing only in ORDER BY are different statements, so the
// terms join the token stream that keys the compiled-statement cache.
func (q Query) Order(ts ...Sort) Query {
	q.no = 0
	for _, t := range ts {
		if int(q.no) >= len(q.otoks) {
			q.over = true
			return q
		}
		q.otoks[q.no] = runtime.Tok(t)
		q.no++
	}
	return q
}

// Err reports a query that outgrew its buffers.
func (q Query) Err() error {
	if q.over {
		return errTooComplex
	}
	if q.mixed {
		return errMixedOrder
	}
	return nil
}

var errMixedOrder = errors.New(
	"raorm: After() needs every ORDER BY term in the same direction; a mixed ordering has no single row comparison, and expanding it into ORs gives up the index walk that makes keyset pagination worth doing")

var errTooComplex = errors.New(
	"raorm: query has more predicates than the generated buffers hold; split it, or raise the limits in codegen")

// push and leaf mutate through a pointer so the builder loop does not
// copy the whole Query twice per predicate. They are only ever called on
// a local, so the public API keeps value semantics: q2 := q1.Where(x)
// must not mutate q1.
func (q *Query) push(t runtime.Tok) {
	if int(q.nt) >= len(q.toks) {
		q.over = true
		return
	}
	q.toks[q.nt] = t
	q.nt++
}

// preds returns the predicate stream with top-level conjuncts ANDed.
// A count uses this: ordering a scalar is wasted work, and including the
// terms would compile a second statement per ordering for no difference.
func (q Query) preds(buf *[21]runtime.Tok) []runtime.Tok {
	n := copy(buf[:], q.toks[:q.nt])
	if q.top > 1 {
		buf[n] = runtime.MakeGroup(runtime.KAnd, uint32(q.top))
		n++
	}
	return buf[:n]
}

// stream is the predicates followed by the ordering — the whole statement
// key. Order tokens go last so a splicer can find the boundary by kind.
func (q Query) stream(buf *[21]runtime.Tok) []runtime.Tok {
	n := len(q.preds(buf))
	if q.no == 0 {
		n += copy(buf[n:], defaultOrder[:])
		return buf[:n]
	}
	n += copy(buf[n:], q.otoks[:q.no])
	return buf[:n]
}

// Pred is one predicate, produced by a typed column handle. A value with
// a small union payload: no interface, nothing to allocate. Structure is
// assembled by Query into a token stream — see Where/Any/Not.
type Pred struct {
	col    uint8
	op     runtime.Op
	num    int64
	str    string
	raw    [16]byte
	tim    time.Time
	f64    float64
	dec    runtime.Decimal
	anyRaw [][16]byte
	anyStr []string
}

// b2i lets a bool ride in the numeric slot of a Pred.
func b2i(b bool) int64 {
	if b {
		return 1
	}
	return 0
}

// Typed column handles. The type of the handle is what makes
// Age.Like(...) fail to compile.
var (
	ID        = UUIDCol{0}
	CreatedAt = TimeCol{1}
	UpdatedAt = TimeCol{2}
	Version   = Int32Col{3}
	DeletedAt = NullTimeCol{4}
	Email     = TextCol{5}
	Name      = TextCol{6}
	Status    = TextCol{7}
	Prefs     = JSONCol{8}
	Scopes    = TextArrayCol{9}
	Age       = NullInt16Col{10}
	LastIP    = NullTextCol{11}
	Balance   = DecimalCol{12}
	Credit    = NullDecimalCol{13}
	OrgID     = UUIDCol{14}
)

// UUIDCol addresses a uuid column.
type UUIDCol struct{ c uint8 }

func (h UUIDCol) Asc() Sort  { return Sort(runtime.MakeOrder(runtime.Asc, uint32(h.c))) }
func (h UUIDCol) Desc() Sort { return Sort(runtime.MakeOrder(runtime.Desc, uint32(h.c))) }
func (h UUIDCol) AscNullsFirst() Sort {
	return Sort(runtime.MakeOrder(runtime.AscNullsFirst, uint32(h.c)))
}
func (h UUIDCol) DescNullsLast() Sort {
	return Sort(runtime.MakeOrder(runtime.DescNullsLast, uint32(h.c)))
}

func (h UUIDCol) Eq(v [16]byte) Pred    { return Pred{col: h.c, op: opEq, raw: v} }
func (h UUIDCol) NotEq(v [16]byte) Pred { return Pred{col: h.c, op: opNotEq, raw: v} }
func (h UUIDCol) In(v ...[16]byte) Pred { return Pred{col: h.c, op: opIn, anyRaw: v} }

// TimeCol addresses a timestamptz column.
type TimeCol struct{ c uint8 }

func (h TimeCol) Asc() Sort  { return Sort(runtime.MakeOrder(runtime.Asc, uint32(h.c))) }
func (h TimeCol) Desc() Sort { return Sort(runtime.MakeOrder(runtime.Desc, uint32(h.c))) }
func (h TimeCol) AscNullsFirst() Sort {
	return Sort(runtime.MakeOrder(runtime.AscNullsFirst, uint32(h.c)))
}
func (h TimeCol) DescNullsLast() Sort {
	return Sort(runtime.MakeOrder(runtime.DescNullsLast, uint32(h.c)))
}

func (h TimeCol) Eq(v time.Time) Pred    { return Pred{col: h.c, op: opEq, tim: v} }
func (h TimeCol) NotEq(v time.Time) Pred { return Pred{col: h.c, op: opNotEq, tim: v} }
func (h TimeCol) Gt(v time.Time) Pred    { return Pred{col: h.c, op: opGt, tim: v} }
func (h TimeCol) Gte(v time.Time) Pred   { return Pred{col: h.c, op: opGte, tim: v} }
func (h TimeCol) Lt(v time.Time) Pred    { return Pred{col: h.c, op: opLt, tim: v} }
func (h TimeCol) Lte(v time.Time) Pred   { return Pred{col: h.c, op: opLte, tim: v} }

// Int32Col addresses a int4 column.
type Int32Col struct{ c uint8 }

func (h Int32Col) Asc() Sort  { return Sort(runtime.MakeOrder(runtime.Asc, uint32(h.c))) }
func (h Int32Col) Desc() Sort { return Sort(runtime.MakeOrder(runtime.Desc, uint32(h.c))) }
func (h Int32Col) AscNullsFirst() Sort {
	return Sort(runtime.MakeOrder(runtime.AscNullsFirst, uint32(h.c)))
}
func (h Int32Col) DescNullsLast() Sort {
	return Sort(runtime.MakeOrder(runtime.DescNullsLast, uint32(h.c)))
}

func (h Int32Col) Eq(v int32) Pred    { return Pred{col: h.c, op: opEq, num: int64(v)} }
func (h Int32Col) NotEq(v int32) Pred { return Pred{col: h.c, op: opNotEq, num: int64(v)} }
func (h Int32Col) Gt(v int32) Pred    { return Pred{col: h.c, op: opGt, num: int64(v)} }
func (h Int32Col) Gte(v int32) Pred   { return Pred{col: h.c, op: opGte, num: int64(v)} }
func (h Int32Col) Lt(v int32) Pred    { return Pred{col: h.c, op: opLt, num: int64(v)} }
func (h Int32Col) Lte(v int32) Pred   { return Pred{col: h.c, op: opLte, num: int64(v)} }

// NullTimeCol addresses a timestamptz column.
type NullTimeCol struct{ c uint8 }

func (h NullTimeCol) Asc() Sort  { return Sort(runtime.MakeOrder(runtime.Asc, uint32(h.c))) }
func (h NullTimeCol) Desc() Sort { return Sort(runtime.MakeOrder(runtime.Desc, uint32(h.c))) }
func (h NullTimeCol) AscNullsFirst() Sort {
	return Sort(runtime.MakeOrder(runtime.AscNullsFirst, uint32(h.c)))
}
func (h NullTimeCol) DescNullsLast() Sort {
	return Sort(runtime.MakeOrder(runtime.DescNullsLast, uint32(h.c)))
}

func (h NullTimeCol) Eq(v time.Time) Pred    { return Pred{col: h.c, op: opEq, tim: v} }
func (h NullTimeCol) NotEq(v time.Time) Pred { return Pred{col: h.c, op: opNotEq, tim: v} }
func (h NullTimeCol) Gt(v time.Time) Pred    { return Pred{col: h.c, op: opGt, tim: v} }
func (h NullTimeCol) Gte(v time.Time) Pred   { return Pred{col: h.c, op: opGte, tim: v} }
func (h NullTimeCol) Lt(v time.Time) Pred    { return Pred{col: h.c, op: opLt, tim: v} }
func (h NullTimeCol) Lte(v time.Time) Pred   { return Pred{col: h.c, op: opLte, tim: v} }
func (h NullTimeCol) IsNull() Pred           { return Pred{col: h.c, op: opIsNull} }
func (h NullTimeCol) IsNotNull() Pred        { return Pred{col: h.c, op: opIsNotNull} }

// TextCol addresses a varchar(320) column.
type TextCol struct{ c uint8 }

func (h TextCol) Asc() Sort  { return Sort(runtime.MakeOrder(runtime.Asc, uint32(h.c))) }
func (h TextCol) Desc() Sort { return Sort(runtime.MakeOrder(runtime.Desc, uint32(h.c))) }
func (h TextCol) AscNullsFirst() Sort {
	return Sort(runtime.MakeOrder(runtime.AscNullsFirst, uint32(h.c)))
}
func (h TextCol) DescNullsLast() Sort {
	return Sort(runtime.MakeOrder(runtime.DescNullsLast, uint32(h.c)))
}

func (h TextCol) Eq(v string) Pred    { return Pred{col: h.c, op: opEq, str: v} }
func (h TextCol) NotEq(v string) Pred { return Pred{col: h.c, op: opNotEq, str: v} }
func (h TextCol) Gt(v string) Pred    { return Pred{col: h.c, op: opGt, str: v} }
func (h TextCol) Gte(v string) Pred   { return Pred{col: h.c, op: opGte, str: v} }
func (h TextCol) Lt(v string) Pred    { return Pred{col: h.c, op: opLt, str: v} }
func (h TextCol) Lte(v string) Pred   { return Pred{col: h.c, op: opLte, str: v} }
func (h TextCol) Like(v string) Pred  { return Pred{col: h.c, op: opLike, str: v} }
func (h TextCol) In(v ...string) Pred { return Pred{col: h.c, op: opIn, anyStr: v} }

// JSONCol addresses a jsonb column.
type JSONCol struct{ c uint8 }

func (h JSONCol) Asc() Sort  { return Sort(runtime.MakeOrder(runtime.Asc, uint32(h.c))) }
func (h JSONCol) Desc() Sort { return Sort(runtime.MakeOrder(runtime.Desc, uint32(h.c))) }
func (h JSONCol) AscNullsFirst() Sort {
	return Sort(runtime.MakeOrder(runtime.AscNullsFirst, uint32(h.c)))
}
func (h JSONCol) DescNullsLast() Sort {
	return Sort(runtime.MakeOrder(runtime.DescNullsLast, uint32(h.c)))
}

// TextArrayCol addresses a text[] column.
type TextArrayCol struct{ c uint8 }

func (h TextArrayCol) Asc() Sort  { return Sort(runtime.MakeOrder(runtime.Asc, uint32(h.c))) }
func (h TextArrayCol) Desc() Sort { return Sort(runtime.MakeOrder(runtime.Desc, uint32(h.c))) }
func (h TextArrayCol) AscNullsFirst() Sort {
	return Sort(runtime.MakeOrder(runtime.AscNullsFirst, uint32(h.c)))
}
func (h TextArrayCol) DescNullsLast() Sort {
	return Sort(runtime.MakeOrder(runtime.DescNullsLast, uint32(h.c)))
}

// NullInt16Col addresses a int2 column.
type NullInt16Col struct{ c uint8 }

func (h NullInt16Col) Asc() Sort  { return Sort(runtime.MakeOrder(runtime.Asc, uint32(h.c))) }
func (h NullInt16Col) Desc() Sort { return Sort(runtime.MakeOrder(runtime.Desc, uint32(h.c))) }
func (h NullInt16Col) AscNullsFirst() Sort {
	return Sort(runtime.MakeOrder(runtime.AscNullsFirst, uint32(h.c)))
}
func (h NullInt16Col) DescNullsLast() Sort {
	return Sort(runtime.MakeOrder(runtime.DescNullsLast, uint32(h.c)))
}

func (h NullInt16Col) Eq(v int16) Pred    { return Pred{col: h.c, op: opEq, num: int64(v)} }
func (h NullInt16Col) NotEq(v int16) Pred { return Pred{col: h.c, op: opNotEq, num: int64(v)} }
func (h NullInt16Col) Gt(v int16) Pred    { return Pred{col: h.c, op: opGt, num: int64(v)} }
func (h NullInt16Col) Gte(v int16) Pred   { return Pred{col: h.c, op: opGte, num: int64(v)} }
func (h NullInt16Col) Lt(v int16) Pred    { return Pred{col: h.c, op: opLt, num: int64(v)} }
func (h NullInt16Col) Lte(v int16) Pred   { return Pred{col: h.c, op: opLte, num: int64(v)} }
func (h NullInt16Col) IsNull() Pred       { return Pred{col: h.c, op: opIsNull} }
func (h NullInt16Col) IsNotNull() Pred    { return Pred{col: h.c, op: opIsNotNull} }

// NullTextCol addresses a text column.
type NullTextCol struct{ c uint8 }

func (h NullTextCol) Asc() Sort  { return Sort(runtime.MakeOrder(runtime.Asc, uint32(h.c))) }
func (h NullTextCol) Desc() Sort { return Sort(runtime.MakeOrder(runtime.Desc, uint32(h.c))) }
func (h NullTextCol) AscNullsFirst() Sort {
	return Sort(runtime.MakeOrder(runtime.AscNullsFirst, uint32(h.c)))
}
func (h NullTextCol) DescNullsLast() Sort {
	return Sort(runtime.MakeOrder(runtime.DescNullsLast, uint32(h.c)))
}

func (h NullTextCol) Eq(v string) Pred    { return Pred{col: h.c, op: opEq, str: v} }
func (h NullTextCol) NotEq(v string) Pred { return Pred{col: h.c, op: opNotEq, str: v} }
func (h NullTextCol) Gt(v string) Pred    { return Pred{col: h.c, op: opGt, str: v} }
func (h NullTextCol) Gte(v string) Pred   { return Pred{col: h.c, op: opGte, str: v} }
func (h NullTextCol) Lt(v string) Pred    { return Pred{col: h.c, op: opLt, str: v} }
func (h NullTextCol) Lte(v string) Pred   { return Pred{col: h.c, op: opLte, str: v} }
func (h NullTextCol) Like(v string) Pred  { return Pred{col: h.c, op: opLike, str: v} }
func (h NullTextCol) In(v ...string) Pred { return Pred{col: h.c, op: opIn, anyStr: v} }
func (h NullTextCol) IsNull() Pred        { return Pred{col: h.c, op: opIsNull} }
func (h NullTextCol) IsNotNull() Pred     { return Pred{col: h.c, op: opIsNotNull} }

// DecimalCol addresses a numeric(18,4) column.
type DecimalCol struct{ c uint8 }

func (h DecimalCol) Asc() Sort  { return Sort(runtime.MakeOrder(runtime.Asc, uint32(h.c))) }
func (h DecimalCol) Desc() Sort { return Sort(runtime.MakeOrder(runtime.Desc, uint32(h.c))) }
func (h DecimalCol) AscNullsFirst() Sort {
	return Sort(runtime.MakeOrder(runtime.AscNullsFirst, uint32(h.c)))
}
func (h DecimalCol) DescNullsLast() Sort {
	return Sort(runtime.MakeOrder(runtime.DescNullsLast, uint32(h.c)))
}

func (h DecimalCol) Eq(v runtime.Decimal) Pred    { return Pred{col: h.c, op: opEq, dec: v} }
func (h DecimalCol) NotEq(v runtime.Decimal) Pred { return Pred{col: h.c, op: opNotEq, dec: v} }
func (h DecimalCol) Gt(v runtime.Decimal) Pred    { return Pred{col: h.c, op: opGt, dec: v} }
func (h DecimalCol) Gte(v runtime.Decimal) Pred   { return Pred{col: h.c, op: opGte, dec: v} }
func (h DecimalCol) Lt(v runtime.Decimal) Pred    { return Pred{col: h.c, op: opLt, dec: v} }
func (h DecimalCol) Lte(v runtime.Decimal) Pred   { return Pred{col: h.c, op: opLte, dec: v} }

// NullDecimalCol addresses a numeric column.
type NullDecimalCol struct{ c uint8 }

func (h NullDecimalCol) Asc() Sort  { return Sort(runtime.MakeOrder(runtime.Asc, uint32(h.c))) }
func (h NullDecimalCol) Desc() Sort { return Sort(runtime.MakeOrder(runtime.Desc, uint32(h.c))) }
func (h NullDecimalCol) AscNullsFirst() Sort {
	return Sort(runtime.MakeOrder(runtime.AscNullsFirst, uint32(h.c)))
}
func (h NullDecimalCol) DescNullsLast() Sort {
	return Sort(runtime.MakeOrder(runtime.DescNullsLast, uint32(h.c)))
}

func (h NullDecimalCol) Eq(v runtime.Decimal) Pred    { return Pred{col: h.c, op: opEq, dec: v} }
func (h NullDecimalCol) NotEq(v runtime.Decimal) Pred { return Pred{col: h.c, op: opNotEq, dec: v} }
func (h NullDecimalCol) Gt(v runtime.Decimal) Pred    { return Pred{col: h.c, op: opGt, dec: v} }
func (h NullDecimalCol) Gte(v runtime.Decimal) Pred   { return Pred{col: h.c, op: opGte, dec: v} }
func (h NullDecimalCol) Lt(v runtime.Decimal) Pred    { return Pred{col: h.c, op: opLt, dec: v} }
func (h NullDecimalCol) Lte(v runtime.Decimal) Pred   { return Pred{col: h.c, op: opLte, dec: v} }
func (h NullDecimalCol) IsNull() Pred                 { return Pred{col: h.c, op: opIsNull} }
func (h NullDecimalCol) IsNotNull() Pred              { return Pred{col: h.c, op: opIsNotNull} }

// Where applies predicates, ANDed together.
func (q Query) Where(ps ...Pred) Query {
	for i := range ps {
		q.leaf(ps[i])
		q.top++
	}
	return q
}

// WhereIf applies a predicate only when cond holds.
func (q Query) WhereIf(cond bool, p Pred) Query {
	if !cond {
		return q
	}
	return q.Where(p)
}

// Any ORs its arguments and ANDs the group with the rest of the query:
// Where(a).Any(b, c) is a AND (b OR c).
func (q Query) Any(ps ...Pred) Query {
	if len(ps) == 0 {
		return q
	}
	for i := range ps {
		q.leaf(ps[i])
	}
	q.push(runtime.MakeGroup(runtime.KOr, uint32(len(ps))))
	q.top++
	return q
}

// Not negates one predicate and ANDs it with the rest.
func (q Query) Not(p Pred) Query {
	q.leaf(p)
	q.push(runtime.MakeGroup(runtime.KNot, 1))
	q.top++
	return q
}

// NotAny negates a disjunction: NOT (a OR b).
func (q Query) NotAny(ps ...Pred) Query {
	if len(ps) == 0 {
		return q
	}
	for i := range ps {
		q.leaf(ps[i])
	}
	q.push(runtime.MakeGroup(runtime.KOr, uint32(len(ps))))
	q.push(runtime.MakeGroup(runtime.KNot, 1))
	q.top++
	return q
}

// leaf records one predicate: its value goes to the arena for its type,
// its structure to the token stream.
func (q *Query) leaf(p Pred) {
	if p.op == opIn {
		switch {
		case p.anyRaw != nil:
			q.anyRaw, q.hasAny = p.anyRaw, true
		case p.anyStr != nil:
			q.anyStr, q.hasAny = p.anyStr, true
		}
		q.push(runtime.MakeLeaf(uint32(p.op), uint32(p.col)))
		return
	}
	switch p.col {
	case 0:
		if int(q.nr) >= 4 {
			q.over = true
			return
		}
		q.raws[q.nr] = p.raw
		q.nr++
	case 1:
		if int(q.ntm) >= 4 {
			q.over = true
			return
		}
		q.tims[q.ntm] = p.tim
		q.ntm++
	case 2:
		if int(q.ntm) >= 4 {
			q.over = true
			return
		}
		q.tims[q.ntm] = p.tim
		q.ntm++
	case 3:
		if int(q.nn) >= 6 {
			q.over = true
			return
		}
		q.nums[q.nn] = p.num
		q.nn++
	case 4:
		if int(q.ntm) >= 4 {
			q.over = true
			return
		}
		q.tims[q.ntm] = p.tim
		q.ntm++
	case 5:
		if int(q.ns) >= 6 {
			q.over = true
			return
		}
		q.strs[q.ns] = p.str
		q.ns++
	case 6:
		if int(q.ns) >= 6 {
			q.over = true
			return
		}
		q.strs[q.ns] = p.str
		q.ns++
	case 7:
		if int(q.ns) >= 6 {
			q.over = true
			return
		}
		q.strs[q.ns] = p.str
		q.ns++
	case 10:
		if int(q.nn) >= 6 {
			q.over = true
			return
		}
		q.nums[q.nn] = p.num
		q.nn++
	case 11:
		if int(q.ns) >= 6 {
			q.over = true
			return
		}
		q.strs[q.ns] = p.str
		q.ns++
	case 12:
		if int(q.nd) >= 4 {
			q.over = true
			return
		}
		q.decs[q.nd] = p.dec
		q.nd++
	case 13:
		if int(q.nd) >= 4 {
			q.over = true
			return
		}
		q.decs[q.nd] = p.dec
		q.nd++
	case 14:
		if int(q.nr) >= 4 {
			q.over = true
			return
		}
		q.raws[q.nr] = p.raw
		q.nr++
	}
	q.push(runtime.MakeLeaf(uint32(p.op), uint32(p.col)))
}

// Chained predicate sugar. Identical to Where(Col.Op(v)).
func (q Query) IDEq(v [16]byte) Query                { return q.Where(ID.Eq(v)) }
func (q Query) IDNotEq(v [16]byte) Query             { return q.Where(ID.NotEq(v)) }
func (q Query) IDIn(v ...[16]byte) Query             { return q.Where(ID.In(v...)) }
func (q Query) CreatedAtEq(v time.Time) Query        { return q.Where(CreatedAt.Eq(v)) }
func (q Query) CreatedAtNotEq(v time.Time) Query     { return q.Where(CreatedAt.NotEq(v)) }
func (q Query) CreatedAtGt(v time.Time) Query        { return q.Where(CreatedAt.Gt(v)) }
func (q Query) CreatedAtGte(v time.Time) Query       { return q.Where(CreatedAt.Gte(v)) }
func (q Query) CreatedAtLt(v time.Time) Query        { return q.Where(CreatedAt.Lt(v)) }
func (q Query) CreatedAtLte(v time.Time) Query       { return q.Where(CreatedAt.Lte(v)) }
func (q Query) UpdatedAtEq(v time.Time) Query        { return q.Where(UpdatedAt.Eq(v)) }
func (q Query) UpdatedAtNotEq(v time.Time) Query     { return q.Where(UpdatedAt.NotEq(v)) }
func (q Query) UpdatedAtGt(v time.Time) Query        { return q.Where(UpdatedAt.Gt(v)) }
func (q Query) UpdatedAtGte(v time.Time) Query       { return q.Where(UpdatedAt.Gte(v)) }
func (q Query) UpdatedAtLt(v time.Time) Query        { return q.Where(UpdatedAt.Lt(v)) }
func (q Query) UpdatedAtLte(v time.Time) Query       { return q.Where(UpdatedAt.Lte(v)) }
func (q Query) VersionEq(v int32) Query              { return q.Where(Version.Eq(v)) }
func (q Query) VersionNotEq(v int32) Query           { return q.Where(Version.NotEq(v)) }
func (q Query) VersionGt(v int32) Query              { return q.Where(Version.Gt(v)) }
func (q Query) VersionGte(v int32) Query             { return q.Where(Version.Gte(v)) }
func (q Query) VersionLt(v int32) Query              { return q.Where(Version.Lt(v)) }
func (q Query) VersionLte(v int32) Query             { return q.Where(Version.Lte(v)) }
func (q Query) DeletedAtEq(v time.Time) Query        { return q.Where(DeletedAt.Eq(v)) }
func (q Query) DeletedAtNotEq(v time.Time) Query     { return q.Where(DeletedAt.NotEq(v)) }
func (q Query) DeletedAtGt(v time.Time) Query        { return q.Where(DeletedAt.Gt(v)) }
func (q Query) DeletedAtGte(v time.Time) Query       { return q.Where(DeletedAt.Gte(v)) }
func (q Query) DeletedAtLt(v time.Time) Query        { return q.Where(DeletedAt.Lt(v)) }
func (q Query) DeletedAtLte(v time.Time) Query       { return q.Where(DeletedAt.Lte(v)) }
func (q Query) DeletedAtIsNull() Query               { return q.Where(DeletedAt.IsNull()) }
func (q Query) DeletedAtIsNotNull() Query            { return q.Where(DeletedAt.IsNotNull()) }
func (q Query) EmailEq(v string) Query               { return q.Where(Email.Eq(v)) }
func (q Query) EmailNotEq(v string) Query            { return q.Where(Email.NotEq(v)) }
func (q Query) EmailGt(v string) Query               { return q.Where(Email.Gt(v)) }
func (q Query) EmailGte(v string) Query              { return q.Where(Email.Gte(v)) }
func (q Query) EmailLt(v string) Query               { return q.Where(Email.Lt(v)) }
func (q Query) EmailLte(v string) Query              { return q.Where(Email.Lte(v)) }
func (q Query) EmailLike(v string) Query             { return q.Where(Email.Like(v)) }
func (q Query) EmailIn(v ...string) Query            { return q.Where(Email.In(v...)) }
func (q Query) NameEq(v string) Query                { return q.Where(Name.Eq(v)) }
func (q Query) NameNotEq(v string) Query             { return q.Where(Name.NotEq(v)) }
func (q Query) NameGt(v string) Query                { return q.Where(Name.Gt(v)) }
func (q Query) NameGte(v string) Query               { return q.Where(Name.Gte(v)) }
func (q Query) NameLt(v string) Query                { return q.Where(Name.Lt(v)) }
func (q Query) NameLte(v string) Query               { return q.Where(Name.Lte(v)) }
func (q Query) NameLike(v string) Query              { return q.Where(Name.Like(v)) }
func (q Query) NameIn(v ...string) Query             { return q.Where(Name.In(v...)) }
func (q Query) StatusEq(v string) Query              { return q.Where(Status.Eq(v)) }
func (q Query) StatusNotEq(v string) Query           { return q.Where(Status.NotEq(v)) }
func (q Query) StatusGt(v string) Query              { return q.Where(Status.Gt(v)) }
func (q Query) StatusGte(v string) Query             { return q.Where(Status.Gte(v)) }
func (q Query) StatusLt(v string) Query              { return q.Where(Status.Lt(v)) }
func (q Query) StatusLte(v string) Query             { return q.Where(Status.Lte(v)) }
func (q Query) StatusLike(v string) Query            { return q.Where(Status.Like(v)) }
func (q Query) StatusIn(v ...string) Query           { return q.Where(Status.In(v...)) }
func (q Query) AgeEq(v int16) Query                  { return q.Where(Age.Eq(v)) }
func (q Query) AgeNotEq(v int16) Query               { return q.Where(Age.NotEq(v)) }
func (q Query) AgeGt(v int16) Query                  { return q.Where(Age.Gt(v)) }
func (q Query) AgeGte(v int16) Query                 { return q.Where(Age.Gte(v)) }
func (q Query) AgeLt(v int16) Query                  { return q.Where(Age.Lt(v)) }
func (q Query) AgeLte(v int16) Query                 { return q.Where(Age.Lte(v)) }
func (q Query) AgeIsNull() Query                     { return q.Where(Age.IsNull()) }
func (q Query) AgeIsNotNull() Query                  { return q.Where(Age.IsNotNull()) }
func (q Query) LastIPEq(v string) Query              { return q.Where(LastIP.Eq(v)) }
func (q Query) LastIPNotEq(v string) Query           { return q.Where(LastIP.NotEq(v)) }
func (q Query) LastIPGt(v string) Query              { return q.Where(LastIP.Gt(v)) }
func (q Query) LastIPGte(v string) Query             { return q.Where(LastIP.Gte(v)) }
func (q Query) LastIPLt(v string) Query              { return q.Where(LastIP.Lt(v)) }
func (q Query) LastIPLte(v string) Query             { return q.Where(LastIP.Lte(v)) }
func (q Query) LastIPLike(v string) Query            { return q.Where(LastIP.Like(v)) }
func (q Query) LastIPIn(v ...string) Query           { return q.Where(LastIP.In(v...)) }
func (q Query) LastIPIsNull() Query                  { return q.Where(LastIP.IsNull()) }
func (q Query) LastIPIsNotNull() Query               { return q.Where(LastIP.IsNotNull()) }
func (q Query) BalanceEq(v runtime.Decimal) Query    { return q.Where(Balance.Eq(v)) }
func (q Query) BalanceNotEq(v runtime.Decimal) Query { return q.Where(Balance.NotEq(v)) }
func (q Query) BalanceGt(v runtime.Decimal) Query    { return q.Where(Balance.Gt(v)) }
func (q Query) BalanceGte(v runtime.Decimal) Query   { return q.Where(Balance.Gte(v)) }
func (q Query) BalanceLt(v runtime.Decimal) Query    { return q.Where(Balance.Lt(v)) }
func (q Query) BalanceLte(v runtime.Decimal) Query   { return q.Where(Balance.Lte(v)) }
func (q Query) CreditEq(v runtime.Decimal) Query     { return q.Where(Credit.Eq(v)) }
func (q Query) CreditNotEq(v runtime.Decimal) Query  { return q.Where(Credit.NotEq(v)) }
func (q Query) CreditGt(v runtime.Decimal) Query     { return q.Where(Credit.Gt(v)) }
func (q Query) CreditGte(v runtime.Decimal) Query    { return q.Where(Credit.Gte(v)) }
func (q Query) CreditLt(v runtime.Decimal) Query     { return q.Where(Credit.Lt(v)) }
func (q Query) CreditLte(v runtime.Decimal) Query    { return q.Where(Credit.Lte(v)) }
func (q Query) CreditIsNull() Query                  { return q.Where(Credit.IsNull()) }
func (q Query) CreditIsNotNull() Query               { return q.Where(Credit.IsNotNull()) }
func (q Query) OrgIDEq(v [16]byte) Query             { return q.Where(OrgID.Eq(v)) }
func (q Query) OrgIDNotEq(v [16]byte) Query          { return q.Where(OrgID.NotEq(v)) }
func (q Query) OrgIDIn(v ...[16]byte) Query          { return q.Where(OrgID.In(v...)) }

const selectPrefix = `SELECT "id", "created_at", "updated_at", "version", "deleted_at", "email", "name", "status", "prefs", "scopes", "age", "last_ip", "balance", "credit", "org_id" FROM "users"`
const countPrefix = `SELECT count(*) FROM "users"`
const limitSuffix = ` LIMIT $`
const limitOffsetSuffix = ` LIMIT $ OFFSET $`

// orderTable is every ordering this table can express, lowered at build
// time. ORDER BY is chosen per query, so it cannot be a constant — but it
// still must not be built from strings at run time.
var orderTable = [nCols][4]string{
	{ // id
		"\"id\"",
		"\"id\" DESC",
		"\"id\" ASC NULLS FIRST",
		"\"id\" DESC NULLS LAST",
	},
	{ // created_at
		"\"created_at\"",
		"\"created_at\" DESC",
		"\"created_at\" ASC NULLS FIRST",
		"\"created_at\" DESC NULLS LAST",
	},
	{ // updated_at
		"\"updated_at\"",
		"\"updated_at\" DESC",
		"\"updated_at\" ASC NULLS FIRST",
		"\"updated_at\" DESC NULLS LAST",
	},
	{ // version
		"\"version\"",
		"\"version\" DESC",
		"\"version\" ASC NULLS FIRST",
		"\"version\" DESC NULLS LAST",
	},
	{ // deleted_at
		"\"deleted_at\"",
		"\"deleted_at\" DESC",
		"\"deleted_at\" ASC NULLS FIRST",
		"\"deleted_at\" DESC NULLS LAST",
	},
	{ // email
		"\"email\"",
		"\"email\" DESC",
		"\"email\" ASC NULLS FIRST",
		"\"email\" DESC NULLS LAST",
	},
	{ // name
		"\"name\"",
		"\"name\" DESC",
		"\"name\" ASC NULLS FIRST",
		"\"name\" DESC NULLS LAST",
	},
	{ // status
		"\"status\"",
		"\"status\" DESC",
		"\"status\" ASC NULLS FIRST",
		"\"status\" DESC NULLS LAST",
	},
	{ // prefs
		"\"prefs\"",
		"\"prefs\" DESC",
		"\"prefs\" ASC NULLS FIRST",
		"\"prefs\" DESC NULLS LAST",
	},
	{ // scopes
		"\"scopes\"",
		"\"scopes\" DESC",
		"\"scopes\" ASC NULLS FIRST",
		"\"scopes\" DESC NULLS LAST",
	},
	{ // age
		"\"age\"",
		"\"age\" DESC",
		"\"age\" ASC NULLS FIRST",
		"\"age\" DESC NULLS LAST",
	},
	{ // last_ip
		"\"last_ip\"",
		"\"last_ip\" DESC",
		"\"last_ip\" ASC NULLS FIRST",
		"\"last_ip\" DESC NULLS LAST",
	},
	{ // balance
		"\"balance\"",
		"\"balance\" DESC",
		"\"balance\" ASC NULLS FIRST",
		"\"balance\" DESC NULLS LAST",
	},
	{ // credit
		"\"credit\"",
		"\"credit\" DESC",
		"\"credit\" ASC NULLS FIRST",
		"\"credit\" DESC NULLS LAST",
	},
	{ // org_id
		"\"org_id\"",
		"\"org_id\" DESC",
		"\"org_id\" ASC NULLS FIRST",
		"\"org_id\" DESC NULLS LAST",
	},
}

// identTable is each column's bare quoted name, for the left side of a
// row comparison.
var identTable = [nCols]string{
	"\"id\"",
	"\"created_at\"",
	"\"updated_at\"",
	"\"version\"",
	"\"deleted_at\"",
	"\"email\"",
	"\"name\"",
	"\"status\"",
	"\"prefs\"",
	"\"scopes\"",
	"\"age\"",
	"\"last_ip\"",
	"\"balance\"",
	"\"credit\"",
	"\"org_id\"",
}

var lowering = runtime.Lowering{
	Frag:  fragOf,
	Order: orderOf,
	OB:    runtime.Order{Lead: " ORDER BY ", Sep: ", "},
	Ident: func(col uint32) string {
		if col >= nCols {
			return ""
		}
		return identTable[col]
	},
	RowCmp: func(op uint32) string {
		if op == runtime.CmpLt {
			return " < "
		}
		return " > "
	},
	TupleOpen:  "(",
	TupleSep:   ", ",
	TupleClose: ")",
}

func orderOf(dir, col uint32) string {
	if col >= nCols || int(dir) >= len(orderTable[0]) {
		return ""
	}
	return orderTable[col][dir]
}

// fragTable is every predicate this table can produce, lowered at build
// time. Runtime splices; it never formats.
var fragTable = [nCols][11]runtime.Frag{
	{ // id
		{}, // opNone
		{A: "\"id\" = $", B: ""},
		{A: "\"id\" <> $", B: ""},
		{},
		{},
		{},
		{},
		{},
		{A: "\"id\" = ANY($", B: ")"},
		{},
		{},
	},
	{ // created_at
		{}, // opNone
		{A: "\"created_at\" = $", B: ""},
		{A: "\"created_at\" <> $", B: ""},
		{A: "\"created_at\" > $", B: ""},
		{A: "\"created_at\" >= $", B: ""},
		{A: "\"created_at\" < $", B: ""},
		{A: "\"created_at\" <= $", B: ""},
		{},
		{},
		{},
		{},
	},
	{ // updated_at
		{}, // opNone
		{A: "\"updated_at\" = $", B: ""},
		{A: "\"updated_at\" <> $", B: ""},
		{A: "\"updated_at\" > $", B: ""},
		{A: "\"updated_at\" >= $", B: ""},
		{A: "\"updated_at\" < $", B: ""},
		{A: "\"updated_at\" <= $", B: ""},
		{},
		{},
		{},
		{},
	},
	{ // version
		{}, // opNone
		{A: "\"version\" = $", B: ""},
		{A: "\"version\" <> $", B: ""},
		{A: "\"version\" > $", B: ""},
		{A: "\"version\" >= $", B: ""},
		{A: "\"version\" < $", B: ""},
		{A: "\"version\" <= $", B: ""},
		{},
		{A: "\"version\" = ANY($", B: ")"},
		{},
		{},
	},
	{ // deleted_at
		{}, // opNone
		{A: "\"deleted_at\" = $", B: ""},
		{A: "\"deleted_at\" <> $", B: ""},
		{A: "\"deleted_at\" > $", B: ""},
		{A: "\"deleted_at\" >= $", B: ""},
		{A: "\"deleted_at\" < $", B: ""},
		{A: "\"deleted_at\" <= $", B: ""},
		{},
		{},
		{A: "\"deleted_at\" IS NULL", B: ""},
		{A: "\"deleted_at\" IS NOT NULL", B: ""},
	},
	{ // email
		{}, // opNone
		{A: "\"email\" = $", B: ""},
		{A: "\"email\" <> $", B: ""},
		{A: "\"email\" > $", B: ""},
		{A: "\"email\" >= $", B: ""},
		{A: "\"email\" < $", B: ""},
		{A: "\"email\" <= $", B: ""},
		{A: "\"email\" LIKE $", B: ""},
		{A: "\"email\" = ANY($", B: ")"},
		{},
		{},
	},
	{ // name
		{}, // opNone
		{A: "\"name\" = $", B: ""},
		{A: "\"name\" <> $", B: ""},
		{A: "\"name\" > $", B: ""},
		{A: "\"name\" >= $", B: ""},
		{A: "\"name\" < $", B: ""},
		{A: "\"name\" <= $", B: ""},
		{A: "\"name\" LIKE $", B: ""},
		{A: "\"name\" = ANY($", B: ")"},
		{},
		{},
	},
	{ // status
		{}, // opNone
		{A: "\"status\" = $", B: ""},
		{A: "\"status\" <> $", B: ""},
		{A: "\"status\" > $", B: ""},
		{A: "\"status\" >= $", B: ""},
		{A: "\"status\" < $", B: ""},
		{A: "\"status\" <= $", B: ""},
		{A: "\"status\" LIKE $", B: ""},
		{A: "\"status\" = ANY($", B: ")"},
		{},
		{},
	},
	{ // prefs
		{}, // opNone
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
	},
	{ // scopes
		{}, // opNone
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
	},
	{ // age
		{}, // opNone
		{A: "\"age\" = $", B: ""},
		{A: "\"age\" <> $", B: ""},
		{A: "\"age\" > $", B: ""},
		{A: "\"age\" >= $", B: ""},
		{A: "\"age\" < $", B: ""},
		{A: "\"age\" <= $", B: ""},
		{},
		{A: "\"age\" = ANY($", B: ")"},
		{A: "\"age\" IS NULL", B: ""},
		{A: "\"age\" IS NOT NULL", B: ""},
	},
	{ // last_ip
		{}, // opNone
		{A: "\"last_ip\" = $", B: ""},
		{A: "\"last_ip\" <> $", B: ""},
		{A: "\"last_ip\" > $", B: ""},
		{A: "\"last_ip\" >= $", B: ""},
		{A: "\"last_ip\" < $", B: ""},
		{A: "\"last_ip\" <= $", B: ""},
		{A: "\"last_ip\" LIKE $", B: ""},
		{A: "\"last_ip\" = ANY($", B: ")"},
		{A: "\"last_ip\" IS NULL", B: ""},
		{A: "\"last_ip\" IS NOT NULL", B: ""},
	},
	{ // balance
		{}, // opNone
		{A: "\"balance\" = $", B: ""},
		{A: "\"balance\" <> $", B: ""},
		{A: "\"balance\" > $", B: ""},
		{A: "\"balance\" >= $", B: ""},
		{A: "\"balance\" < $", B: ""},
		{A: "\"balance\" <= $", B: ""},
		{},
		{},
		{},
		{},
	},
	{ // credit
		{}, // opNone
		{A: "\"credit\" = $", B: ""},
		{A: "\"credit\" <> $", B: ""},
		{A: "\"credit\" > $", B: ""},
		{A: "\"credit\" >= $", B: ""},
		{A: "\"credit\" < $", B: ""},
		{A: "\"credit\" <= $", B: ""},
		{},
		{},
		{A: "\"credit\" IS NULL", B: ""},
		{A: "\"credit\" IS NOT NULL", B: ""},
	},
	{ // org_id
		{}, // opNone
		{A: "\"org_id\" = $", B: ""},
		{A: "\"org_id\" <> $", B: ""},
		{},
		{},
		{},
		{},
		{},
		{A: "\"org_id\" = ANY($", B: ")"},
		{},
		{},
	},
}

func fragOf(op, col uint32) runtime.Frag {
	if col >= nCols || int(op) >= len(fragTable[0]) {
		return runtime.Frag{}
	}
	return fragTable[col][op]
}

// defaultOrder is what a query with no Order() uses.
//
// It is never empty. A read without ORDER BY has no defined order, so
// paging one is a bug waiting for a plan change to expose it — and the
// primary key is the cheapest total order available.
var defaultOrder = [1]runtime.Tok{
	runtime.MakeOrder(runtime.Asc, 0), // id
}

var (
	cache       = runtime.NewTreeCache()
	offsetCache = runtime.NewTreeCache()
	countCache  = runtime.NewTreeCache()
)

// Shapes reports how many distinct query structures have compiled.
// `raorm lint` uses it to catch a builder minting a statement per request.
func Shapes() int { return cache.Shapes() }

// stmtFor compiles a read. LIMIT and LIMIT/OFFSET are different
// statements with different placeholder counts, so they get different
// caches rather than a sentinel token muddying the key.
func stmtFor(toks []runtime.Tok, withOffset bool) *runtime.Stmt {
	c, suffix := cache, limitSuffix
	if withOffset {
		c, suffix = offsetCache, limitOffsetSuffix
	}
	if st := c.Get(toks); st != nil {
		return st
	}
	return c.Put(toks, runtime.SpliceTree(selectPrefix, toks, lowering, suffix))
}

func countStmtFor(toks []runtime.Tok) *runtime.Stmt {
	if st := countCache.Get(toks); st != nil {
		return st
	}
	// A count ignores ordering as well as LIMIT: ordering a scalar is
	// wasted work, and the token stream is trimmed before it gets here.
	return countCache.Put(toks, runtime.SpliceTree(countPrefix, toks, lowering, ""))
}

// Shape is a fingerprint of this query's structure — equal shapes share a
// compiled statement. Values do not contribute, which is the point.
func (q Query) Shape() uint64 {
	var buf [21]runtime.Tok
	return runtime.HashToks(q.stream(&buf))
}

// SQL returns the compiled text for this query's structure.
func (q Query) SQL() string {
	var buf [21]runtime.Tok
	return stmtFor(q.stream(&buf), q.offset > 0).SQL
}

// Scan decodes one row from raw wire bytes into r, copying text into sl.
//
// Exported for the context package, which assembles batched results and
// therefore has to decode rows it did not issue the query for.
func Scan(rv [][]byte, r *Row, sl *runtime.Slab) error { return scan(rv, r, sl) }

// scan decodes one row straight from the wire. No reflect, no `any`, no
// driver.Value: the generator knows every column's type already.
//
// It returns an error only for a value the Go type cannot carry — a
// numeric past 18 significant digits, or a NaN. Those must not become a
// plausible zero, and a row scanner is the last place that can tell.
func scan(rv [][]byte, r *Row, sl *runtime.Slab) error {
	var decErr error
	copy(r.ID[:], rv[0])
	r.CreatedAt = runtime.Timestamptz(rv[1])
	r.UpdatedAt = runtime.Timestamptz(rv[2])
	r.Version = runtime.Int4(rv[3])
	r.DeletedAt = runtime.Nullable(rv[4], runtime.Timestamptz)
	r.Email = sl.Str(rv[5])
	r.Name = sl.Str(rv[6])
	r.Status = sl.Str(rv[7])
	r.Prefs = runtime.JSON(runtime.JSONB(rv[8], sl))
	r.Scopes, decErr = runtime.TextArray(rv[9], sl)
	if decErr != nil {
		return decErr
	}
	r.Age = runtime.Nullable(rv[10], runtime.Int2)
	r.LastIP = runtime.NullText(rv[11], sl)
	r.Balance, decErr = runtime.NumericErr(rv[12])
	if decErr != nil {
		return decErr
	}
	r.Credit, decErr = runtime.NullNumeric(rv[13])
	if decErr != nil {
		return decErr
	}
	copy(r.OrgID[:], rv[14])
	return decErr
}

type binder struct {
	vals   []any
	strs   [6]string
	nums   [6]int64
	raws   [4][16]byte
	tims   [4]time.Time
	f64s   [4]float64
	decs   [4]runtime.Decimal
	anyRaw [][16]byte
	anyStr []string
	limit  int64
	offset int64
}

var binders = runtime.NewPool(func() *binder {
	return &binder{vals: make([]any, 0, 17)}
})

// Binder is the pooled argument buffer.
type Binder = binder

func GetBinder() *Binder  { return binders.Get() }
func PutBinder(b *Binder) { binders.Put(b) }

// bind copies arena values into the pooled buffer and points the []any
// at the buffer's own fields — boxing a pointer does not allocate.
func (q Query) bind(b *binder) []any {
	v := b.vals[:0]
	var ns, nn, nr, ntm, nd uint8
	for i := uint8(0); i < q.nt; i++ {
		t := q.toks[i]
		// KLeaf binds a predicate's value; KCol binds a keyset cursor's.
		// Both live in the same per-type arenas in stream order, so the
		// column switch below handles them identically. A KCol carries no
		// operator — its op is opNone, which matches no case in the
		// operator switch and falls straight through.
		if k := t.Kind(); k != runtime.KLeaf && k != runtime.KCol {
			continue
		}
		switch runtime.Op(t.Op()) {
		case opIsNull, opIsNotNull:
			continue
		case opIn:
			if q.anyRaw != nil {
				b.anyRaw = q.anyRaw
				v = append(v, &b.anyRaw)
			} else {
				b.anyStr = q.anyStr
				v = append(v, &b.anyStr)
			}
			continue
		}
		switch t.Col() {
		case 0:
			b.raws[nr] = q.raws[nr]
			v = append(v, &b.raws[nr])
			nr++
		case 1:
			b.tims[ntm] = q.tims[ntm]
			v = append(v, &b.tims[ntm])
			ntm++
		case 2:
			b.tims[ntm] = q.tims[ntm]
			v = append(v, &b.tims[ntm])
			ntm++
		case 3:
			b.nums[nn] = q.nums[nn]
			v = append(v, &b.nums[nn])
			nn++
		case 4:
			b.tims[ntm] = q.tims[ntm]
			v = append(v, &b.tims[ntm])
			ntm++
		case 5:
			b.strs[ns] = q.strs[ns]
			v = append(v, &b.strs[ns])
			ns++
		case 6:
			b.strs[ns] = q.strs[ns]
			v = append(v, &b.strs[ns])
			ns++
		case 7:
			b.strs[ns] = q.strs[ns]
			v = append(v, &b.strs[ns])
			ns++
		case 10:
			b.nums[nn] = q.nums[nn]
			v = append(v, &b.nums[nn])
			nn++
		case 11:
			b.strs[ns] = q.strs[ns]
			v = append(v, &b.strs[ns])
			ns++
		case 12:
			b.decs[nd] = q.decs[nd]
			v = append(v, &b.decs[nd])
			nd++
		case 13:
			b.decs[nd] = q.decs[nd]
			v = append(v, &b.decs[nd])
			nd++
		case 14:
			b.raws[nr] = q.raws[nr]
			v = append(v, &b.raws[nr])
			nr++
		}
	}
	b.limit = q.limit
	v = append(v, &b.limit)
	// LIMIT and OFFSET are bound last, in the order the suffix spells
	// them. An offset of zero is absent from the statement, so binding it
	// would leave an argument nothing consumes.
	if q.offset > 0 {
		b.offset = q.offset
		v = append(v, &b.offset)
	}
	b.vals = v
	return v
}

// All runs the query and decodes every row.
func (q Query) All(ctx context.Context, ex runtime.Executor, dst []Row) ([]Row, error) {
	var sl runtime.Slab
	return q.AllInto(ctx, ex, dst, &sl)
}

// AllInto lets the caller own the string arena.
func (q Query) AllInto(ctx context.Context, ex runtime.Executor, dst []Row, sl *runtime.Slab) ([]Row, error) {
	if err := q.Err(); err != nil {
		return dst, err
	}
	var buf [21]runtime.Tok
	st := stmtFor(q.stream(&buf), q.offset > 0)
	if st.Err != nil {
		// A malformed token stream is a code-generation bug. Executing it
		// would run a query whose filter is not the one that was asked for.
		return dst, st.Err
	}
	sl.Reserve(st.SlabHint())
	b := binders.Get()
	defer binders.Put(b)

	rows, err := ex.Query(ctx, st.SQL, q.bind(b))
	if err != nil {
		return dst, err
	}
	defer rows.Close()
	for rows.Next() {
		dst = append(dst, Row{})
		if err := scan(rows.RawValues(), &dst[len(dst)-1], sl); err != nil {
			return dst, err
		}
	}
	st.ObserveSlab(sl.Size())
	return dst, rows.Err()
}

// One returns the first row, if any.
func (q Query) One(ctx context.Context, ex runtime.Executor) (Row, bool, error) {
	var sl runtime.Slab
	var buf [1]Row
	out, err := q.Limit(1).AllInto(ctx, ex, buf[:0], &sl)
	if err != nil || len(out) == 0 {
		return Row{}, false, err
	}
	return out[0], true, nil
}

// Count ignores Limit: counting a truncated set is a bug, not a feature.
func (q Query) Count(ctx context.Context, ex runtime.Executor) (int64, error) {
	if err := q.Err(); err != nil {
		return 0, err
	}
	var buf [21]runtime.Tok
	st := countStmtFor(q.preds(&buf))
	if st.Err != nil {
		// A malformed token stream is a code-generation bug. Executing it
		// would run a query whose filter is not the one that was asked for.
		return 0, st.Err
	}
	b := binders.Get()
	defer binders.Put(b)
	args := q.bind(b)
	rows, err := ex.Query(ctx, st.SQL, args[:len(args)-1]) // drop the limit
	if err != nil {
		return 0, err
	}
	defer rows.Close()
	var n int64
	if rows.Next() {
		n = runtime.Int8(rows.RawValues()[0])
	}
	return n, rows.Err()
}

// Exists is One with the row discarded.
func (q Query) Exists(ctx context.Context, ex runtime.Executor) (bool, error) {
	_, ok, err := q.Limit(1).One(ctx, ex)
	return ok, err
}

// Prepare resolves the structure and binds arguments without executing.
func (q Query) Prepare(b *Binder) (string, []any) {
	var buf [21]runtime.Tok
	return stmtFor(q.stream(&buf), q.offset > 0).SQL, q.bind(b)
}

// Greatest-n-per-group: at most n children per parent, in ONE query.
//
// The ordering is REQUIRED and must be a strict total order. "The first
// three by date" with ties on that date returns an arbitrary three, and
// a different arbitrary three on the next call — a paging bug that only
// appears under data the developer did not have. Add the primary key as
// a final term if the natural ordering is not unique.
var errNoTopOrder = errors.New(
	"raorm: a per-parent limit needs an ordering — without one \"the first three\" is an arbitrary three, and a different three next time")

// BatchTopByOrgID fetches at most n rows for each id, ordered by order.
//
// ONE round trip regardless of how many ids are passed — the per-parent
// limit is expressed in SQL, not by looping. It delegates to the lowering
// chosen at BUILD time by measurement (bench/RESULTS.md); the strategy is
// never sniffed at run time.
func BatchTopByOrgID(ctx context.Context, ex runtime.Executor, ids [][16]byte, n int64, order ...Sort) ([]Row, error) {
	return BatchTopByOrgIDLateral(ctx, ex, ids, n, order...)
}

// BatchTopByOrgIDWindow runs the window lowering.
//
// Both forms are exported so a benchmark can compare them on identical
// generated code rather than on two hand-written approximations, and so
// a caller whose data defeats the default has a way out that does not
// involve writing SQL.
func BatchTopByOrgIDWindow(ctx context.Context, ex runtime.Executor, ids [][16]byte, n int64, order ...Sort) ([]Row, error) {
	return batchTopByOrgIDRun(ctx, ex, batchTopByOrgIDWindowSQL(order), ids, n)
}

// BatchTopByOrgIDLateral runs the lateral lowering.
//
// Both forms are exported so a benchmark can compare them on identical
// generated code rather than on two hand-written approximations, and so
// a caller whose data defeats the default has a way out that does not
// involve writing SQL.
func BatchTopByOrgIDLateral(ctx context.Context, ex runtime.Executor, ids [][16]byte, n int64, order ...Sort) ([]Row, error) {
	return batchTopByOrgIDRun(ctx, ex, batchTopByOrgIDLateralSQL(order), ids, n)
}

// batchTopByOrgIDRun executes one lowered statement.
func batchTopByOrgIDRun(ctx context.Context, ex runtime.Executor, sql string, ids [][16]byte, n int64) ([]Row, error) {
	if len(ids) == 0 || n <= 0 {
		return nil, nil
	}
	if sql == "" {
		return nil, errNoTopOrder
	}
	rows, err := ex.Query(ctx, sql, []any{ids, n})
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var sl runtime.Slab
	out := make([]Row, 0, int64(len(ids))*n)
	for rows.Next() {
		out = append(out, Row{})
		if err := scan(rows.RawValues(), &out[len(out)-1], &sl); err != nil {
			return nil, err
		}
	}
	return out, rows.Err()
}

var batchTopByOrgIDWindowCache = runtime.NewTreeCache()

// batchTopByOrgIDWindowSQL compiles one ordering, once. The ordering is the key, exactly
// as it is for an ordinary read; an empty ordering yields "", which the
// runner turns into errNoTopOrder.
func batchTopByOrgIDWindowSQL(order []Sort) string {
	if len(order) == 0 {
		return ""
	}
	toks := make([]runtime.Tok, len(order))
	for i, s := range order {
		toks[i] = runtime.Tok(s)
	}
	if st := batchTopByOrgIDWindowCache.Get(toks); st != nil {
		return st.SQL
	}
	terms := make([]string, len(toks))
	for i, t := range toks {
		terms[i] = orderOf(t.Op(), t.Col())
	}
	sql := runtime.SpliceOrder("SELECT \"id\", \"created_at\", \"updated_at\", \"version\", \"deleted_at\", \"email\", \"name\", \"status\", \"prefs\", \"scopes\", \"age\", \"last_ip\", \"balance\", \"credit\", \"org_id\" FROM (SELECT \"id\", \"created_at\", \"updated_at\", \"version\", \"deleted_at\", \"email\", \"name\", \"status\", \"prefs\", \"scopes\", \"age\", \"last_ip\", \"balance\", \"credit\", \"org_id\", row_number() OVER (PARTITION BY \"org_id\"\x00order\x00) AS \"_raorm_rn\" FROM \"users\" WHERE \"org_id\" = ANY($1)) \"_raorm_t\" WHERE \"_raorm_rn\" <= $2", terms, " ORDER BY ", ", ")
	return batchTopByOrgIDWindowCache.Put(toks, &runtime.Stmt{SQL: sql, NArg: 2}).SQL
}

var batchTopByOrgIDLateralCache = runtime.NewTreeCache()

// batchTopByOrgIDLateralSQL compiles one ordering, once. The ordering is the key, exactly
// as it is for an ordinary read; an empty ordering yields "", which the
// runner turns into errNoTopOrder.
func batchTopByOrgIDLateralSQL(order []Sort) string {
	if len(order) == 0 {
		return ""
	}
	toks := make([]runtime.Tok, len(order))
	for i, s := range order {
		toks[i] = runtime.Tok(s)
	}
	if st := batchTopByOrgIDLateralCache.Get(toks); st != nil {
		return st.SQL
	}
	terms := make([]string, len(toks))
	for i, t := range toks {
		terms[i] = orderOf(t.Op(), t.Col())
	}
	sql := runtime.SpliceOrder("SELECT \"_raorm_c\".\"id\", \"_raorm_c\".\"created_at\", \"_raorm_c\".\"updated_at\", \"_raorm_c\".\"version\", \"_raorm_c\".\"deleted_at\", \"_raorm_c\".\"email\", \"_raorm_c\".\"name\", \"_raorm_c\".\"status\", \"_raorm_c\".\"prefs\", \"_raorm_c\".\"scopes\", \"_raorm_c\".\"age\", \"_raorm_c\".\"last_ip\", \"_raorm_c\".\"balance\", \"_raorm_c\".\"credit\", \"_raorm_c\".\"org_id\" FROM unnest($1::uuid[]) AS \"_raorm_p\"(\"_raorm_k\") CROSS JOIN LATERAL (SELECT \"id\", \"created_at\", \"updated_at\", \"version\", \"deleted_at\", \"email\", \"name\", \"status\", \"prefs\", \"scopes\", \"age\", \"last_ip\", \"balance\", \"credit\", \"org_id\" FROM \"users\" WHERE \"org_id\" = \"_raorm_p\".\"_raorm_k\"\x00order\x00 LIMIT $2) \"_raorm_c\"", terms, " ORDER BY ", ", ")
	return batchTopByOrgIDLateralCache.Put(toks, &runtime.Stmt{SQL: sql, NArg: 2}).SQL
}

// insertSQL does not vary: the column list is fixed by the table, so
// the placeholders are known at build time and nothing is spliced.
const insertSQL = `INSERT INTO "users" ("id", "created_at", "updated_at", "version", "deleted_at", "email", "name", "status", "prefs", "scopes", "age", "last_ip", "balance", "credit", "org_id") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15) RETURNING "id", "created_at", "updated_at", "version", "deleted_at", "email", "name", "status", "prefs", "scopes", "age", "last_ip", "balance", "credit", "org_id"`

const updatePrefix = `UPDATE "users" SET `
const deletePrefix = `DELETE FROM "users"`

// Dirty bits. One per updatable column; the set of them is an UPDATE's
// identity, exactly as a token stream is a SELECT's.
const (
	dUpdatedAt uint64 = 1 << 0
	dDeletedAt uint64 = 1 << 1
	dEmail     uint64 = 1 << 2
	dName      uint64 = 1 << 3
	dStatus    uint64 = 1 << 4
	dPrefs     uint64 = 1 << 5
	dScopes    uint64 = 1 << 6
	dAge       uint64 = 1 << 7
	dLastIP    uint64 = 1 << 8
	dBalance   uint64 = 1 << 9
	dCredit    uint64 = 1 << 10
	dOrgID     uint64 = 1 << 11
)

const nUpdatable = 12

// setFrags is every assignment this table can make, lowered at build time.
var setFrags = [nUpdatable]runtime.Frag{
	{A: "\"updated_at\" = $", B: ""}, // updated_at
	{A: "\"deleted_at\" = $", B: ""}, // deleted_at
	{A: "\"email\" = $", B: ""},      // email
	{A: "\"name\" = $", B: ""},       // name
	{A: "\"status\" = $", B: ""},     // status
	{A: "\"prefs\" = $", B: ""},      // prefs
	{A: "\"scopes\" = $", B: ""},     // scopes
	{A: "\"age\" = $", B: ""},        // age
	{A: "\"last_ip\" = $", B: ""},    // last_ip
	{A: "\"balance\" = $", B: ""},    // balance
	{A: "\"credit\" = $", B: ""},     // credit
	{A: "\"org_id\" = $", B: ""},     // org_id
}

// pkFrags addresses one row.
var pkFrags = [1]runtime.Frag{
	{A: "\"id\" = $", B: ""}, // id
}

// versionFrag is the optimistic lock. An update carrying it matches
// no row when somebody else wrote first, which is the whole mechanism.
var versionFrag = runtime.Frag{A: "\"version\" = $", B: ""}

// versionBump increments from the column's own value, never from one
// the client read — two writers who both saw 3 must not both write 4.
var versionBump = runtime.Frag{A: "\"version\" = \"version\" + 1", B: ""}

// Insert bits. A masked INSERT names only the columns the caller
// assigned, so every other column takes its database default — which is
// the only way a DEFAULT gen_random_uuid() can ever fire.
const (
	iID        uint64 = 1 << 0
	iCreatedAt uint64 = 1 << 1
	iUpdatedAt uint64 = 1 << 2
	iVersion   uint64 = 1 << 3
	iDeletedAt uint64 = 1 << 4
	iEmail     uint64 = 1 << 5
	iName      uint64 = 1 << 6
	iStatus    uint64 = 1 << 7
	iPrefs     uint64 = 1 << 8
	iScopes    uint64 = 1 << 9
	iAge       uint64 = 1 << 10
	iLastIP    uint64 = 1 << 11
	iBalance   uint64 = 1 << 12
	iCredit    uint64 = 1 << 13
	iOrgID     uint64 = 1 << 14
)

const nInsertable = 15

// insCols is the quoted column name for each insert bit.
var insCols = [nInsertable]string{
	"\"id\"",
	"\"created_at\"",
	"\"updated_at\"",
	"\"version\"",
	"\"deleted_at\"",
	"\"email\"",
	"\"name\"",
	"\"status\"",
	"\"prefs\"",
	"\"scopes\"",
	"\"age\"",
	"\"last_ip\"",
	"\"balance\"",
	"\"credit\"",
	"\"org_id\"",
}

// insParts and insPlaceholder come from the back end at build time; the
// runtime splicer chooses none of them.
var insParts = runtime.InsertParts{Open: " (", Sep: ", ", Mid: ") VALUES (", Close: ")"}

const insPlaceholder = "$"
const insPrefix = "INSERT INTO \"users\""
const insReturning = " RETURNING \"id\", \"created_at\", \"updated_at\", \"version\", \"deleted_at\", \"email\", \"name\", \"status\", \"prefs\", \"scopes\", \"age\", \"last_ip\", \"balance\", \"credit\", \"org_id\""

var insCache = runtime.NewMaskCache()
var updCache = runtime.NewMaskCache()

// Masks reports how many distinct UPDATE shapes have compiled.
func Masks() int { return updCache.Masks() }

// Mut is a row staged for update: the values, plus which of them were
// actually assigned. An UPDATE writes the assigned ones and no others,
// so a read-modify-write cannot clobber a column it never looked at.
type Mut struct {
	row   Row
	dirty uint64
}

// Mutate stages a row read from the database.
func Mutate(r Row) Mut { return Mut{row: r} }

// Row returns the staged values.
func (m Mut) Row() Row { return m.row }

// Dirty reports the assigned-column mask, which is also the statement key.
func (m Mut) Dirty() uint64 { return m.dirty }

// Setters. There is deliberately no setter for the primary key, for an
// Immutable column, or for the version column: the absence of a method is
// the enforcement, so misuse does not compile rather than failing later.
func (m *Mut) SetUpdatedAt(v time.Time) {
	m.row.UpdatedAt = v
	m.dirty |= dUpdatedAt
}

func (m *Mut) SetDeletedAt(v time.Time) {
	m.row.DeletedAt = runtime.Null[time.Time]{V: v, Valid: true}
	m.dirty |= dDeletedAt
}

// SetDeletedAtNull writes SQL NULL. It is a separate method because a
// zero value and an absent value are different facts.
func (m *Mut) SetDeletedAtNull() {
	m.row.DeletedAt = runtime.Null[time.Time]{}
	m.dirty |= dDeletedAt
}

func (m *Mut) SetEmail(v string) {
	m.row.Email = v
	m.dirty |= dEmail
}

func (m *Mut) SetName(v string) {
	m.row.Name = v
	m.dirty |= dName
}

func (m *Mut) SetStatus(v string) {
	m.row.Status = v
	m.dirty |= dStatus
}

func (m *Mut) SetPrefs(v runtime.JSON) {
	m.row.Prefs = v
	m.dirty |= dPrefs
}

func (m *Mut) SetScopes(v []string) {
	m.row.Scopes = v
	m.dirty |= dScopes
}

func (m *Mut) SetAge(v int16) {
	m.row.Age = runtime.Null[int16]{V: v, Valid: true}
	m.dirty |= dAge
}

// SetAgeNull writes SQL NULL. It is a separate method because a
// zero value and an absent value are different facts.
func (m *Mut) SetAgeNull() {
	m.row.Age = runtime.Null[int16]{}
	m.dirty |= dAge
}

func (m *Mut) SetLastIP(v string) {
	m.row.LastIP = runtime.Null[string]{V: v, Valid: true}
	m.dirty |= dLastIP
}

// SetLastIPNull writes SQL NULL. It is a separate method because a
// zero value and an absent value are different facts.
func (m *Mut) SetLastIPNull() {
	m.row.LastIP = runtime.Null[string]{}
	m.dirty |= dLastIP
}

func (m *Mut) SetBalance(v runtime.Decimal) {
	m.row.Balance = v
	m.dirty |= dBalance
}

func (m *Mut) SetCredit(v runtime.Decimal) {
	m.row.Credit = runtime.Null[runtime.Decimal]{V: v, Valid: true}
	m.dirty |= dCredit
}

// SetCreditNull writes SQL NULL. It is a separate method because a
// zero value and an absent value are different facts.
func (m *Mut) SetCreditNull() {
	m.row.Credit = runtime.Null[runtime.Decimal]{}
	m.dirty |= dCredit
}

func (m *Mut) SetOrgID(v [16]byte) {
	m.row.OrgID = v
	m.dirty |= dOrgID
}

// Ins stages a new row. Unlike Mut it has a setter for every insertable
// column including the primary key and Immutable ones — supplying your
// own id is legitimate, changing it later is not.
//
// A column left unset is absent from the statement, so the database
// applies its default. Absence is tracked by the mask, never inferred
// from a zero value: that inference is why other ORMs cannot insert a
// false, a 0 or an empty string into a column that has a default.
type Ins struct {
	row Row
	set uint64

	// conflict is the upsert target, as a bit per unique-constraint
	// column set. Zero means a plain insert, and a duplicate is an error
	// — which is the right default: silently updating a row you meant to
	// create is a data-loss bug that looks like success.
	conflict uint8
}

// Create stages a new row.
func Create() Ins { return Ins{} }

// Assigned reports the mask, which is also the statement key.
func (n Ins) Assigned() uint64 { return n.set }

func (n *Ins) SetID(v [16]byte) {
	n.row.ID = v
	n.set |= iID
}

func (n *Ins) SetCreatedAt(v time.Time) {
	n.row.CreatedAt = v
	n.set |= iCreatedAt
}

func (n *Ins) SetUpdatedAt(v time.Time) {
	n.row.UpdatedAt = v
	n.set |= iUpdatedAt
}

func (n *Ins) SetVersion(v int32) {
	n.row.Version = v
	n.set |= iVersion
}

func (n *Ins) SetDeletedAt(v time.Time) {
	n.row.DeletedAt = runtime.Null[time.Time]{V: v, Valid: true}
	n.set |= iDeletedAt
}

// SetDeletedAtNull writes SQL NULL explicitly, which is not the same as
// leaving the column unset and taking its default.
func (n *Ins) SetDeletedAtNull() {
	n.row.DeletedAt = runtime.Null[time.Time]{}
	n.set |= iDeletedAt
}

func (n *Ins) SetEmail(v string) {
	n.row.Email = v
	n.set |= iEmail
}

func (n *Ins) SetName(v string) {
	n.row.Name = v
	n.set |= iName
}

func (n *Ins) SetStatus(v string) {
	n.row.Status = v
	n.set |= iStatus
}

func (n *Ins) SetPrefs(v runtime.JSON) {
	n.row.Prefs = v
	n.set |= iPrefs
}

func (n *Ins) SetScopes(v []string) {
	n.row.Scopes = v
	n.set |= iScopes
}

func (n *Ins) SetAge(v int16) {
	n.row.Age = runtime.Null[int16]{V: v, Valid: true}
	n.set |= iAge
}

// SetAgeNull writes SQL NULL explicitly, which is not the same as
// leaving the column unset and taking its default.
func (n *Ins) SetAgeNull() {
	n.row.Age = runtime.Null[int16]{}
	n.set |= iAge
}

func (n *Ins) SetLastIP(v string) {
	n.row.LastIP = runtime.Null[string]{V: v, Valid: true}
	n.set |= iLastIP
}

// SetLastIPNull writes SQL NULL explicitly, which is not the same as
// leaving the column unset and taking its default.
func (n *Ins) SetLastIPNull() {
	n.row.LastIP = runtime.Null[string]{}
	n.set |= iLastIP
}

func (n *Ins) SetBalance(v runtime.Decimal) {
	n.row.Balance = v
	n.set |= iBalance
}

func (n *Ins) SetCredit(v runtime.Decimal) {
	n.row.Credit = runtime.Null[runtime.Decimal]{V: v, Valid: true}
	n.set |= iCredit
}

// SetCreditNull writes SQL NULL explicitly, which is not the same as
// leaving the column unset and taking its default.
func (n *Ins) SetCreditNull() {
	n.row.Credit = runtime.Null[runtime.Decimal]{}
	n.set |= iCredit
}

func (n *Ins) SetOrgID(v [16]byte) {
	n.row.OrgID = v
	n.set |= iOrgID
}

// upsertTails builds the ON CONFLICT tail for one target, given the
// insert mask — an upsert must only overwrite the columns the caller
// assigned, or it silently reverts every column it did not.
var upsertTails = []func(uint64) string{
	func(mask uint64) string {
		set := make([]string, 0, 12)
		if mask&(1<<2) != 0 {
			set = append(set, "updated_at")
		}
		if mask&(1<<4) != 0 {
			set = append(set, "deleted_at")
		}
		if mask&(1<<5) != 0 {
			set = append(set, "email")
		}
		if mask&(1<<6) != 0 {
			set = append(set, "name")
		}
		if mask&(1<<7) != 0 {
			set = append(set, "status")
		}
		if mask&(1<<8) != 0 {
			set = append(set, "prefs")
		}
		if mask&(1<<9) != 0 {
			set = append(set, "scopes")
		}
		if mask&(1<<10) != 0 {
			set = append(set, "age")
		}
		if mask&(1<<11) != 0 {
			set = append(set, "last_ip")
		}
		if mask&(1<<12) != 0 {
			set = append(set, "balance")
		}
		if mask&(1<<13) != 0 {
			set = append(set, "credit")
		}
		if mask&(1<<14) != 0 {
			set = append(set, "org_id")
		}
		return onConflictID(set)
	},
}

func onConflictID(set []string) string {
	switch len(set) {
	case 0:
		return " ON CONFLICT (\"id\") DO NOTHING"
	}
	return " ON CONFLICT (\"id\") DO UPDATE SET " + joinAssign(set)
}

// OnConflictID upserts on the unique key (id).
func (n *Ins) OnConflictID() *Ins {
	n.conflict = 1
	return n
}

// joinAssign renders the DO UPDATE SET list for the columns the caller
// assigned. The punctuation comes from the back end, never from here.
func joinAssign(set []string) string {
	out := ""
	for i, c := range set {
		if i > 0 {
			out += ", "
		}
		out += assignExcluded(c)
	}
	return out
}

var assignFor = map[string]string{
	"updated_at": "\"updated_at\" = EXCLUDED.\"updated_at\"",
	"deleted_at": "\"deleted_at\" = EXCLUDED.\"deleted_at\"",
	"email":      "\"email\" = EXCLUDED.\"email\"",
	"name":       "\"name\" = EXCLUDED.\"name\"",
	"status":     "\"status\" = EXCLUDED.\"status\"",
	"prefs":      "\"prefs\" = EXCLUDED.\"prefs\"",
	"scopes":     "\"scopes\" = EXCLUDED.\"scopes\"",
	"age":        "\"age\" = EXCLUDED.\"age\"",
	"last_ip":    "\"last_ip\" = EXCLUDED.\"last_ip\"",
	"balance":    "\"balance\" = EXCLUDED.\"balance\"",
	"credit":     "\"credit\" = EXCLUDED.\"credit\"",
	"org_id":     "\"org_id\" = EXCLUDED.\"org_id\"",
}

func assignExcluded(c string) string { return assignFor[c] }

func stmtForInsert(mask uint64, conflict uint8) *runtime.Stmt {
	// The conflict target is part of the statement, so it must be part of
	// the key. Packing it above the column bits keeps one cache for both.
	key := mask | uint64(conflict)<<nInsertable
	if st := insCache.Get(key); st != nil {
		return st
	}
	cols := make([]string, 0, nInsertable)
	for i := 0; i < nInsertable; i++ {
		if mask&(1<<uint(i)) != 0 {
			cols = append(cols, insCols[i])
		}
	}
	suffix := insReturning
	if conflict > 0 {
		suffix = upsertTails[conflict-1](mask) + insReturning
	}
	return insCache.Put(key, runtime.SpliceInsert(insPrefix, insParts, cols, insPlaceholder, suffix))
}

// Insert writes the assigned columns and reads every column back, so
// database-computed values land in the returned Row rather than needing a
// second SELECT that would race every other writer.
func (n *Ins) Insert(ctx context.Context, ex runtime.Executor) (Row, error) {
	if n.set == 0 {
		return Row{}, runtime.ErrNothingAssigned
	}
	st := stmtForInsert(n.set, n.conflict)
	if st.Err != nil {
		// A malformed token stream is a code-generation bug. Executing it
		// would run a query whose filter is not the one that was asked for.
		return Row{}, st.Err
	}
	args := make([]any, 0, st.NArg)
	for i := 0; i < nInsertable; i++ {
		if n.set&(1<<uint(i)) == 0 {
			continue
		}
		switch i {
		case 0:
			args = append(args, n.row.ID)
		case 1:
			args = append(args, n.row.CreatedAt)
		case 2:
			args = append(args, n.row.UpdatedAt)
		case 3:
			args = append(args, n.row.Version)
		case 4:
			args = append(args, n.row.DeletedAt.Arg())
		case 5:
			args = append(args, n.row.Email)
		case 6:
			args = append(args, n.row.Name)
		case 7:
			args = append(args, n.row.Status)
		case 8:
			args = append(args, n.row.Prefs)
		case 9:
			args = append(args, n.row.Scopes)
		case 10:
			args = append(args, n.row.Age.Arg())
		case 11:
			args = append(args, n.row.LastIP.Arg())
		case 12:
			args = append(args, n.row.Balance)
		case 13:
			args = append(args, n.row.Credit.Arg())
		case 14:
			args = append(args, n.row.OrgID)
		}
	}
	var out Row
	rows, err := ex.Query(ctx, st.SQL, args)
	if err != nil {
		return out, err
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return out, err
		}
		return out, runtime.ErrNoRow
	}
	var sl runtime.Slab
	if err := scan(rows.RawValues(), &out, &sl); err != nil {
		return out, err
	}
	return out, rows.Err()
}

// Inserts reports how many distinct INSERT column sets have compiled.
func Inserts() int { return insCache.Masks() }

// Insert writes one row and reads back every column, so database-computed
// defaults — a generated id, a now() timestamp — land in r rather than
// needing a second SELECT that would race every other writer.
//
// Every insertable column is written, including zero values. raorm does
// not treat a zero as 'unset': that guess is why other ORMs cannot insert
// a false, a 0 or an empty string into a column with a default.
func Insert(ctx context.Context, ex runtime.Executor, r *Row) error {
	args := make([]any, 0, 15)
	args = append(args, r.ID)
	args = append(args, r.CreatedAt)
	args = append(args, r.UpdatedAt)
	args = append(args, r.Version)
	args = append(args, r.DeletedAt.Arg())
	args = append(args, r.Email)
	args = append(args, r.Name)
	args = append(args, r.Status)
	args = append(args, r.Prefs)
	args = append(args, r.Scopes)
	args = append(args, r.Age.Arg())
	args = append(args, r.LastIP.Arg())
	args = append(args, r.Balance)
	args = append(args, r.Credit.Arg())
	args = append(args, r.OrgID)
	rows, err := ex.Query(ctx, insertSQL, args)
	if err != nil {
		return err
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return err
		}
		return runtime.ErrNoRow
	}
	// The returned strings live as long as this Slab, and the Slab lives
	// as long as r — a Row from an insert owns its own arena, unlike a Row
	// from a scan, which shares the result set's.
	var sl runtime.Slab
	if err := scan(rows.RawValues(), r, &sl); err != nil {
		return err
	}
	return rows.Err()
}

// copyCols is the fixed column list of a bulk load. Unlike Ins there is
// no mask: COPY sends one shape for the whole stream, so every row must
// supply every column and database defaults do not apply. Fill the row
// yourself, or use Create() per row and give up the bulk path.
var copyCols = []string{
	"id",
	"created_at",
	"updated_at",
	"version",
	"deleted_at",
	"email",
	"name",
	"status",
	"prefs",
	"scopes",
	"age",
	"last_ip",
	"balance",
	"credit",
	"org_id",
}

// rowSource walks a []Row for CopyFrom without copying any of it.
type rowSource struct {
	rows []Row
	i    int
	buf  [15]any
}

func (s *rowSource) Next() bool {
	s.i++
	return s.i <= len(s.rows)
}

// Values reuses one buffer across every row, and fills it with POINTERS
// into the caller's slice rather than copies.
//
// Both halves matter. The driver consumes each slice before asking for
// the next, so one buffer is safe. And boxing a pointer into an `any`
// does not allocate while boxing a value does — at a thousand rows that
// is one allocation per column per row, or none. Measured: the first cut
// boxed values and cost 7 allocations per row.
func (s *rowSource) Values() []any {
	r := &s.rows[s.i-1]
	s.buf[0] = &r.ID
	s.buf[1] = &r.CreatedAt
	s.buf[2] = &r.UpdatedAt
	s.buf[3] = &r.Version
	s.buf[4] = r.DeletedAt.Ptr()
	s.buf[5] = &r.Email
	s.buf[6] = &r.Name
	s.buf[7] = &r.Status
	s.buf[8] = &r.Prefs
	s.buf[9] = &r.Scopes
	s.buf[10] = r.Age.Ptr()
	s.buf[11] = r.LastIP.Ptr()
	s.buf[12] = &r.Balance
	s.buf[13] = r.Credit.Ptr()
	s.buf[14] = &r.OrgID
	return s.buf[:]
}

func (s *rowSource) Err() error { return nil }

// InsertAll bulk-loads rows through the driver's COPY protocol: ONE round
// trip regardless of row count, because COPY is a different wire path and
// not a faster loop over INSERT.
//
// It returns no rows. COPY has no RETURNING, so a caller who needs
// database-generated ids must supply them — which is why the primary key
// is in copyCols and must be set on every row.
func InsertAll(ctx context.Context, ex runtime.Executor, rows []Row) (int64, error) {
	if len(rows) == 0 {
		return 0, nil
	}
	src := &rowSource{rows: rows}
	return ex.CopyFrom(ctx, "users", copyCols, src)
}

// InsertOp is an insert as a queueable statement. It writes every
// insertable column, because a batch of a thousand rows that each chose
// a different column set would compile a thousand statements and defeat
// the point of batching them.
//
// WantRows is false: a batched insert reports a count. Asking for
// RETURNING here would mean scanning a result per statement, which is
// exactly the per-row work a batch exists to avoid.
func InsertOp(r Row) runtime.BatchOp {
	var mask uint64
	mask |= 1 << 0
	mask |= 1 << 1
	mask |= 1 << 2
	mask |= 1 << 3
	mask |= 1 << 4
	mask |= 1 << 5
	mask |= 1 << 6
	mask |= 1 << 7
	mask |= 1 << 8
	mask |= 1 << 9
	mask |= 1 << 10
	mask |= 1 << 11
	mask |= 1 << 12
	mask |= 1 << 13
	mask |= 1 << 14
	st := stmtForInsert(mask, 0)
	args := make([]any, 0, 15)
	args = append(args, r.ID)
	args = append(args, r.CreatedAt)
	args = append(args, r.UpdatedAt)
	args = append(args, r.Version)
	args = append(args, r.DeletedAt.Arg())
	args = append(args, r.Email)
	args = append(args, r.Name)
	args = append(args, r.Status)
	args = append(args, r.Prefs)
	args = append(args, r.Scopes)
	args = append(args, r.Age.Arg())
	args = append(args, r.LastIP.Arg())
	args = append(args, r.Balance)
	args = append(args, r.Credit.Arg())
	args = append(args, r.OrgID)
	return runtime.BatchOp{SQL: st.SQL, Args: args}
}

// UpdateOp is this Mut's update as a queueable statement.
//
// The optimistic lock still applies, but the caller must check the
// affected count the batch reports: a stale write inside a batch is not
// an error the driver raises, it is a zero the caller has to notice.
func (m *Mut) UpdateOp() (runtime.BatchOp, bool) {
	if m.dirty == 0 {
		return runtime.BatchOp{}, false
	}
	st := stmtForMask(m.dirty)
	args := make([]any, 0, st.NArg)
	for i := 0; i < nUpdatable; i++ {
		if m.dirty&(1<<uint(i)) == 0 {
			continue
		}
		switch i {
		case 0:
			args = append(args, m.row.UpdatedAt)
		case 1:
			args = append(args, m.row.DeletedAt.Arg())
		case 2:
			args = append(args, m.row.Email)
		case 3:
			args = append(args, m.row.Name)
		case 4:
			args = append(args, m.row.Status)
		case 5:
			args = append(args, m.row.Prefs)
		case 6:
			args = append(args, m.row.Scopes)
		case 7:
			args = append(args, m.row.Age.Arg())
		case 8:
			args = append(args, m.row.LastIP.Arg())
		case 9:
			args = append(args, m.row.Balance)
		case 10:
			args = append(args, m.row.Credit.Arg())
		case 11:
			args = append(args, m.row.OrgID)
		}
	}
	args = append(args, m.row.ID)
	args = append(args, m.row.Version)
	return runtime.BatchOp{SQL: st.SQL, Args: args}, true
}

// DeleteOp is a delete as a queueable statement.
func DeleteOp(iD [16]byte) runtime.BatchOp {
	return runtime.BatchOp{SQL: deleteSQL, Args: []any{iD}}
}

// Table is the table these statements write, so a Unit can order a mixed
// batch by foreign key without knowing what any of them are.
const Table = "users"

// stmtForMask compiles the UPDATE for one dirty mask, once.
func stmtForMask(mask uint64) *runtime.Stmt {
	if st := updCache.Get(mask); st != nil {
		return st
	}
	set := make([]runtime.Frag, 0, nUpdatable+1)
	for i := 0; i < nUpdatable; i++ {
		if mask&(1<<uint(i)) != 0 {
			set = append(set, setFrags[i])
		}
	}
	set = append(set, versionBump)
	where := make([]runtime.Frag, 0, 2)
	where = append(where, pkFrags[:]...)
	where = append(where, versionFrag)
	return updCache.Put(mask, runtime.SpliceSections(updatePrefix, []runtime.Section{
		{Lead: "", Sep: ", ", Frags: set},
		{Lead: " WHERE ", Sep: " AND ", Frags: where},
	}, ""))
}

// Update writes the assigned columns of one row.
//
// The version column makes this an optimistic lock: the statement matches
// only a row still at the version that was read, and a miss is
// runtime.ErrStaleWrite rather than a silent no-op. Re-read and retry;
// do not force it, because the update was computed from a value that is
// no longer true.
// Assigning nothing is not an error and issues no statement — an UPDATE
// with an empty SET list is not valid SQL, and a caller looping over
// possibly-changed fields should not have to special-case the empty case.
func (m *Mut) Update(ctx context.Context, ex runtime.Executor) error {
	if m.dirty == 0 {
		return nil
	}
	st := stmtForMask(m.dirty)
	if st.Err != nil {
		// A malformed token stream is a code-generation bug. Executing it
		// would run a query whose filter is not the one that was asked for.
		return st.Err
	}
	args := make([]any, 0, st.NArg)
	for i := 0; i < nUpdatable; i++ {
		if m.dirty&(1<<uint(i)) == 0 {
			continue
		}
		switch i {
		case 0:
			args = append(args, m.row.UpdatedAt)
		case 1:
			args = append(args, m.row.DeletedAt.Arg())
		case 2:
			args = append(args, m.row.Email)
		case 3:
			args = append(args, m.row.Name)
		case 4:
			args = append(args, m.row.Status)
		case 5:
			args = append(args, m.row.Prefs)
		case 6:
			args = append(args, m.row.Scopes)
		case 7:
			args = append(args, m.row.Age.Arg())
		case 8:
			args = append(args, m.row.LastIP.Arg())
		case 9:
			args = append(args, m.row.Balance)
		case 10:
			args = append(args, m.row.Credit.Arg())
		case 11:
			args = append(args, m.row.OrgID)
		}
	}
	args = append(args, m.row.ID)
	args = append(args, m.row.Version)
	n, err := ex.Exec(ctx, st.SQL, args)
	if err != nil {
		return err
	}
	if n == 0 {
		return runtime.ErrStaleWrite
	}
	m.dirty = 0
	m.row.Version++ // the database incremented it; keep the staged row usable
	return nil
}

var deleteSQL = runtime.SpliceSections(deletePrefix, []runtime.Section{
	{Lead: " WHERE ", Sep: " AND ", Frags: pkFrags[:]},
}, "").SQL

// Delete removes one row by primary key. A row that was already gone is
// runtime.ErrNoRow, not success: a caller deleting something that is not
// there usually has a bug, and swallowing it hides the bug.
func Delete(ctx context.Context, ex runtime.Executor, iD [16]byte) error {
	n, err := ex.Exec(ctx, deleteSQL, []any{iD})
	if err != nil {
		return err
	}
	if n == 0 {
		return runtime.ErrNoRow
	}
	return nil
}
