// Package runtime is what generated code calls at query time.
//
// It is the only part of raorm on the hot path, and it obeys the rules in
// AGENTS.md: no reflect, no `any` boxing per column, no map lookup per query,
// no allocation on a warm path.
package runtime

import (
	"strconv"
	"sync/atomic"
)

// A shape is the identity of one query's SQL text. M0 used a bitmask over six
// fixed filter slots, indexed into a flat array. That does not generalise: a
// real table has more (column, operator) pairs than a uint64 has bits.
//
// So a shape is instead the *packed sequence* of predicate ids — up to eight
// one-byte ids, order included, because order changes the SQL. Distinct queries
// therefore get distinct shapes without hashing anything the caller supplied,
// and the cache is probed with a single multiply-shift.

// MaxPacked is how many predicates fit in a packed shape key.
const MaxPacked = 8

// Shape identifies one compiled statement.
type Shape uint64

// Push appends a predicate id. Ids above 255, or a ninth predicate, set the
// overflow bit: such queries still work, they just compile per distinct
// sequence through the slower path.
func (s Shape) Push(n int, id uint16) (Shape, int) {
	if n >= MaxPacked || id > 0xff {
		return s | overflow, n + 1
	}
	return s | Shape(id)<<(n*8), n + 1
}

const overflow Shape = 1 << 63

// Stmt is a compiled statement: immutable, interned, shared by every caller
// that produces the same shape.
type Stmt struct {
	SQL  string
	NArg int

	// slabHint is the byte size the last result of this shape needed from a
	// Slab. Shapes are stable, so one observation sizes the next arena exactly
	// and the doubling ramp never runs. Measured worth 1.8x throughput.
	slabHint atomic.Int64
}

// SlabHint reports the size to pre-size an arena to.
func (s *Stmt) SlabHint() int { return int(s.slabHint.Load()) }

// ObserveSlab records how much arena the last result actually used.
func (s *Stmt) ObserveSlab(n int) { s.slabHint.Store(int64(n)) }

// Cache maps shapes to compiled statements. Open-addressed with atomic slots:
// no lock, no allocation, and no map hashing of caller data on the warm path.
type Cache struct {
	// last is a one-entry L1. M0 indexed a flat array because six filters gave
	// only 64 shapes; a real table has far more, so the general cache probes.
	// But a call site almost always reuses one shape, and a single pointer load
	// plus a compare is much cheaper than a multiply-shift and a probe loop.
	// Shape and statement live in one struct so a reader can never see a
	// mismatched pair.
	last atomic.Pointer[hot]

	mask    uint64
	entries []cacheEntry
}

type hot struct {
	shape Shape
	stmt  *Stmt
}

type cacheEntry struct {
	shape atomic.Uint64
	stmt  atomic.Pointer[Stmt]
}

// NewCache sizes a cache to the next power of two at least 2x n.
func NewCache(n int) *Cache {
	size := 16
	for size < n*2 {
		size <<= 1
	}
	return &Cache{mask: uint64(size - 1), entries: make([]cacheEntry, size)}
}

// fibmix is a single multiply-shift. It is not a cryptographic hash and does
// not need to be: shapes are generated by the compiler, never by a caller.
func (c *Cache) slot(s Shape) uint64 {
	return (uint64(s) * 0x9E3779B97F4A7C15) >> 32 & c.mask
}

// Get returns the compiled statement for a shape, or nil.
func (c *Cache) Get(s Shape) *Stmt {
	if h := c.last.Load(); h != nil && h.shape == s {
		return h.stmt
	}
	return c.getSlow(s)
}

func (c *Cache) getSlow(s Shape) *Stmt {
	i := c.slot(s)
	for probe := 0; probe < 8; probe++ {
		e := &c.entries[(i+uint64(probe))&c.mask]
		got := e.shape.Load()
		if got == uint64(s)+1 { // +1 so zero means empty
			st := e.stmt.Load()
			if st != nil {
				c.last.Store(&hot{shape: s, stmt: st})
			}
			return st
		}
		if got == 0 {
			return nil
		}
	}
	return nil
}

// Put stores a compiled statement. A lost race simply discards the loser's
// copy; both are identical by construction.
func (c *Cache) Put(s Shape, st *Stmt) *Stmt {
	i := c.slot(s)
	for probe := 0; probe < 8; probe++ {
		e := &c.entries[(i+uint64(probe))&c.mask]
		got := e.shape.Load()
		if got == uint64(s)+1 {
			if existing := e.stmt.Load(); existing != nil {
				return existing
			}
			e.stmt.Store(st)
			return st
		}
		if got == 0 && e.shape.CompareAndSwap(0, uint64(s)+1) {
			e.stmt.Store(st)
			c.last.Store(&hot{shape: s, stmt: st})
			return st
		}
	}
	// All probes taken: fall back to returning the caller's statement
	// uncached. Correct, just not memoised — and `raorm lint` reports the
	// shape count that got us here.
	return st
}

// Frag is a predicate lowered at build time. It renders as A + <ordinal> + B,
// so the placeholder number is the only thing decided per shape.
type Frag struct{ A, B string }

// Splice assembles a statement from fragments. Cold path only: paid once per
// shape for the life of the process.
func Splice(prefix string, frags []Frag, suffix string, trailingArgs int) *Stmt {
	b := make([]byte, 0, 256)
	b = append(b, prefix...)
	ord := 0
	for i := range frags {
		if ord == 0 {
			b = append(b, " WHERE "...)
		} else {
			b = append(b, " AND "...)
		}
		ord++
		b = append(b, frags[i].A...)
		b = strconv.AppendInt(b, int64(ord), 10)
		b = append(b, frags[i].B...)
	}
	b = append(b, suffix...)
	for i := 0; i < trailingArgs; i++ {
		ord++
		b = strconv.AppendInt(b, int64(ord), 10)
		if i+1 < trailingArgs {
			b = append(b, ", $"...)
		}
	}
	return &Stmt{SQL: string(b), NArg: ord}
}

// Pool is a typed sync.Pool. Generated code needs one per table, and the
// generic wrapper keeps the type assertion out of the generated source.
type Pool[T any] struct {
	p   chan *T
	new func() *T
}

// NewPool builds a pool. The channel is bounded, so a burst cannot pin memory.
func NewPool[T any](new func() *T) *Pool[T] {
	return &Pool[T]{p: make(chan *T, 64), new: new}
}

func (p *Pool[T]) Get() *T {
	select {
	case v := <-p.p:
		return v
	default:
		return p.new()
	}
}

func (p *Pool[T]) Put(v *T) {
	select {
	case p.p <- v:
	default:
	}
}
