// Code generated by storm (devel). DO NOT EDIT.
// source: table teams

package store

import "github.com/gsoultan/storm"

// Ghost would be discovered as a model if generated files were not skipped,
// which would make every second `generate` differ from the first.
type Ghost struct {
	storm.Model
	Name string
}
