package orabench

// The DDL storm emits for Oracle, APPLIED.
//
// docs/PRODUCTION-READINESS.md P6.7 is why this exists and why it executes
// rather than asserting on text: a generator that agrees with itself proves
// nothing. compile/oraddl was written before runtime/oradrv on purpose — the
// SQL is the half a borrowed client can prove, and proving it after writing a
// driver against untested SQL is the order M9 showed is expensive.
//
// The model here is deliberately the AWKWARD one: every type that crosses, an
// enum, a generated column, a soft-delete table whose live-scoped unique is a
// partial index everywhere else, and a foreign key. If Oracle takes this, it
// takes what storm generates.

import (
	"database/sql"
	"strings"
	"testing"
	"time"

	"github.com/gsoultan/storm"
	"github.com/gsoultan/storm/compile/oraddl"
)

type oraStatus string

func (oraStatus) EnumValues() []string { return []string{"new", "paid", "void"} }

type ddlOrg struct {
	storm.Model
	Name    string
	Seats   int32
	Balance storm.Decimal
	Active  bool
	Opened  time.Time
	Blob    []byte
	Status  oraStatus
	Upper   string
	Doc     storm.JSON
}

func (o *ddlOrg) Schema(t *storm.Table) {
	t.Col(&o.Name).Size(200)
	t.Col(&o.Balance).Numeric(19, 4)
	t.Col(&o.Opened).Date()
	t.Col(&o.Upper).Generated(`UPPER("name")`)
	t.Unique(&o.Name)
	t.Index(&o.Seats)
}

type ddlMember struct {
	storm.Model
	Email     string
	Rank      int64
	DeletedAt *time.Time
	Org       ddlOrg
}

func (m *ddlMember) Schema(t *storm.Table) {
	t.Col(&m.Email).Size(255)
	// The soft-delete shape. A partial UNIQUE is a filtered index on SQL
	// Server, refused outright on MySQL, and a function-based index on a CASE
	// here — measured in constructs_test.go and generated by oraddl.
	//
	// The predicate is the model's own SQL and every back end passes it
	// through, so it is written in the target's spelling: Oracle quotes with
	// double quotes, and an unquoted name would fold UP and not resolve.
	t.Index(&m.Email).Unique().Where(`"deleted_at" IS NULL`)
}

// tables in dependency order for teardown: children first.
var ddlTables = []string{"ddl_members", "ddl_orgs"}

func TestTheDDLStormEmitsApplies(t *testing.T) {
	db := open(t)

	s, err := storm.Build(&ddlOrg{}, &ddlMember{})
	if err != nil {
		t.Fatal(err)
	}
	stmts, err := oraddl.Statements(s)
	if err != nil {
		t.Fatalf("oraddl refused a model it should take:\n%v", err)
	}

	for _, tb := range ddlTables {
		drop(db, "TABLE", `"`+tb+`" CASCADE CONSTRAINTS PURGE`)
	}
	t.Cleanup(func() {
		for _, tb := range ddlTables {
			drop(db, "TABLE", `"`+tb+`" CASCADE CONSTRAINTS PURGE`)
		}
	})

	for i, st := range stmts {
		if _, err := db.Exec(st); err != nil {
			t.Fatalf("statement %d refused by the server:\n%s\n  %v", i, st, err)
		}
		t.Logf("  ok  %s", firstLine2(st))
	}

	// And it is not just accepted — it is the shape asked for. A CREATE TABLE
	// the server takes and stores differently is the failure a round trip
	// catches and a text assertion does not.
	assertCol(t, db, "ddl_orgs", "name", "VARCHAR2", 200)
	assertCol(t, db, "ddl_orgs", "status", "VARCHAR2", 4) // the widest label
	assertCol(t, db, "ddl_orgs", "id", "RAW", 16)
	assertCol(t, db, "ddl_orgs", "active", "BOOLEAN", 0)
	assertCol(t, db, "ddl_orgs", "doc", "JSON", 0)

	// The enum's CHECK exists and does its job, which is the whole of what an
	// enum means where there is no enum type.
	if _, err := db.Exec(
		`INSERT INTO "ddl_orgs" ("name","seats","balance","active","opened","status") ` +
			`VALUES ('acme',1,0,TRUE,DATE '2026-01-01','nope')`); err == nil {
		t.Error("a value outside the enum's labels was accepted; the CHECK is not doing its job")
	}

	// The soft-delete unique. Two live rows with one email must collide; a
	// deleted one must not — which is the property a partial index gives and
	// the reason MySQL cannot take this model.
	mustExec(t, db, `INSERT INTO "ddl_orgs" ("name","seats","balance","active","opened","status") `+
		`VALUES ('acme',1,0,TRUE,DATE '2026-01-01','new')`)
	var orgID []byte
	if err := db.QueryRow(`SELECT "id" FROM "ddl_orgs" WHERE "name" = 'acme'`).Scan(&orgID); err != nil {
		t.Fatal(err)
	}
	ins := `INSERT INTO "ddl_members" ("email","rank","deleted_at","org_id") VALUES (:1,:2,:3,:4)`
	mustExec(t, db, ins, "a@example.com", 1, nil, orgID)
	if _, err := db.Exec(ins, "a@example.com", 2, nil, orgID); err == nil {
		t.Error("two LIVE rows with one email were accepted; the live-scoped unique is not enforced")
	}
	// Soft-deleted, the same email is free again.
	mustExec(t, db, ins, "a@example.com", 3, time.Now().UTC(), orgID)
}

// A model Oracle cannot take is refused by NAME, before anything is applied.
func TestANullableTextModelIsRefusedBeforeItIsApplied(t *testing.T) {
	type bad struct {
		storm.Model
		Note *string
	}
	s, err := storm.Build(&bad{})
	if err != nil {
		t.Fatal(err)
	}
	if _, err := oraddl.Statements(s); err == nil {
		t.Fatal("a nullable text column was accepted")
	} else if !strings.Contains(err.Error(), "empty string") {
		t.Errorf("the refusal must name the reason: %v", err)
	}
}

// assertCol reads the CATALOGUE rather than the DDL. A CREATE TABLE the server
// accepts and stores differently is the failure this catches and a text
// assertion cannot: M10 found exactly that shape when max_length turned out to
// be bytes and halved every imported width.
func assertCol(t *testing.T, db *sql.DB, table, col, wantType string, wantLen int) {
	t.Helper()
	var gotType string
	var charLen, dataLen sql.NullInt64
	err := db.QueryRow(`SELECT data_type, char_length, data_length FROM user_tab_columns
		WHERE table_name = :1 AND column_name = :2`, table, col).Scan(&gotType, &charLen, &dataLen)
	if err != nil {
		t.Errorf("%s.%s: %v", table, col, err)
		return
	}
	if gotType != wantType {
		t.Errorf("%s.%s is %s, want %s", table, col, gotType, wantType)
	}
	if wantLen == 0 {
		return
	}
	got := charLen.Int64
	if got == 0 {
		got = dataLen.Int64 // RAW and BLOB have no character length
	}
	if got != int64(wantLen) {
		t.Errorf("%s.%s has length %d, want %d", table, col, got, wantLen)
	}
}

func firstLine2(s string) string {
	if i := strings.IndexByte(s, '\n'); i >= 0 {
		return strings.TrimSpace(s[:i])
	}
	return strings.TrimSpace(s)
}
