// Package codegen emits Go from the schema IR.
//
// Output is byte-deterministic across runs and machines: `raorm verify` fails
// CI on a plain diff, so any nondeterminism here would show up as spurious
// churn in every pull request.
package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strings"

	"github.com/gsoultan/raorm/schema"
)

// Options control emission.
type Options struct {
	Package string // package name for the generated file
	Import  string // module path of the runtime, e.g. "github.com/gsoultan/raorm"
	Table   string // which table to emit
	OrderBy string // ORDER BY clause; defaults to the primary key
}

// File renders one table's package.
func File(s *schema.Schema, o Options) ([]byte, error) {
	t := s.Table(o.Table)
	if t == nil {
		return nil, fmt.Errorf("codegen: no table %q", o.Table)
	}
	cols := filterable(t)
	if len(cols) > 15 {
		// Four bits of op per column must fit in a 64-bit shape.
		cols = cols[:15]
	}

	g := &gen{s: s, t: t, o: o, cols: cols}
	g.header()
	g.rowType()
	g.opConstants()
	g.treeQuery()
	g.predType()
	g.colHandles()
	g.treePreds()
	g.chained()
	g.compile()
	g.scanner()
	g.treeBind()
	g.terminals()

	src, err := format.Source(g.buf.Bytes())
	if err != nil {
		return g.buf.Bytes(), fmt.Errorf("codegen: generated code does not parse: %w", err)
	}
	return src, nil
}

type gen struct {
	buf  bytes.Buffer
	s    *schema.Schema
	t    *schema.Table
	o    Options
	cols []colInfo
}

// colInfo is a filterable column with everything the emitters need, resolved
// once so no pass re-derives it.
type colInfo struct {
	col    *schema.Column
	kind   kind
	goBase string
}

func (c colInfo) Name() string { return c.col.Name }

func (g *gen) p(format string, a ...any) {
	fmt.Fprintf(&g.buf, format, a...)
	g.buf.WriteByte('\n')
}

// filterable returns the columns a query may filter on, in table order so the
// output is stable.
func filterable(t *schema.Table) []colInfo {
	var out []colInfo
	for _, c := range t.Columns {
		k := goKind(c)
		if k == kindUnsupported {
			continue
		}
		out = append(out, colInfo{col: c, kind: k, goBase: baseGoType(c)})
	}
	return out
}

func (g *gen) header() {
	g.p("// Code generated by raorm. DO NOT EDIT.")
	g.p("// source: table %s", g.t.Name)
	g.p("")
	g.p("package %s", g.o.Package)
	g.p("")
	g.p("import (")
	g.p("\t%q", "context")
	g.p("\t%q", "errors")
	g.p("\t%q", "time")
	g.p("")
	g.p("\t%q", g.o.Import+"/runtime")
	g.p(")")
	g.p("")
	g.p("var _ = time.Time{}")
	g.p("")
}

func (g *gen) rowType() {
	g.p("// Row is what a full read returns: the model struct with relations")
	g.p("// replaced by their scalar foreign keys and *T rewritten to Null[T].")
	g.p("type Row struct {")
	for _, c := range g.t.Columns {
		k := goKind(c)
		if k == kindUnsupported {
			continue
		}
		g.p("\t%s %s", exportName(c.Name), goType(c))
	}
	g.p("}")
	g.p("")
}

// Operators, in a fixed order so the op nibble is stable across runs.
var ops = []struct {
	name string // method suffix
	frag string // SQL, with the column substituted
	args int
}{
	{"Eq", "%s = $", 1},
	{"NotEq", "%s <> $", 1},
	{"Gt", "%s > $", 1},
	{"Gte", "%s >= $", 1},
	{"Lt", "%s < $", 1},
	{"Lte", "%s <= $", 1},
	{"Like", "%s LIKE $", 1},
	{"In", "%s = ANY($", 1},
	{"IsNull", "%s IS NULL", 0},
	{"IsNotNull", "%s IS NOT NULL", 0},
}

const opNone = 0 // nibble 0 means "no predicate on this column"

func (g *gen) opConstants() {
	g.p("// Operator ids. Argument-taking operators are numbered first, so the")
	g.p("// bind loop tests `op-1 < opsWithArg` with one unsigned compare.")
	g.p("const (")
	for i, op := range ops {
		g.p("\top%s runtime.Op = %d", op.name, i+1)
	}
	g.p(")")
	g.p("")
	g.p("const nCols = %d", len(g.cols))
	g.p("")
}

func (g *gen) chained() {
	g.p("// Chained predicate sugar. Identical to Where(Col.Op(v)).")
	for _, c := range g.cols {
		for _, op := range ops {
			if !opApplies(op.name, c.kind, c.col) {
				continue
			}
			m := exportName(c.Name()) + op.name
			h := exportName(c.Name())
			switch {
			case op.name == "In":
				if predArraySlot(c) == "" {
					continue
				}
				g.p("func (q Query) %s(v ...%s) Query { return q.Where(%s.In(v...)) }", m, c.goBase, h)
			case op.args == 0:
				g.p("func (q Query) %s() Query { return q.Where(%s.%s()) }", m, h, op.name)
			default:
				g.p("func (q Query) %s(v %s) Query { return q.Where(%s.%s(v)) }", m, c.goBase, h, op.name)
			}
		}
	}
	g.p("")
}

func (g *gen) compile() {
	g.p("const selectPrefix = `SELECT %s FROM %s`", strings.Join(quotedCols(g.t), ", "), quote(g.t.Name))
	ob := g.o.OrderBy
	if ob == "" {
		ob = orderBy(g.t)
	}
	g.p("const orderSuffix = ` ORDER BY %s LIMIT $`", ob)
	g.p("const countPrefix = `SELECT count(*) FROM %s`", quote(g.t.Name))
	g.p("")
	g.p("// fragTable is every predicate this table can produce, lowered at build")
	g.p("// time. Runtime splices; it never formats.")
	g.p("var fragTable = [nCols][%d]runtime.Frag{", len(ops)+1)
	for _, c := range g.cols {
		g.p("\t{ // %s", c.Name())
		g.p("\t\t{}, // opNone")
		for _, op := range ops {
			if !opApplies(op.name, c.kind, c.col) {
				g.p("\t\t{},")
				continue
			}
			g.p("\t\t{A: %q, B: %q},", fmt.Sprintf(op.frag, quote(c.Name())), fragTail(op.name))
		}
		g.p("\t},")
	}
	g.p("}")
	g.p("")
	g.p("func fragOf(op, col uint32) runtime.Frag {")
	g.p("\tif col >= nCols || int(op) >= len(fragTable[0]) {")
	g.p("\t\treturn runtime.Frag{}")
	g.p("\t}")
	g.p("\treturn fragTable[col][op]")
	g.p("}")
	g.p("")
	g.p("var (")
	g.p("\tcache      = runtime.NewTreeCache()")
	g.p("\tcountCache = runtime.NewTreeCache()")
	g.p(")")
	g.p("")
	g.p("// Shapes reports how many distinct query structures have compiled.")
	g.p("// `raorm lint` uses it to catch a builder minting a statement per request.")
	g.p("func Shapes() int { return cache.Shapes() }")
	g.p("")
	g.p("func stmtFor(toks []runtime.Tok) *runtime.Stmt {")
	g.p("\tif st := cache.Get(toks); st != nil {")
	g.p("\t\treturn st")
	g.p("\t}")
	g.p("\treturn cache.Put(toks, runtime.SpliceTree(selectPrefix, toks, fragOf, orderSuffix, 1))")
	g.p("}")
	g.p("")
	g.p("func countStmtFor(toks []runtime.Tok) *runtime.Stmt {")
	g.p("\tif st := countCache.Get(toks); st != nil {")
	g.p("\t\treturn st")
	g.p("\t}")
	g.p("\treturn countCache.Put(toks, runtime.SpliceTree(countPrefix, toks, fragOf, \"\", 0))")
	g.p("}")
	g.p("")
	g.p("// Shape is a fingerprint of this query's structure — equal shapes share a")
	g.p("// compiled statement. Values do not contribute, which is the point.")
	g.p("func (q Query) Shape() uint64 {")
	g.p("\tvar buf [%d]runtime.Tok", maxToks+1)
	g.p("\treturn runtime.HashToks(q.stream(&buf))")
	g.p("}")
	g.p("")
	g.p("// SQL returns the compiled text for this query's structure.")
	g.p("func (q Query) SQL() string {")
	g.p("\tvar buf [%d]runtime.Tok", maxToks+1)
	g.p("\treturn stmtFor(q.stream(&buf)).SQL")
	g.p("}")
	g.p("")
}

func (g *gen) scanner() {
	g.p("// scan decodes one row straight from the wire. No reflect, no `any`, no")
	g.p("// driver.Value: the generator knows every column's type already.")
	g.p("func scan(rv [][]byte, r *Row, sl *runtime.Slab) {")
	i := 0
	for _, c := range g.t.Columns {
		if goKind(c) == kindUnsupported {
			continue
		}
		g.p("\t%s", decodeExpr(c, i))
		i++
	}
	g.p("}")
	g.p("")
}

// fragTail closes a fragment that opened a bracket. Only ANY does.
func fragTail(op string) string {
	if op == "In" {
		return ")"
	}
	return ""
}

// argOps counts the operators that take a bound value. They must be numbered
// before the argument-less ones for the range check in bind to be valid.
func argOps() int {
	n := 0
	for _, op := range ops {
		if op.args == 0 {
			break
		}
		n++
	}
	return n
}

func (g *gen) terminals() {
	g.p("// All runs the query and decodes every row.")
	g.p("func (q Query) All(ctx context.Context, ex runtime.Executor, dst []Row) ([]Row, error) {")
	g.p("\tvar sl runtime.Slab")
	g.p("\treturn q.AllInto(ctx, ex, dst, &sl)")
	g.p("}")
	g.p("")
	g.p("// AllInto lets the caller own the string arena.")
	g.p("func (q Query) AllInto(ctx context.Context, ex runtime.Executor, dst []Row, sl *runtime.Slab) ([]Row, error) {")
	g.p("\tif err := q.Err(); err != nil {")
	g.p("\t\treturn dst, err")
	g.p("\t}")
	g.p("\tvar buf [%d]runtime.Tok", maxToks+1)
	g.p("\tst := stmtFor(q.stream(&buf))")
	g.p("\tsl.Reserve(st.SlabHint())")
	g.p("\tb := binders.Get()")
	g.p("\tdefer binders.Put(b)")
	g.p("")
	g.p("\trows, err := ex.Query(ctx, st.SQL, q.bind(b))")
	g.p("\tif err != nil {")
	g.p("\t\treturn dst, err")
	g.p("\t}")
	g.p("\tdefer rows.Close()")
	g.p("\tfor rows.Next() {")
	g.p("\t\tdst = append(dst, Row{})")
	g.p("\t\tscan(rows.RawValues(), &dst[len(dst)-1], sl)")
	g.p("\t}")
	g.p("\tst.ObserveSlab(sl.Size())")
	g.p("\treturn dst, rows.Err()")
	g.p("}")
	g.p("")
	g.p("// One returns the first row, if any.")
	g.p("func (q Query) One(ctx context.Context, ex runtime.Executor) (Row, bool, error) {")
	g.p("\tvar sl runtime.Slab")
	g.p("\tvar buf [1]Row")
	g.p("\tout, err := q.Limit(1).AllInto(ctx, ex, buf[:0], &sl)")
	g.p("\tif err != nil || len(out) == 0 {")
	g.p("\t\treturn Row{}, false, err")
	g.p("\t}")
	g.p("\treturn out[0], true, nil")
	g.p("}")
	g.p("")
	g.p("// Count ignores Limit: counting a truncated set is a bug, not a feature.")
	g.p("func (q Query) Count(ctx context.Context, ex runtime.Executor) (int64, error) {")
	g.p("\tif err := q.Err(); err != nil {")
	g.p("\t\treturn 0, err")
	g.p("\t}")
	g.p("\tvar buf [%d]runtime.Tok", maxToks+1)
	g.p("\tst := countStmtFor(q.stream(&buf))")
	g.p("\tb := binders.Get()")
	g.p("\tdefer binders.Put(b)")
	g.p("\targs := q.bind(b)")
	g.p("\trows, err := ex.Query(ctx, st.SQL, args[:len(args)-1]) // drop the limit")
	g.p("\tif err != nil {")
	g.p("\t\treturn 0, err")
	g.p("\t}")
	g.p("\tdefer rows.Close()")
	g.p("\tvar n int64")
	g.p("\tif rows.Next() {")
	g.p("\t\tn = runtime.Int8(rows.RawValues()[0])")
	g.p("\t}")
	g.p("\treturn n, rows.Err()")
	g.p("}")
	g.p("")
	g.p("// Exists is One with the row discarded.")
	g.p("func (q Query) Exists(ctx context.Context, ex runtime.Executor) (bool, error) {")
	g.p("\t_, ok, err := q.Limit(1).One(ctx, ex)")
	g.p("\treturn ok, err")
	g.p("}")
	g.p("")
	g.p("// Prepare resolves the structure and binds arguments without executing.")
	g.p("func (q Query) Prepare(b *Binder) (string, []any) {")
	g.p("\tvar buf [%d]runtime.Tok", maxToks+1)
	g.p("\treturn stmtFor(q.stream(&buf)).SQL, q.bind(b)")
	g.p("}")
	g.p("")
}

// ---- helpers ----

func quote(s string) string { return `"` + s + `"` }

func quotedCols(t *schema.Table) []string {
	var out []string
	for _, c := range t.Columns {
		if goKind(c) != kindUnsupported {
			out = append(out, quote(c.Name))
		}
	}
	return out
}

func orderBy(t *schema.Table) string {
	if len(t.PrimaryKey) > 0 {
		parts := make([]string, len(t.PrimaryKey))
		for i, k := range t.PrimaryKey {
			parts[i] = quote(k)
		}
		return strings.Join(parts, ", ")
	}
	return quote(t.Columns[0].Name)
}

func exportName(col string) string {
	parts := strings.Split(col, "_")
	for i, p := range parts {
		switch p {
		case "id":
			parts[i] = "ID"
		case "url", "uri", "ip", "api":
			parts[i] = strings.ToUpper(p)
		default:
			if p != "" {
				parts[i] = strings.ToUpper(p[:1]) + p[1:]
			}
		}
	}
	return strings.Join(parts, "")
}

var _ = sort.Strings
