// Package codegen emits Go from the schema IR.
//
// Output is byte-deterministic across runs and machines: `raorm verify` fails
// CI on a plain diff, so any nondeterminism here would show up as spurious
// churn in every pull request.
package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strings"

	"github.com/gsoultan/raorm/compile/pgsql"
	"github.com/gsoultan/raorm/runtime"
	"github.com/gsoultan/raorm/schema"
)

// Options control emission.
type Options struct {
	Package string // package name for the generated file
	Import  string // module path of the runtime, e.g. "github.com/gsoultan/raorm"
	Table   string // which table to emit

	// DefaultOrder is the ordering a query with no Order() gets; empty means
	// the primary key.
	//
	// Structured, not a raw SQL string: ordering is chosen per query now, so
	// the terms have to become tokens, and a string cannot be one. A column
	// that is not filterable is a generation error rather than SQL that fails
	// on first use.
	DefaultOrder []OrderTerm
}

// OrderTerm is one default ordering term.
type OrderTerm struct {
	Column string
	Desc   bool
}

// File renders one table's package.
func File(s *schema.Schema, o Options) ([]byte, error) {
	t := s.Table(o.Table)
	if t == nil {
		return nil, fmt.Errorf("codegen: no table %q", o.Table)
	}
	// The old cap here was fifteen columns, because four bits of operator per
	// column had to fit in a 64-bit shape. The tree IR replaced that mask with
	// a token stream months ago and the cap outlived it, silently generating
	// no predicates at all for a sixteenth column. The real limit is the width
	// of Tok's column field, and exceeding it is an error.
	cols := filterable(t)
	if len(cols) > runtime.MaxCols {
		return nil, fmt.Errorf(
			"codegen: table %s has %d filterable columns; the token column field holds %d — "+
				"split the table, or narrow it with a projection",
			t.Name, len(cols), runtime.MaxCols)
	}

	g := &gen{s: s, t: t, o: o, cols: cols}
	g.header()
	g.rowType()
	g.opConstants()
	g.treeQuery()
	g.predType()
	g.colHandles()
	g.treePreds()
	g.chained()
	g.compile()
	g.scanner()
	g.treeBind()
	g.terminals()
	g.writes()

	if g.err != nil {
		return nil, g.err
	}

	src, err := format.Source(g.buf.Bytes())
	if err != nil {
		return g.buf.Bytes(), fmt.Errorf("codegen: generated code does not parse: %w", err)
	}
	return src, nil
}

type gen struct {
	buf  bytes.Buffer
	s    *schema.Schema
	t    *schema.Table
	o    Options
	cols []colInfo

	// err is the first construct the target cannot express. Emitters set it
	// and return; File reports it instead of writing a file that is quietly
	// missing a predicate. Silence is not an option AGENTS.md allows.
	err error
}

// colInfo is a filterable column with everything the emitters need, resolved
// once so no pass re-derives it.
type colInfo struct {
	col    *schema.Column
	kind   kind
	goBase string
}

func (c colInfo) Name() string { return c.col.Name }

func (g *gen) p(format string, a ...any) {
	fmt.Fprintf(&g.buf, format, a...)
	g.buf.WriteByte('\n')
}

// filterable returns the columns a query may filter on, in table order so the
// output is stable.
func filterable(t *schema.Table) []colInfo {
	var out []colInfo
	for _, c := range t.Columns {
		k := goKind(c)
		if k == kindUnsupported {
			continue
		}
		out = append(out, colInfo{col: c, kind: k, goBase: baseGoType(c)})
	}
	return out
}

func (g *gen) header() {
	g.p("// Code generated by raorm. DO NOT EDIT.")
	g.p("// source: table %s", g.t.Name)
	g.p("")
	g.p("package %s", g.o.Package)
	g.p("")
	g.p("import (")
	g.p("\t%q", "context")
	g.p("\t%q", "errors")
	g.p("\t%q", "time")
	g.p("")
	g.p("\t%q", g.o.Import+"/runtime")
	g.p(")")
	g.p("")
	g.p("var _ = time.Time{}")
	g.p("")
}

func (g *gen) rowType() {
	g.p("// Row is what a full read returns: the model struct with relations")
	g.p("// replaced by their scalar foreign keys and *T rewritten to Null[T].")
	g.p("type Row struct {")
	for _, c := range g.t.Columns {
		k := goKind(c)
		if k == kindUnsupported {
			continue
		}
		g.p("\t%s %s", exportName(c.Name), goType(c))
	}
	g.p("}")
	g.p("")
}

// Operators, in a fixed order so the op nibble is stable across runs.
// ops is the operator set as it appears in the *Go* API: the method suffix and
// whether it binds a value. The SQL each one lowers to belongs to the back end
// in compile/, not here — see pgsql.Frag.
//
// Argument-taking operators must come first: bind tests `op-1 < opsWithArg`
// with a single unsigned compare and that range check is only valid if the
// argument-less operators are last.
var ops = []struct {
	name string // method suffix
	args int
}{
	{"Eq", 1},
	{"NotEq", 1},
	{"Gt", 1},
	{"Gte", 1},
	{"Lt", 1},
	{"Lte", 1},
	{"Like", 1},
	{"In", 1},
	{"IsNull", 0},
	{"IsNotNull", 0},
}

const opNone = 0 // nibble 0 means "no predicate on this column"

func (g *gen) opConstants() {
	g.p("// Operator ids. Argument-taking operators are numbered first, so the")
	g.p("// bind loop tests `op-1 < opsWithArg` with one unsigned compare.")
	g.p("const (")
	for i, op := range ops {
		g.p("\top%s runtime.Op = %d", op.name, i+1)
	}
	g.p(")")
	g.p("")
	g.p("const nCols = %d", len(g.cols))
	g.p("")
}

func (g *gen) chained() {
	g.p("// Chained predicate sugar. Identical to Where(Col.Op(v)).")
	for _, c := range g.cols {
		for _, op := range ops {
			if !opApplies(op.name, c.kind, c.col) {
				continue
			}
			m := exportName(c.Name()) + op.name
			h := exportName(c.Name())
			switch {
			case op.name == "In":
				if predArraySlot(c) == "" {
					continue
				}
				g.p("func (q Query) %s(v ...%s) Query { return q.Where(%s.In(v...)) }", m, c.goBase, h)
			case op.args == 0:
				g.p("func (q Query) %s() Query { return q.Where(%s.%s()) }", m, h, op.name)
			default:
				g.p("func (q Query) %s(v %s) Query { return q.Where(%s.%s(v)) }", m, c.goBase, h, op.name)
			}
		}
	}
	g.p("")
}

func (g *gen) compile() {
	g.p("const selectPrefix = `%s`", pgsql.SelectPrefix(g.t.Name, readableCols(g.t)))
	g.p("const countPrefix = `%s`", pgsql.CountPrefix(g.t.Name))
	g.p("const limitSuffix = `%s`", pgsql.LimitOffsetSuffix(false))
	g.p("const limitOffsetSuffix = `%s`", pgsql.LimitOffsetSuffix(true))
	g.p("// orderTable is every ordering this table can express, lowered at build")
	g.p("// time. ORDER BY is chosen per query, so it cannot be a constant — but it")
	g.p("// still must not be built from strings at run time.")
	g.p("var orderTable = [nCols][%d]string{", pgsql.NDirections)
	for _, c := range g.cols {
		g.p("\t{ // %s", c.Name())
		for d := 0; d < pgsql.NDirections; d++ {
			g.p("\t\t%q,", pgsql.OrderTerm(d, pgsql.Ident(c.Name())))
		}
		g.p("\t},")
	}
	g.p("}")
	g.p("")
	g.p("// identTable is each column's bare quoted name, for the left side of a")
	g.p("// row comparison.")
	g.p("var identTable = [nCols]string{")
	for _, c := range g.cols {
		g.p("\t%q,", pgsql.Ident(c.Name()))
	}
	g.p("}")
	g.p("")
	g.p("var lowering = runtime.Lowering{")
	g.p("\tFrag:  fragOf,")
	g.p("\tOrder: orderOf,")
	g.p("\tOB:    runtime.Order{Lead: %q, Sep: %q},", pgsql.OrderLead, pgsql.OrderSep)
	g.p("\tIdent: func(col uint32) string {")
	g.p("\t\tif col >= nCols {")
	g.p("\t\t\treturn \"\"")
	g.p("\t\t}")
	g.p("\t\treturn identTable[col]")
	g.p("\t},")
	g.p("\tRowCmp: func(op uint32) string {")
	g.p("\t\tif op == runtime.CmpLt {")
	g.p("\t\t\treturn %q", pgsql.RowCmpOp(1))
	g.p("\t\t}")
	g.p("\t\treturn %q", pgsql.RowCmpOp(0))
	g.p("\t},")
	g.p("\tTupleOpen:  %q,", pgsql.TupleOpen)
	g.p("\tTupleSep:   %q,", pgsql.TupleSep)
	g.p("\tTupleClose: %q,", pgsql.TupleClose)
	g.p("}")
	g.p("")
	g.p("func orderOf(dir, col uint32) string {")
	g.p("\tif col >= nCols || int(dir) >= len(orderTable[0]) {")
	g.p("\t\treturn \"\"")
	g.p("\t}")
	g.p("\treturn orderTable[col][dir]")
	g.p("}")
	g.p("")
	g.p("// fragTable is every predicate this table can produce, lowered at build")
	g.p("// time. Runtime splices; it never formats.")
	g.p("var fragTable = [nCols][%d]runtime.Frag{", len(ops)+1)
	for _, c := range g.cols {
		g.p("\t{ // %s", c.Name())
		g.p("\t\t{}, // opNone")
		for _, op := range ops {
			if !opApplies(op.name, c.kind, c.col) {
				g.p("\t\t{},")
				continue
			}
			a, b, ok := pgsql.Frag(op.name, pgsql.Ident(c.Name()))
			if !ok {
				g.err = fmt.Errorf("codegen: table %s column %s: target postgres has no lowering for operator %s",
					g.t.Name, c.Name(), op.name)
				return
			}
			g.p("\t\t{A: %q, B: %q},", a, b)
		}
		g.p("\t},")
	}
	g.p("}")
	g.p("")
	g.p("func fragOf(op, col uint32) runtime.Frag {")
	g.p("\tif col >= nCols || int(op) >= len(fragTable[0]) {")
	g.p("\t\treturn runtime.Frag{}")
	g.p("\t}")
	g.p("\treturn fragTable[col][op]")
	g.p("}")
	g.p("")
	g.p("// defaultOrder is what a query with no Order() uses.")
	g.p("//")
	g.p("// It is never empty. A read without ORDER BY has no defined order, so")
	g.p("// paging one is a bug waiting for a plan change to expose it — and the")
	g.p("// primary key is the cheapest total order available.")
	g.p("var defaultOrder = [%d]runtime.Tok{", len(g.defaultOrder()))
	for _, t := range g.defaultOrder() {
		g.p("\truntime.MakeOrder(%s, %d), // %s", t.dirConst, t.col, t.comment)
	}
	g.p("}")
	g.p("")
	g.p("var (")
	g.p("\tcache      = runtime.NewTreeCache()")
	g.p("\toffsetCache = runtime.NewTreeCache()")
	g.p("\tcountCache = runtime.NewTreeCache()")
	g.p(")")
	g.p("")
	g.p("// Shapes reports how many distinct query structures have compiled.")
	g.p("// `raorm lint` uses it to catch a builder minting a statement per request.")
	g.p("func Shapes() int { return cache.Shapes() }")
	g.p("")
	g.p("// stmtFor compiles a read. LIMIT and LIMIT/OFFSET are different")
	g.p("// statements with different placeholder counts, so they get different")
	g.p("// caches rather than a sentinel token muddying the key.")
	g.p("func stmtFor(toks []runtime.Tok, withOffset bool) *runtime.Stmt {")
	g.p("\tc, suffix := cache, limitSuffix")
	g.p("\tif withOffset {")
	g.p("\t\tc, suffix = offsetCache, limitOffsetSuffix")
	g.p("\t}")
	g.p("\tif st := c.Get(toks); st != nil {")
	g.p("\t\treturn st")
	g.p("\t}")
	g.p("\treturn c.Put(toks, runtime.SpliceTree(selectPrefix, toks, lowering, suffix))")
	g.p("}")
	g.p("")
	g.p("func countStmtFor(toks []runtime.Tok) *runtime.Stmt {")
	g.p("\tif st := countCache.Get(toks); st != nil {")
	g.p("\t\treturn st")
	g.p("\t}")
	g.p("\t// A count ignores ordering as well as LIMIT: ordering a scalar is")
	g.p("\t// wasted work, and the token stream is trimmed before it gets here.")
	g.p("\treturn countCache.Put(toks, runtime.SpliceTree(countPrefix, toks, lowering, \"\"))")
	g.p("}")
	g.p("")
	g.p("// Shape is a fingerprint of this query's structure — equal shapes share a")
	g.p("// compiled statement. Values do not contribute, which is the point.")
	g.p("func (q Query) Shape() uint64 {")
	g.p("\tvar buf [%d]runtime.Tok", maxToks+maxOrder+1)
	g.p("\treturn runtime.HashToks(q.stream(&buf))")
	g.p("}")
	g.p("")
	g.p("// SQL returns the compiled text for this query's structure.")
	g.p("func (q Query) SQL() string {")
	g.p("\tvar buf [%d]runtime.Tok", maxToks+maxOrder+1)
	g.p("\treturn stmtFor(q.stream(&buf), q.offset > 0).SQL")
	g.p("}")
	g.p("")
}

func (g *gen) scanner() {
	g.p("// scan decodes one row straight from the wire. No reflect, no `any`, no")
	g.p("// driver.Value: the generator knows every column's type already.")
	g.p("func scan(rv [][]byte, r *Row, sl *runtime.Slab) {")
	i := 0
	for _, c := range g.t.Columns {
		if goKind(c) == kindUnsupported {
			continue
		}
		g.p("\t%s", decodeExpr(c, i))
		i++
	}
	g.p("}")
	g.p("")
}

// argOps counts the operators that take a bound value. They must be numbered
// before the argument-less ones for the range check in bind to be valid.
func argOps() int {
	n := 0
	for _, op := range ops {
		if op.args == 0 {
			break
		}
		n++
	}
	return n
}

func (g *gen) terminals() {
	g.p("// All runs the query and decodes every row.")
	g.p("func (q Query) All(ctx context.Context, ex runtime.Executor, dst []Row) ([]Row, error) {")
	g.p("\tvar sl runtime.Slab")
	g.p("\treturn q.AllInto(ctx, ex, dst, &sl)")
	g.p("}")
	g.p("")
	g.p("// AllInto lets the caller own the string arena.")
	g.p("func (q Query) AllInto(ctx context.Context, ex runtime.Executor, dst []Row, sl *runtime.Slab) ([]Row, error) {")
	g.p("\tif err := q.Err(); err != nil {")
	g.p("\t\treturn dst, err")
	g.p("\t}")
	g.p("\tvar buf [%d]runtime.Tok", maxToks+maxOrder+1)
	g.p("\tst := stmtFor(q.stream(&buf), q.offset > 0)")
	g.p("\tsl.Reserve(st.SlabHint())")
	g.p("\tb := binders.Get()")
	g.p("\tdefer binders.Put(b)")
	g.p("")
	g.p("\trows, err := ex.Query(ctx, st.SQL, q.bind(b))")
	g.p("\tif err != nil {")
	g.p("\t\treturn dst, err")
	g.p("\t}")
	g.p("\tdefer rows.Close()")
	g.p("\tfor rows.Next() {")
	g.p("\t\tdst = append(dst, Row{})")
	g.p("\t\tscan(rows.RawValues(), &dst[len(dst)-1], sl)")
	g.p("\t}")
	g.p("\tst.ObserveSlab(sl.Size())")
	g.p("\treturn dst, rows.Err()")
	g.p("}")
	g.p("")
	g.p("// One returns the first row, if any.")
	g.p("func (q Query) One(ctx context.Context, ex runtime.Executor) (Row, bool, error) {")
	g.p("\tvar sl runtime.Slab")
	g.p("\tvar buf [1]Row")
	g.p("\tout, err := q.Limit(1).AllInto(ctx, ex, buf[:0], &sl)")
	g.p("\tif err != nil || len(out) == 0 {")
	g.p("\t\treturn Row{}, false, err")
	g.p("\t}")
	g.p("\treturn out[0], true, nil")
	g.p("}")
	g.p("")
	g.p("// Count ignores Limit: counting a truncated set is a bug, not a feature.")
	g.p("func (q Query) Count(ctx context.Context, ex runtime.Executor) (int64, error) {")
	g.p("\tif err := q.Err(); err != nil {")
	g.p("\t\treturn 0, err")
	g.p("\t}")
	g.p("\tvar buf [%d]runtime.Tok", maxToks+maxOrder+1)
	g.p("\tst := countStmtFor(q.preds(&buf))")
	g.p("\tb := binders.Get()")
	g.p("\tdefer binders.Put(b)")
	g.p("\targs := q.bind(b)")
	g.p("\trows, err := ex.Query(ctx, st.SQL, args[:len(args)-1]) // drop the limit")
	g.p("\tif err != nil {")
	g.p("\t\treturn 0, err")
	g.p("\t}")
	g.p("\tdefer rows.Close()")
	g.p("\tvar n int64")
	g.p("\tif rows.Next() {")
	g.p("\t\tn = runtime.Int8(rows.RawValues()[0])")
	g.p("\t}")
	g.p("\treturn n, rows.Err()")
	g.p("}")
	g.p("")
	g.p("// Exists is One with the row discarded.")
	g.p("func (q Query) Exists(ctx context.Context, ex runtime.Executor) (bool, error) {")
	g.p("\t_, ok, err := q.Limit(1).One(ctx, ex)")
	g.p("\treturn ok, err")
	g.p("}")
	g.p("")
	g.p("// Prepare resolves the structure and binds arguments without executing.")
	g.p("func (q Query) Prepare(b *Binder) (string, []any) {")
	g.p("\tvar buf [%d]runtime.Tok", maxToks+maxOrder+1)
	g.p("\treturn stmtFor(q.stream(&buf), q.offset > 0).SQL, q.bind(b)")
	g.p("}")
	g.p("")
}

// ---- helpers ----

// readableCols is every column a read projects, in table order. Unsupported
// types are omitted rather than guessed at.
func readableCols(t *schema.Table) []string {
	var out []string
	for _, c := range t.Columns {
		if goKind(c) != kindUnsupported {
			out = append(out, c.Name)
		}
	}
	return out
}

func exportName(col string) string {
	parts := strings.Split(col, "_")
	for i, p := range parts {
		switch p {
		case "id":
			parts[i] = "ID"
		case "url", "uri", "ip", "api":
			parts[i] = strings.ToUpper(p)
		default:
			if p != "" {
				parts[i] = strings.ToUpper(p[:1]) + p[1:]
			}
		}
	}
	return strings.Join(parts, "")
}

var _ = sort.Strings

// orderTerm is one default ORDER BY term, resolved to the ids generated code
// uses.
type orderTerm struct {
	col      int
	dirConst string
	comment  string
}

// defaultOrder is the ordering a query with no Order() gets.
//
// It is never empty: a read without ORDER BY has no defined order, so paging
// one is a bug waiting for a plan change to expose it. The primary key is the
// cheapest total order available, and Options.DefaultOrder overrides it.
func (g *gen) defaultOrder() []orderTerm {
	if len(g.o.DefaultOrder) > 0 {
		var out []orderTerm
		for _, t := range g.o.DefaultOrder {
			i := g.colIndex(t.Column)
			if i < 0 {
				g.err = fmt.Errorf(
					"codegen: table %s: default order names column %s, which is not filterable",
					g.t.Name, t.Column)
				return []orderTerm{{col: 0, dirConst: "runtime.Asc", comment: "invalid"}}
			}
			out = append(out, orderTerm{col: i, dirConst: dirConst(t.Desc), comment: t.Column})
		}
		return out
	}
	var out []orderTerm
	for _, k := range g.t.PrimaryKey {
		if i := g.colIndex(k); i >= 0 {
			out = append(out, orderTerm{col: i, dirConst: "runtime.Asc", comment: k})
		}
	}
	if len(out) == 0 {
		out = append(out, orderTerm{col: 0, dirConst: "runtime.Asc", comment: g.cols[0].Name()})
	}
	return out
}

func dirConst(desc bool) string {
	if desc {
		return "runtime.Desc"
	}
	return "runtime.Asc"
}

func (g *gen) colIndex(name string) int {
	for i, c := range g.cols {
		if c.Name() == name {
			return i
		}
	}
	return -1
}
