package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strings"

	"github.com/gsoultan/storm/schema"
)

// Model emission: an introspected database rendered back as Go models.
//
// This is the adoption on-ramp. storm is model-first, so a team with an
// existing database needs a model to start from — and hand-writing one for
// forty tables is where adoption stops. `storm import` writes the first draft.
//
// It is a DRAFT and says so. Some things a database knows cannot be inferred
// back into a Go declaration, and the honest move is to list them at the top of
// the file rather than emit a model that silently means something narrower than
// the schema it came from.

// ModelOptions configures model emission.
type ModelOptions struct {
	Package string // package clause; "model" when empty
	Import  string // storm's import path
}

// Model renders a schema as Go model declarations.
func Model(s *schema.Schema, o ModelOptions) ([]byte, error) {
	if o.Package == "" {
		o.Package = "model"
	}
	if o.Import == "" {
		o.Import = "github.com/gsoultan/storm"
	}

	var g gen
	g.dec = decodersFor(DialectPostgres, "")
	unported := unportedFacts(s)

	g.p("// Code generated by `storm import`. EDIT THIS.")
	g.p("//")
	g.p("// It is a first draft of the model behind an existing database, not a")
	g.p("// finished one: a Go declaration cannot express everything a schema knows,")
	g.p("// and the rest has to be added by hand. Nothing below is guessed silently —")
	g.p("// what did not survive the round trip is listed here.")
	if len(unported) == 0 {
		g.p("//")
		g.p("// Nothing was dropped: every construct in this schema is expressible.")
	} else {
		g.p("//")
		g.p("// NOT CARRIED OVER — add these to a Schema method before trusting a diff:")
		for _, u := range unported {
			g.p("//   %s", u)
		}
	}
	g.p("")
	g.p("package %s", o.Package)
	g.p("")

	// Render the bodies FIRST, then read the imports off what was actually
	// written.
	//
	// Every version of this that reasoned about columns instead got it wrong,
	// each time one type along: the original tested only timestamptz, so a
	// `date` column emitted time.Time with no import; the fix that scanned
	// every column's type over-counted, because a table embedding storm.Model
	// emits no timestamp FIELD at all and the file then imported `time`
	// unused. The output is the only thing that knows what the output needs.
	var body gen
	body.dec = g.dec
	for _, e := range s.Enums {
		body.enumType(e)
	}
	tables := make([]*schema.Table, len(s.Tables))
	copy(tables, s.Tables)
	sort.Slice(tables, func(i, j int) bool { return tables[i].Name < tables[j].Name })
	for _, t := range tables {
		body.modelType(s, t)
	}

	rendered := body.buf.String()
	g.p("import (")
	needsTime := strings.Contains(rendered, "time.Time")
	needsNetip := strings.Contains(rendered, "netip.")
	if needsTime {
		g.p("\t%q", "time")
	}
	if needsNetip {
		g.p("\t%q", "net/netip")
	}
	if needsTime || needsNetip {
		g.p("")
	}
	g.p("\t%q", o.Import)
	g.p(")")
	g.p("")
	g.buf.WriteString(rendered)

	g.p("// All is what you pass to storm.Build.")
	g.p("func All() []any {")
	g.p("\treturn []any{")
	for _, t := range tables {
		g.p("\t\t&%s{},", modelName(t))
	}
	g.p("\t}")
	g.p("}")

	src, err := format.Source(g.buf.Bytes())
	if err != nil {
		return g.buf.Bytes(), fmt.Errorf("codegen: imported model does not parse: %w", err)
	}
	return src, nil
}

// unportedFacts lists what an introspected schema knows that a plain Go
// declaration cannot say.
func unportedFacts(s *schema.Schema) []string {
	var out []string
	for _, t := range s.Tables {
		for _, ix := range t.Indexes {
			if _, ok := indexDecl(s, t, ix); !ok {
				out = append(out, fmt.Sprintf("index %s on %s — re-declare with t.Index(...)", ix.Name, t.Name))
			}
		}
		for _, ck := range t.Checks {
			out = append(out, fmt.Sprintf("check %s on %s — re-declare with t.Check(%q)", ck.Name, t.Name, ck.Expr))
		}
		for _, ex := range t.Excludes {
			out = append(out, fmt.Sprintf("exclusion constraint %s on %s — re-declare with t.Exclude(...)", ex.Name, t.Name))
		}
		for _, u := range t.Uniques {
			out = append(out, fmt.Sprintf("unique %s on %s — re-declare with t.Unique(...)", u.Name, t.Name))
		}
	}
	sort.Strings(out)
	return out
}

func (g *gen) enumType(e *schema.Enum) {
	name := exportName(e.Name)
	g.p("// %s is the %s enum.", name, e.Name)
	g.p("type %s string", name)
	g.p("")
	g.p("const (")
	for _, v := range e.Labels {
		g.p("\t%s%s %s = %q", name, exportName(v), name, v)
	}
	g.p(")")
	g.p("")
	g.p("// EnumValues makes %s a storm enum. Constants are not discoverable by", name)
	g.p("// reflection, so the type has to list them.")
	g.p("func (%s) EnumValues() []string {", name)
	g.p("\treturn []string{")
	for _, v := range e.Labels {
		g.p("\t\t%q,", v)
	}
	g.p("\t}")
	g.p("}")
	g.p("")
}

func (g *gen) modelType(s *schema.Schema, t *schema.Table) {
	name := modelName(t)
	fkBy := map[string]*schema.ForeignKey{}
	for _, fk := range t.ForeignKeys {
		if len(fk.Columns) == 1 {
			fkBy[fk.Columns[0]] = fk
		}
	}

	g.p("// %s is table %s.", name, t.Name)
	if t.Name != tableNameFor(name) {
		g.p("//")
		g.p("// The table name is not what storm would derive from the type, so it is")
		g.p("// set explicitly in Schema — otherwise the first diff would rename it.")
	}
	g.p("type %s struct {", name)

	// The storm.Model triple is embedded rather than restated. A hand-written
	// model embeds it, so a draft that spells out id/created_at/updated_at
	// reads as something a human did not write — and the first thing anyone
	// would do is collapse it.
	embedded := embedsModel(t)
	if embedded {
		g.p("\tstorm.Model")
		g.p("")
	}

	var schemaLines []string
	for _, c := range t.Columns {
		if embedded && isModelColumn(c) {
			continue
		}
		if fk := fkBy[c.Name]; fk != nil {
			target := s.Table(fk.RefTable)
			if target != nil {
				field := relationFieldName(c.Name)
				if c.NotNull {
					g.p("\t%s %s", field, modelName(target))
				} else {
					g.p("\t%s *%s", field, modelName(target))
				}
				if c := actionConst(fk.OnDelete); c != "" {
					schemaLines = append(schemaLines, fmt.Sprintf(
						"t.Col(&m.%s).OnDelete(storm.%s)", field, c))
				}
				continue
			}
		}
		k := goKind(c)
		if k == kindUnsupported {
			g.p("\t// %s %s — storm has no Go type for this yet; it is omitted rather",
				exportName(c.Name), c.Type.SQL())
			g.p("\t// than guessed, so a diff will want to drop it until you decide.")
			continue
		}
		g.p("\t%s %s", exportName(c.Name), importGoType(c))
		if l := columnFacts(c); l != "" {
			schemaLines = append(schemaLines, fmt.Sprintf("t.Col(&m.%s)%s", exportName(c.Name), l))
		}
	}
	g.p("}")
	g.p("")

	if t.Name != tableNameFor(name) {
		schemaLines = append([]string{fmt.Sprintf("t.Name(%q)", t.Name)}, schemaLines...)
	}
	// Indexes come back as declarations, not as facts the reader has to
	// re-type: an imported schema is usually a real one, and a real one's
	// indexes are where its performance lives.
	for _, ix := range t.Indexes {
		if line, ok := indexDecl(s, t, ix); ok {
			schemaLines = append(schemaLines, line)
		}
	}
	if len(schemaLines) == 0 {
		return
	}
	g.p("func (m *%s) Schema(t *storm.Table) {", name)
	for _, l := range schemaLines {
		g.p("\t%s", l)
	}
	g.p("}")
	g.p("")
}

// indexDecl renders one index as the t.Index(...) declaration that would
// produce it, or reports that it cannot: a key on a column the model omitted
// has no field pointer to name.
// modelFieldName is the struct field a column actually became.
//
// The struct emitter turns a resolvable single-column foreign key into a
// RELATION field — user_id becomes User — and every other place that names a
// field has to make the same choice. It did not: an index over a foreign key
// emitted `t.Index(&m.UserID)` against a struct whose field is `User`. That
// parses and compiles nowhere, and an index on a foreign key is one of the
// most common things in a real schema.
func modelFieldName(s *schema.Schema, t *schema.Table, col string) string {
	for _, fk := range t.ForeignKeys {
		if len(fk.Columns) == 1 && fk.Columns[0] == col && s.Table(fk.RefTable) != nil {
			return relationFieldName(col)
		}
	}
	return exportName(col)
}

func indexDecl(s *schema.Schema, t *schema.Table, ix *schema.Index) (string, bool) {
	keys := make([]string, 0, len(ix.Columns))
	for _, c := range ix.Columns {
		k, ok := indexKeyDecl(s, t, c)
		if !ok {
			return "", false
		}
		keys = append(keys, k)
	}
	var b strings.Builder
	fmt.Fprintf(&b, "t.Index(%s)", strings.Join(keys, ", "))
	if m := ix.Method; m != "" && m != "btree" {
		fmt.Fprintf(&b, ".Using(%s)", methodConst(m))
	}
	if ix.Unique {
		b.WriteString(".Unique()")
	}
	if ix.NullsNotDistinct {
		b.WriteString(".NullsNotDistinct()")
	}
	if len(ix.Include) > 0 {
		inc := make([]string, 0, len(ix.Include))
		for _, col := range ix.Include {
			if t.Column(col) == nil {
				return "", false
			}
			inc = append(inc, "&m."+modelFieldName(s, t, col))
		}
		fmt.Fprintf(&b, ".Include(%s)", strings.Join(inc, ", "))
	}
	for _, p := range ix.With {
		fmt.Fprintf(&b, ".With(%q, %q)", p.Name, p.Value)
	}
	if ix.Where != "" {
		fmt.Fprintf(&b, ".Where(%q)", ix.Where)
	}
	if ix.Invisible {
		b.WriteString(".Invisible()")
	}
	fmt.Fprintf(&b, ".Named(%q)", ix.Name)
	return b.String(), true
}

// indexKeyDecl renders one key with its modifiers composed inside out, the
// way the declaration reads: storm.OpClass(storm.Desc(&m.Email), "…").
func indexKeyDecl(s *schema.Schema, t *schema.Table, c schema.IndexColumn) (string, bool) {
	var k string
	switch {
	case !c.Expr:
		if t.Column(c.Name) == nil {
			return "", false
		}
		k = "&m." + modelFieldName(s, t, c.Name)
	default:
		// An expression names a column somewhere inside it. The common forms
		// are recognised; anything else is rendered over the first column the
		// expression mentions, with %s standing for it.
		col, expr, ok := splitExpr(t, c.Name)
		if !ok {
			return "", false
		}
		switch expr {
		case "lower(%s)":
			k = fmt.Sprintf("storm.Lower(&m.%s)", modelFieldName(s, t, col))
		case "upper(%s)":
			k = fmt.Sprintf("storm.Upper(&m.%s)", modelFieldName(s, t, col))
		default:
			k = fmt.Sprintf("storm.IndexExpr(&m.%s, %q)", modelFieldName(s, t, col), expr)
		}
	}
	if c.Desc {
		k = fmt.Sprintf("storm.Desc(%s)", k)
	}
	if c.NullsLast {
		k = fmt.Sprintf("storm.NullsLast(%s)", k)
	}
	if c.NullsFirst {
		k = fmt.Sprintf("storm.NullsFirst(%s)", k)
	}
	if c.Collate != "" {
		k = fmt.Sprintf("storm.Collate(%s, %q)", k, c.Collate)
	}
	if c.OpClass != "" {
		k = fmt.Sprintf("storm.OpClass(%s, %q)", k, c.OpClass)
	}
	if c.Prefix > 0 {
		k = fmt.Sprintf("storm.Prefix(%s, %d)", k, c.Prefix)
	}
	return k, true
}

// splitExpr finds the column an index expression is over and returns the
// expression with %s in its place. The longest column name is matched first,
// so that created_at is not mistaken for a column called at.
func splitExpr(t *schema.Table, expr string) (col, tmpl string, ok bool) {
	best := ""
	for _, c := range t.Columns {
		if len(c.Name) > len(best) && containsWord(expr, c.Name) {
			best = c.Name
		}
	}
	if best == "" {
		return "", "", false
	}
	return best, strings.Replace(expr, best, "%s", 1), true
}

// containsWord reports whether name appears in expr as a whole identifier.
func containsWord(expr, name string) bool {
	for i := strings.Index(expr, name); i >= 0; {
		before := i == 0 || !identByte(expr[i-1])
		after := i+len(name) == len(expr) || !identByte(expr[i+len(name)])
		if before && after {
			return true
		}
		next := strings.Index(expr[i+1:], name)
		if next < 0 {
			return false
		}
		i += 1 + next
	}
	return false
}

func identByte(b byte) bool {
	return b == '_' || (b >= 'a' && b <= 'z') || (b >= 'A' && b <= 'Z') || (b >= '0' && b <= '9')
}

func methodConst(m string) string {
	switch m {
	case "gin":
		return "storm.GIN"
	case "gist":
		return "storm.GiST"
	case "spgist":
		return "storm.SPGiST"
	case "hash":
		return "storm.Hash"
	case "brin":
		return "storm.BRIN"
	case "fulltext":
		return "storm.FullText"
	}
	return fmt.Sprintf("%q", m)
}

// columnFacts is what the Go type cannot say.
func columnFacts(c *schema.Column) string {
	var b strings.Builder
	if n := c.Type.Size; n > 0 {
		fmt.Fprintf(&b, ".Size(%d)", n)
	}
	if c.Default != "" && !isIdentityDefault(c.Default) {
		fmt.Fprintf(&b, ".Default(%q)", c.Default)
	}
	if c.Version {
		b.WriteString(".Version()")
	}
	if c.Immutable {
		b.WriteString(".Immutable()")
	}
	return b.String()
}

// isIdentityDefault skips defaults storm.Model already supplies, so an imported
// model does not restate them and then diff against itself.
func isIdentityDefault(d string) bool {
	switch strings.ToLower(strings.TrimSpace(d)) {
	case "gen_random_uuid()", "now()", "current_timestamp":
		return true
	}
	return false
}

// importGoType is the Go type for an imported column. Nullable scalars become
// pointers, which is the declaration form — Null[T] is the READ form and is
// generated, not written.
//
// An enum column takes its own named type rather than string: that is what
// makes the generated query API typed, and importing it as a string would
// silently give up the property the model exists to provide.
// modelGoType is baseGoType rendered for a MODEL file rather than for
// generated code.
//
// One type table served two audiences with different imports: generated code
// imports runtime and net/netip, a model imports storm and stdlib. So an
// imported model named runtime.JSON, runtime.Decimal and netip.Prefix — types
// it had no import for — and did not compile. Every one of those has a storm
// alias for exactly this reason; JSON was the one that did not, until now.
func modelGoType(c *schema.Column) string {
	t := baseGoType(c)
	return strings.ReplaceAll(t, "runtime.", "storm.")
}

func importGoType(c *schema.Column) string {
	base := modelGoType(c)
	if c.Type.Enum {
		base = exportName(c.Type.Name)
	}
	// A slice carries its own null: nil is SQL NULL, and an empty non-nil
	// slice is a real empty value — a distinction storm keeps deliberately.
	// Wrapping one in a pointer invents a second way to say nothing, and
	// storm.Build refuses the result. This tested only bytea, so a nullable
	// jsonb imported as *storm.JSON and a nullable text[] as *[]string.
	if c.NotNull || c.Type.Array || goKind(c) == kindBytes || goKind(c) == kindJSONB {
		return base
	}
	return "*" + base
}

// embedsModel reports whether a table carries exactly the storm.Model triple:
// a uuid primary key called id, plus created_at and updated_at.
//
// Conservative on purpose. Embedding when the shapes do not match would change
// what the model means — Model's id defaults to gen_random_uuid() and its
// created_at is immutable — so a near-miss is spelled out in full instead.
func embedsModel(t *schema.Table) bool {
	if len(t.PrimaryKey) != 1 || t.PrimaryKey[0] != "id" {
		return false
	}
	need := map[string]string{
		"id":         schema.TypeUUID,
		"created_at": schema.TypeTimestamptz,
		"updated_at": schema.TypeTimestamptz,
	}
	for _, c := range t.Columns {
		want, ok := need[c.Name]
		if !ok {
			continue
		}
		if c.Type.Name != want || !c.NotNull || c.Type.Array {
			return false
		}
		delete(need, c.Name)
	}
	return len(need) == 0
}

func isModelColumn(c *schema.Column) bool {
	switch c.Name {
	case "id", "created_at", "updated_at":
		return true
	}
	return false
}

func modelName(t *schema.Table) string {
	if t.GoName != "" {
		return t.GoName
	}
	return exportName(singular(t.Name))
}

// relationFieldName turns author_id into Author.
func relationFieldName(col string) string {
	return exportName(strings.TrimSuffix(col, "_id"))
}

// singular is a naive de-pluralisation, used ONLY to propose a type name for an
// imported table. It is allowed to be wrong here in a way it is not allowed to
// be in codegen: this output is a draft a human reads and renames, and the
// table name is pinned explicitly in Schema so a wrong guess cannot rename a
// table.
// singular delegates to schema.Singular — the join table's column names come
// from there, and a second copy here is how the two would name different
// columns.
func singular(s string) string { return schema.Singular(s) }

// tableNameFor mirrors storm's pluralisation, to decide whether the table name
// has to be pinned explicitly.
func tableNameFor(goName string) string {
	s := snakeOf(goName)
	switch {
	case strings.HasSuffix(s, "s"), strings.HasSuffix(s, "x"),
		strings.HasSuffix(s, "z"), strings.HasSuffix(s, "ch"), strings.HasSuffix(s, "sh"):
		return s + "es"
	case strings.HasSuffix(s, "y") && len(s) > 1 && !isVowel(s[len(s)-2]):
		return s[:len(s)-1] + "ies"
	default:
		return s + "s"
	}
}

func isVowel(b byte) bool {
	return b == 'a' || b == 'e' || b == 'i' || b == 'o' || b == 'u'
}

func snakeOf(s string) string {
	var b bytes.Buffer
	for i := 0; i < len(s); i++ {
		c := s[i]
		if c >= 'A' && c <= 'Z' {
			if i > 0 {
				b.WriteByte('_')
			}
			b.WriteByte(c + ('a' - 'A'))
			continue
		}
		b.WriteByte(c)
	}
	return b.String()
}

// actionConst is the Go constant naming a referential action.
//
// An action's VALUE is SQL text — "SET NULL", "NO ACTION" — and this used to
// run it through exportName, the column-name humaniser. That produced
// `storm.SET NULL`: an imported model that does not parse. CASCADE and
// RESTRICT parsed and then failed to compile as undefined identifiers, which
// is the same defect wearing a better disguise, and is why "it parses" was
// never the right check.
//
// The mapping is written out rather than derived because a value that was
// never an identifier cannot be turned into one by capitalising it. An action
// this does not know emits nothing: a missing clause is a diff the adopter can
// see, and a wrong identifier is a build they have to debug.
func actionConst(a schema.Action) string {
	switch a {
	case schema.Cascade:
		return "Cascade"
	case schema.Restrict:
		return "Restrict"
	case schema.SetNull:
		return "SetNull"
	case schema.SetDefault:
		return "SetDefault"
	}
	return "" // NoAction, and anything unrecognised
}
