package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strings"

	"github.com/gsoultan/storm/schema"
)

// Model emission: an introspected database rendered back as Go models.
//
// This is the adoption on-ramp. storm is model-first, so a team with an
// existing database needs a model to start from — and hand-writing one for
// forty tables is where adoption stops. `storm import` writes the first draft.
//
// It is a DRAFT and says so. Some things a database knows cannot be inferred
// back into a Go declaration, and the honest move is to list them at the top of
// the file rather than emit a model that silently means something narrower than
// the schema it came from.

// ModelOptions configures model emission.
type ModelOptions struct {
	Package string // package clause; "model" when empty
	Import  string // storm's import path
}

// Model renders a schema as Go model declarations.
func Model(s *schema.Schema, o ModelOptions) ([]byte, error) {
	if o.Package == "" {
		o.Package = "model"
	}
	if o.Import == "" {
		o.Import = "github.com/gsoultan/storm"
	}

	var g gen
	unported := unportedFacts(s)

	g.p("// Code generated by `storm import`. EDIT THIS.")
	g.p("//")
	g.p("// It is a first draft of the model behind an existing database, not a")
	g.p("// finished one: a Go declaration cannot express everything a schema knows,")
	g.p("// and the rest has to be added by hand. Nothing below is guessed silently —")
	g.p("// what did not survive the round trip is listed here.")
	if len(unported) == 0 {
		g.p("//")
		g.p("// Nothing was dropped: every construct in this schema is expressible.")
	} else {
		g.p("//")
		g.p("// NOT CARRIED OVER — add these to a Schema method before trusting a diff:")
		for _, u := range unported {
			g.p("//   %s", u)
		}
	}
	g.p("")
	g.p("package %s", o.Package)
	g.p("")

	needsTime, needsStorm := false, true
	for _, t := range s.Tables {
		for _, c := range t.Columns {
			if goKind(c) == kindTimestamptz {
				needsTime = true
			}
		}
	}
	g.p("import (")
	if needsTime {
		g.p("\t%q", "time")
		g.p("")
	}
	if needsStorm {
		g.p("\t%q", o.Import)
	}
	g.p(")")
	g.p("")

	for _, e := range s.Enums {
		g.enumType(e)
	}

	tables := make([]*schema.Table, len(s.Tables))
	copy(tables, s.Tables)
	sort.Slice(tables, func(i, j int) bool { return tables[i].Name < tables[j].Name })
	for _, t := range tables {
		g.modelType(s, t)
	}

	g.p("// All is what you pass to storm.Build.")
	g.p("func All() []any {")
	g.p("\treturn []any{")
	for _, t := range tables {
		g.p("\t\t&%s{},", modelName(t))
	}
	g.p("\t}")
	g.p("}")

	src, err := format.Source(g.buf.Bytes())
	if err != nil {
		return g.buf.Bytes(), fmt.Errorf("codegen: imported model does not parse: %w", err)
	}
	return src, nil
}

// unportedFacts lists what an introspected schema knows that a plain Go
// declaration cannot say.
func unportedFacts(s *schema.Schema) []string {
	var out []string
	for _, t := range s.Tables {
		for _, ix := range t.Indexes {
			out = append(out, fmt.Sprintf("index %s on %s — re-declare with t.Index(...)", ix.Name, t.Name))
		}
		for _, ck := range t.Checks {
			out = append(out, fmt.Sprintf("check %s on %s — re-declare with t.Check(%q)", ck.Name, t.Name, ck.Expr))
		}
		for _, ex := range t.Excludes {
			out = append(out, fmt.Sprintf("exclusion constraint %s on %s — re-declare with t.Exclude(...)", ex.Name, t.Name))
		}
		for _, u := range t.Uniques {
			out = append(out, fmt.Sprintf("unique %s on %s — re-declare with t.Unique(...)", u.Name, t.Name))
		}
	}
	sort.Strings(out)
	return out
}

func (g *gen) enumType(e *schema.Enum) {
	name := exportName(e.Name)
	g.p("// %s is the %s enum.", name, e.Name)
	g.p("type %s string", name)
	g.p("")
	g.p("const (")
	for _, v := range e.Labels {
		g.p("\t%s%s %s = %q", name, exportName(v), name, v)
	}
	g.p(")")
	g.p("")
	g.p("// EnumValues makes %s a storm enum. Constants are not discoverable by", name)
	g.p("// reflection, so the type has to list them.")
	g.p("func (%s) EnumValues() []string {", name)
	g.p("\treturn []string{")
	for _, v := range e.Labels {
		g.p("\t\t%q,", v)
	}
	g.p("\t}")
	g.p("}")
	g.p("")
}

func (g *gen) modelType(s *schema.Schema, t *schema.Table) {
	name := modelName(t)
	fkBy := map[string]*schema.ForeignKey{}
	for _, fk := range t.ForeignKeys {
		if len(fk.Columns) == 1 {
			fkBy[fk.Columns[0]] = fk
		}
	}

	g.p("// %s is table %s.", name, t.Name)
	if t.Name != tableNameFor(name) {
		g.p("//")
		g.p("// The table name is not what storm would derive from the type, so it is")
		g.p("// set explicitly in Schema — otherwise the first diff would rename it.")
	}
	g.p("type %s struct {", name)

	// The storm.Model triple is embedded rather than restated. A hand-written
	// model embeds it, so a draft that spells out id/created_at/updated_at
	// reads as something a human did not write — and the first thing anyone
	// would do is collapse it.
	embedded := embedsModel(t)
	if embedded {
		g.p("\tstorm.Model")
		g.p("")
	}

	var schemaLines []string
	for _, c := range t.Columns {
		if embedded && isModelColumn(c) {
			continue
		}
		if fk := fkBy[c.Name]; fk != nil {
			target := s.Table(fk.RefTable)
			if target != nil {
				field := relationFieldName(c.Name)
				if c.NotNull {
					g.p("\t%s %s", field, modelName(target))
				} else {
					g.p("\t%s *%s", field, modelName(target))
				}
				if fk.OnDelete != "" && fk.OnDelete != schema.NoAction {
					schemaLines = append(schemaLines, fmt.Sprintf(
						"t.Col(&m.%s).OnDelete(storm.%s)", field, exportName(string(fk.OnDelete))))
				}
				continue
			}
		}
		k := goKind(c)
		if k == kindUnsupported {
			g.p("\t// %s %s — storm has no Go type for this yet; it is omitted rather",
				exportName(c.Name), c.Type.SQL())
			g.p("\t// than guessed, so a diff will want to drop it until you decide.")
			continue
		}
		g.p("\t%s %s", exportName(c.Name), importGoType(c))
		if l := columnFacts(c); l != "" {
			schemaLines = append(schemaLines, fmt.Sprintf("t.Col(&m.%s)%s", exportName(c.Name), l))
		}
	}
	g.p("}")
	g.p("")

	if t.Name != tableNameFor(name) {
		schemaLines = append([]string{fmt.Sprintf("t.Name(%q)", t.Name)}, schemaLines...)
	}
	if len(schemaLines) == 0 {
		return
	}
	g.p("func (m *%s) Schema(t *storm.Table) {", name)
	for _, l := range schemaLines {
		g.p("\t%s", l)
	}
	g.p("}")
	g.p("")
}

// columnFacts is what the Go type cannot say.
func columnFacts(c *schema.Column) string {
	var b strings.Builder
	if n := c.Type.Size; n > 0 {
		fmt.Fprintf(&b, ".Size(%d)", n)
	}
	if c.Default != "" && !isIdentityDefault(c.Default) {
		fmt.Fprintf(&b, ".Default(%q)", c.Default)
	}
	if c.Version {
		b.WriteString(".Version()")
	}
	if c.Immutable {
		b.WriteString(".Immutable()")
	}
	return b.String()
}

// isIdentityDefault skips defaults storm.Model already supplies, so an imported
// model does not restate them and then diff against itself.
func isIdentityDefault(d string) bool {
	switch strings.ToLower(strings.TrimSpace(d)) {
	case "gen_random_uuid()", "now()", "current_timestamp":
		return true
	}
	return false
}

// importGoType is the Go type for an imported column. Nullable scalars become
// pointers, which is the declaration form — Null[T] is the READ form and is
// generated, not written.
//
// An enum column takes its own named type rather than string: that is what
// makes the generated query API typed, and importing it as a string would
// silently give up the property the model exists to provide.
func importGoType(c *schema.Column) string {
	base := baseGoType(c)
	if c.Type.Enum {
		base = exportName(c.Type.Name)
	}
	if c.NotNull || goKind(c) == kindBytes {
		return base
	}
	return "*" + base
}

// embedsModel reports whether a table carries exactly the storm.Model triple:
// a uuid primary key called id, plus created_at and updated_at.
//
// Conservative on purpose. Embedding when the shapes do not match would change
// what the model means — Model's id defaults to gen_random_uuid() and its
// created_at is immutable — so a near-miss is spelled out in full instead.
func embedsModel(t *schema.Table) bool {
	if len(t.PrimaryKey) != 1 || t.PrimaryKey[0] != "id" {
		return false
	}
	need := map[string]string{
		"id":         schema.TypeUUID,
		"created_at": schema.TypeTimestamptz,
		"updated_at": schema.TypeTimestamptz,
	}
	for _, c := range t.Columns {
		want, ok := need[c.Name]
		if !ok {
			continue
		}
		if c.Type.Name != want || !c.NotNull || c.Type.Array {
			return false
		}
		delete(need, c.Name)
	}
	return len(need) == 0
}

func isModelColumn(c *schema.Column) bool {
	switch c.Name {
	case "id", "created_at", "updated_at":
		return true
	}
	return false
}

func modelName(t *schema.Table) string {
	if t.GoName != "" {
		return t.GoName
	}
	return exportName(singular(t.Name))
}

// relationFieldName turns author_id into Author.
func relationFieldName(col string) string {
	return exportName(strings.TrimSuffix(col, "_id"))
}

// singular is a naive de-pluralisation, used ONLY to propose a type name for an
// imported table. It is allowed to be wrong here in a way it is not allowed to
// be in codegen: this output is a draft a human reads and renames, and the
// table name is pinned explicitly in Schema so a wrong guess cannot rename a
// table.
func singular(s string) string {
	switch {
	case strings.HasSuffix(s, "ies"):
		return s[:len(s)-3] + "y"
	case strings.HasSuffix(s, "sses"), strings.HasSuffix(s, "xes"), strings.HasSuffix(s, "ches"):
		return s[:len(s)-2]
	case strings.HasSuffix(s, "s") && !strings.HasSuffix(s, "ss"):
		return s[:len(s)-1]
	}
	return s
}

// tableNameFor mirrors storm's pluralisation, to decide whether the table name
// has to be pinned explicitly.
func tableNameFor(goName string) string {
	s := snakeOf(goName)
	switch {
	case strings.HasSuffix(s, "s"), strings.HasSuffix(s, "x"),
		strings.HasSuffix(s, "z"), strings.HasSuffix(s, "ch"), strings.HasSuffix(s, "sh"):
		return s + "es"
	case strings.HasSuffix(s, "y") && len(s) > 1 && !isVowel(s[len(s)-2]):
		return s[:len(s)-1] + "ies"
	default:
		return s + "s"
	}
}

func isVowel(b byte) bool {
	return b == 'a' || b == 'e' || b == 'i' || b == 'o' || b == 'u'
}

func snakeOf(s string) string {
	var b bytes.Buffer
	for i := 0; i < len(s); i++ {
		c := s[i]
		if c >= 'A' && c <= 'Z' {
			if i > 0 {
				b.WriteByte('_')
			}
			b.WriteByte(c + ('a' - 'A'))
			continue
		}
		b.WriteByte(c)
	}
	return b.String()
}
