package codegen

import (
	"fmt"
	"go/format"
	"reflect"
	"sort"
	"strconv"
)

// ModelShape is one model type as the generator saw it: enough to write an
// assertion that the struct has not changed since.
type ModelShape struct {
	// ImportPath and TypeName locate the model, e.g.
	// "example.com/app/model" and "Product".
	ImportPath string
	TypeName   string
	// Fields is every field name in declaration order. Embedded fields appear
	// under their type name, which is also how they are selected.
	Fields []string
	// Skip records why no assertion was written, if none was.
	Skip string
}

// ShapesOf reads the models the tool was given.
//
// It is reflection at GENERATE time, on the developer's machine, which is a
// different thing from reflection in the query path — the boundary the ban
// under runtime/ protects.
func ShapesOf(models []any) []ModelShape {
	out := make([]ModelShape, 0, len(models))
	for _, m := range models {
		t := reflect.TypeOf(m)
		for t != nil && t.Kind() == reflect.Pointer {
			t = t.Elem()
		}
		if t == nil || t.Kind() != reflect.Struct || t.PkgPath() == "" {
			continue
		}
		s := ModelShape{ImportPath: t.PkgPath(), TypeName: t.Name()}
		for i := 0; i < t.NumField(); i++ {
			f := t.Field(i)
			// An unexported field cannot be named from another package, and an
			// unkeyed literal of a struct that has one is illegal outside its
			// own package. Assert nothing rather than emit something that
			// cannot compile.
			if !f.IsExported() {
				s.Skip = "has unexported field " + f.Name
				s.Fields = nil
				break
			}
			s.Fields = append(s.Fields, f.Name)
		}
		out = append(out, s)
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].ImportPath != out[j].ImportPath {
			return out[i].ImportPath < out[j].ImportPath
		}
		return out[i].TypeName < out[j].TypeName
	})
	return out
}

// shapeFile writes the compile-time staleness check.
//
// A stale store used to COMPILE. Add a field to a model, skip `generate`, and
// the project builds cleanly with the column simply absent from the API — you
// find out when you finally type product.Barcode, which may be much later and
// somewhere else. Silence was the real cost of the generate step, not the
// command.
//
// So each model is rebuilt from its own fields through an UNKEYED literal.
// Unkeyed means positional, and positional means the compiler checks the field
// LIST:
//
//	add a field     → "too few values in struct literal"
//	remove a field  → "too many values in struct literal"
//	rename a field  → "m.OldName undefined"
//	reorder fields  → a type error at the position that moved
//
// What it does not catch: changing a field's TYPE (the value still comes from
// that same field), and any change inside Schema, Plans or Projections — those
// are method bodies, invisible to the type system. `storm verify -stale` is
// still the check for those, and this does not replace it.
func shapeFile(shapes []ModelShape, pkg string) ([]byte, error) {
	var g gen
	g.dec = decodersFor(DialectPostgres, "")
	g.p("// Code generated by storm %s. DO NOT EDIT.", Version())
	g.p("//")
	g.p("// The compile-time staleness check: if a model's fields changed and this")
	g.p("// file was not regenerated, the package below does not build.")
	g.p("package %s", pkg)
	g.p("")

	alias := map[string]string{}
	var paths []string
	for _, s := range shapes {
		if len(s.Fields) == 0 {
			continue
		}
		if _, ok := alias[s.ImportPath]; !ok {
			alias[s.ImportPath] = "m" + strconv.Itoa(len(alias))
			paths = append(paths, s.ImportPath)
		}
	}
	if len(paths) > 0 {
		g.p("import (")
		for _, p := range paths {
			g.p("\t%s %s", alias[p], strconv.Quote(p))
		}
		g.p(")")
		g.p("")
	}

	for _, s := range shapes {
		if s.Skip != "" {
			g.p("// %s.%s: no shape assertion — %s.", s.ImportPath, s.TypeName, s.Skip)
			g.p("")
			continue
		}
		if len(s.Fields) == 0 {
			continue
		}
		q := alias[s.ImportPath] + "." + s.TypeName
		g.p("// _assert%sShape fails to compile if %s gains, loses, renames or", s.TypeName, q)
		g.p("// reorders a field. Regenerate: `storm generate`.")
		g.p("func _assert%sShape(m %s) {", s.TypeName, q)
		g.p("\t_ = %s{", q)
		for _, f := range s.Fields {
			g.p("\t\tm.%s,", f)
		}
		g.p("\t}")
		g.p("}")
		g.p("")
	}

	if g.err != nil {
		return nil, g.err
	}
	src, err := format.Source(g.buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("codegen: shape assertions do not parse (this is a storm bug): %w\n%s", err, g.buf.String())
	}
	return src, nil
}
