// Code generated by storm (replaced). DO NOT EDIT.
//
// The compile-time staleness check: if a model's fields changed and this
// file was not regenerated, the package below does not build.
package store

import (
	m0 "example.com/orders/model"
)

// _assertBookingShape fails to compile if m0.Booking gains, loses, renames or
// reorders a field. Regenerate: `storm generate`.
func _assertBookingShape(m m0.Booking) {
	_ = m0.Booking{
		m.Model,
		m.Room,
		m.Guest,
		m.During,
	}
}

// _assertCustomerShape fails to compile if m0.Customer gains, loses, renames or
// reorders a field. Regenerate: `storm generate`.
func _assertCustomerShape(m m0.Customer) {
	_ = m0.Customer{
		m.Model,
		m.Email,
		m.Name,
		m.Orders,
	}
}

// _assertOrderShape fails to compile if m0.Order gains, loses, renames or
// reorders a field. Regenerate: `storm generate`.
func _assertOrderShape(m m0.Order) {
	_ = m0.Order{
		m.Model,
		m.Audited,
		m.Customer,
		m.Status,
		m.Total,
		m.PlacedAt,
		m.Lines,
	}
}

// _assertOrderLineShape fails to compile if m0.OrderLine gains, loses, renames or
// reorders a field. Regenerate: `storm generate`.
func _assertOrderLineShape(m m0.OrderLine) {
	_ = m0.OrderLine{
		m.Model,
		m.Order,
		m.Product,
		m.Quantity,
		m.UnitPrice,
	}
}

// _assertProductShape fails to compile if m0.Product gains, loses, renames or
// reorders a field. Regenerate: `storm generate`.
func _assertProductShape(m m0.Product) {
	_ = m0.Product{
		m.Model,
		m.SKU,
		m.Name,
		m.Price,
		m.Active,
		m.Tags,
		m.Attrs,
		m.Search,
	}
}

// _assertStockItemShape fails to compile if m0.StockItem gains, loses, renames or
// reorders a field. Regenerate: `storm generate`.
func _assertStockItemShape(m m0.StockItem) {
	_ = m0.StockItem{
		m.Model,
		m.Audited,
		m.Product,
		m.OnHand,
		m.Reserved,
		m.Version,
	}
}

// github.com/gsoultan/storm.UnionDecl: no shape assertion — has unexported field name.
