// Code generated by storm (devel). DO NOT EDIT.
// source: bounded context store

package store

import (
	"context"
	"fmt"

	"github.com/gsoultan/storm/examples/tenants/store/currency"
	"github.com/gsoultan/storm/examples/tenants/store/order"
	"github.com/gsoultan/storm/runtime"
	"github.com/gsoultan/storm/runtime/shard"
)

var _ = runtime.BatchOp{}

// FlushOrder ranks tables so that every table's foreign-key targets rank
// strictly lower. It is computed at generate time from the model, so no
// runtime code inspects a schema and no constraint has to be deferred for
// a graph write to succeed.
var FlushOrder = map[string]int{
	"currencies": 0,
	"orders":     1,
}

// NewUnit stages writes across this context and flushes them in foreign-key
// order as one round trip.
//
// This context contains a sharded table, so Add takes the shard.Bound the
// write belongs to and refuses a second one — a unit of work is one shard,
// because a transaction is.
func NewUnit() *shard.Unit { return shard.NewUnit(FlushOrder) }

// defaultChildLimit caps a relation load. Any constant is arbitrary — too
// low truncates a legitimate load, too high is the unbounded read the dba
// profile vetoes — so what is settled here is only the BEHAVIOUR on
// reaching it: an error, never a partial result. Override per plan with
// ChildLimit.
const defaultChildLimit = 1 << 20

// OrderWithCurrencyRow is orders with its Currency loaded.
type OrderWithCurrencyRow struct {
	order.Row
	// A pointer because the link is optional. nil means the row has no
	// Currency, which is different from having one that failed to load.
	Currency *currency.Row
}

type OrderWithCurrencyQuery struct {
	q order.Query
}

// OrderWithCurrency starts the plan.
func OrderWithCurrency() OrderWithCurrencyQuery { return OrderWithCurrencyQuery{q: order.New()} }

func (p OrderWithCurrencyQuery) Where(ps ...order.Pred) OrderWithCurrencyQuery {
	p.q = p.q.Where(ps...)
	return p
}

func (p OrderWithCurrencyQuery) WhereIf(cond bool, pr order.Pred) OrderWithCurrencyQuery {
	p.q = p.q.WhereIf(cond, pr)
	return p
}

func (p OrderWithCurrencyQuery) Any(ps ...order.Pred) OrderWithCurrencyQuery {
	p.q = p.q.Any(ps...)
	return p
}

func (p OrderWithCurrencyQuery) Not(pr order.Pred) OrderWithCurrencyQuery {
	p.q = p.q.Not(pr)
	return p
}

func (p OrderWithCurrencyQuery) NotAny(ps ...order.Pred) OrderWithCurrencyQuery {
	p.q = p.q.NotAny(ps...)
	return p
}

func (p OrderWithCurrencyQuery) Order(ts ...order.Sort) OrderWithCurrencyQuery {
	p.q = p.q.Order(ts...)
	return p
}

func (p OrderWithCurrencyQuery) Limit(n int64) OrderWithCurrencyQuery {
	p.q = p.q.Limit(n)
	return p
}

func (p OrderWithCurrencyQuery) Offset(n int64) OrderWithCurrencyQuery {
	p.q = p.q.Offset(n)
	return p
}

// After pages the PARENTS past one already seen — keyset pagination over
// the plan. It takes the plan's row type, so the cursor is a row you
// actually received rather than one you had to unwrap.
func (p OrderWithCurrencyQuery) After(r OrderWithCurrencyRow) OrderWithCurrencyQuery {
	p.q = p.q.After(r.Row)
	return p
}

// Err reports a parent query that outgrew its buffers or was given a
// mixed ordering to page. Terminals return it too; this is for checking
// a composed plan before running it.
func (p OrderWithCurrencyQuery) Err() error { return p.q.Err() }

// All runs the plan in exactly TWO round trips. Distinct parent keys are
// de-duplicated before the second, so a thousand rows pointing at three
// orgs fetch three orgs.
func (p OrderWithCurrencyQuery) All(ctx context.Context, ex shard.Bound) ([]OrderWithCurrencyRow, error) {
	parents, err := p.q.All(ctx, ex, nil)
	if err != nil {
		return nil, err
	}
	if len(parents) == 0 {
		return nil, nil
	}
	out := make([]OrderWithCurrencyRow, len(parents))
	seen := make(map[[16]byte]bool, len(parents))
	ids := make([][16]byte, 0, len(parents))
	for i, r := range parents {
		out[i] = OrderWithCurrencyRow{Row: r}
		key, ok := r.CurrencyID.Get()
		if !ok {
			continue
		}
		if !seen[key] {
			seen[key] = true
			ids = append(ids, key)
		}
	}
	if len(ids) == 0 {
		return out, nil
	}
	targets, err := currency.New().Unordered().
		Where(currency.ID.In(ids...)).
		Limit(int64(len(ids))).
		All(ctx, ex, nil)
	if err != nil {
		return nil, err
	}
	by := make(map[[16]byte]int, len(targets))
	for i := range targets {
		by[targets[i].ID] = i
	}
	for i := range out {
		key, ok := out[i].Row.CurrencyID.Get()
		if !ok {
			continue
		}
		j, ok := by[key]
		if !ok {
			// A foreign key pointing at a row that is not there. The database
			// forbids it, so reaching this means the constraint was dropped.
			return nil, fmt.Errorf("storm: %s references a missing %s row", "orders", "currencies")
		}
		out[i].Currency = &targets[j]
	}
	return out, nil
}
