// Package pgddl lowers the schema IR to PostgreSQL DDL.
//
// Output is byte-deterministic: the same IR always produces the same bytes, so
// `raorm verify` can fail CI on a plain diff and migrations can be golden-tested.
package pgddl

import (
	"strconv"
	"strings"

	"github.com/gsoultan/raorm/schema"
)

// Create renders CREATE statements for a whole schema, enums first.
func Create(s *schema.Schema) string {
	var b strings.Builder
	for _, e := range s.Enums {
		b.WriteString(CreateEnum(e))
		b.WriteString("\n")
	}
	if len(s.Enums) > 0 {
		b.WriteString("\n")
	}
	for i, t := range s.Tables {
		if i > 0 {
			b.WriteString("\n")
		}
		b.WriteString(CreateTable(t))
	}
	// Foreign keys come last so table order never matters.
	var fks strings.Builder
	for _, t := range s.Tables {
		for _, fk := range t.ForeignKeys {
			fks.WriteString(AddForeignKey(t, fk))
			fks.WriteString("\n")
		}
	}
	if fks.Len() > 0 {
		b.WriteString("\n")
		b.WriteString(fks.String())
	}
	return b.String()
}

// CreateEnum renders CREATE TYPE ... AS ENUM.
func CreateEnum(e *schema.Enum) string {
	lits := make([]string, len(e.Labels))
	for i, l := range e.Labels {
		lits[i] = quoteLit(l)
	}
	return "CREATE TYPE " + Ident(e.Name) + " AS ENUM (" + strings.Join(lits, ", ") + ");"
}

// CreateTable renders one table plus its indexes.
func CreateTable(t *schema.Table) string {
	var b strings.Builder
	b.WriteString("CREATE TABLE " + Ident(t.Name) + " (\n")

	parts := make([]string, 0, len(t.Columns)+8)
	for _, c := range t.Columns {
		parts = append(parts, "    "+ColumnDef(c))
	}
	if len(t.PrimaryKey) > 0 {
		parts = append(parts, "    PRIMARY KEY ("+identList(t.PrimaryKey)+")")
	}
	for _, u := range t.Uniques {
		parts = append(parts, "    CONSTRAINT "+Ident(u.Name)+" UNIQUE ("+exprList(u.Columns)+")")
	}
	for _, ck := range t.Checks {
		parts = append(parts, "    CONSTRAINT "+Ident(ck.Name)+" CHECK ("+ck.Expr+")")
	}
	for _, ex := range t.Excludes {
		parts = append(parts, "    "+excludeDef(ex))
	}
	b.WriteString(strings.Join(parts, ",\n"))
	b.WriteString("\n);\n")

	for _, ix := range t.Indexes {
		b.WriteString(CreateIndex(t, ix))
		b.WriteString("\n")
	}
	if t.Comment != "" {
		b.WriteString("COMMENT ON TABLE " + Ident(t.Name) + " IS " + quoteLit(t.Comment) + ";\n")
	}
	for _, c := range t.Columns {
		if c.Comment != "" {
			b.WriteString("COMMENT ON COLUMN " + Ident(t.Name) + "." + Ident(c.Name) +
				" IS " + quoteLit(c.Comment) + ";\n")
		}
	}
	return b.String()
}

// ColumnDef renders one column definition.
func ColumnDef(c *schema.Column) string {
	var b strings.Builder
	b.WriteString(Ident(c.Name) + " " + c.Type.SQL())
	if c.Generated != "" {
		b.WriteString(" GENERATED ALWAYS AS (" + c.Generated + ") STORED")
	} else if c.Identity {
		b.WriteString(" GENERATED BY DEFAULT AS IDENTITY")
	} else if c.Default != "" {
		b.WriteString(" DEFAULT " + c.Default)
	}
	if c.NotNull {
		b.WriteString(" NOT NULL")
	}
	return b.String()
}

// CreateIndex renders a CREATE INDEX.
func CreateIndex(t *schema.Table, ix *schema.Index) string {
	var b strings.Builder
	b.WriteString("CREATE ")
	if ix.Unique {
		b.WriteString("UNIQUE ")
	}
	b.WriteString("INDEX " + Ident(ix.Name) + " ON " + Ident(t.Name))
	if m := ix.Method; m != "" && m != "btree" {
		b.WriteString(" USING " + m)
	}
	keys := make([]string, len(ix.Columns))
	for i, c := range ix.Columns {
		k := maybeIdent(c.Name, c.Expr)
		if c.Desc {
			k += " DESC"
		}
		if c.NullsLast {
			k += " NULLS LAST"
		}
		keys[i] = k
	}
	b.WriteString(" (" + strings.Join(keys, ", ") + ")")
	if ix.Where != "" {
		b.WriteString(" WHERE " + ix.Where)
	}
	b.WriteString(";")
	return b.String()
}

// AddForeignKey renders an ALTER TABLE ... ADD CONSTRAINT ... FOREIGN KEY.
func AddForeignKey(t *schema.Table, fk *schema.ForeignKey) string {
	var b strings.Builder
	b.WriteString("ALTER TABLE " + Ident(t.Name) + " ADD CONSTRAINT " + Ident(fk.Name) +
		" FOREIGN KEY (" + identList(fk.Columns) + ") REFERENCES " + Ident(fk.RefTable) +
		" (" + identList(fk.RefColumns) + ")")
	if fk.OnDelete != "" && fk.OnDelete != schema.NoAction {
		b.WriteString(" ON DELETE " + string(fk.OnDelete))
	}
	if fk.OnUpdate != "" && fk.OnUpdate != schema.NoAction {
		b.WriteString(" ON UPDATE " + string(fk.OnUpdate))
	}
	if fk.Deferrable {
		b.WriteString(" DEFERRABLE INITIALLY DEFERRED")
	}
	b.WriteString(";")
	return b.String()
}

func excludeDef(ex *schema.Exclude) string {
	parts := make([]string, len(ex.Parts))
	for i, p := range ex.Parts {
		if p.Expr {
			parts[i] = "(" + p.Column + ") WITH " + p.Operator
		} else {
			parts[i] = Ident(p.Column) + " WITH " + p.Operator
		}
	}
	s := "CONSTRAINT " + Ident(ex.Name) + " EXCLUDE USING " + ex.Method +
		" (" + strings.Join(parts, ", ") + ")"
	if ex.Where != "" {
		s += " WHERE (" + ex.Where + ")"
	}
	return s
}

// ---- quoting ----

// Ident quotes an identifier. Everything is quoted unconditionally: it is the
// only way to be correct for reserved words and mixed case, and the only
// identifiers that reach here came from a Go field name or an explicit
// override, never from a runtime value.
func Ident(s string) string {
	return `"` + strings.ReplaceAll(s, `"`, `""`) + `"`
}

func maybeIdent(s string, isExpr bool) string {
	if isExpr {
		return s
	}
	return Ident(s)
}

func quoteLit(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}

func identList(names []string) string {
	out := make([]string, len(names))
	for i, n := range names {
		out[i] = Ident(n)
	}
	return strings.Join(out, ", ")
}

// exprList quotes plain names but passes expressions like lower(email) through.
func exprList(names []string) string {
	out := make([]string, len(names))
	for i, n := range names {
		if strings.ContainsAny(n, "()") {
			out[i] = "(" + n + ")"
		} else {
			out[i] = Ident(n)
		}
	}
	return strings.Join(out, ", ")
}

var _ = strconv.Itoa
