// Package pgddl lowers the schema IR to PostgreSQL DDL.
//
// Output is byte-deterministic: the same IR always produces the same bytes, so
// `storm verify` can fail CI on a plain diff and migrations can be golden-tested.
package pgddl

import (
	"fmt"
	"sort"
	"strconv"
	"strings"

	"github.com/gsoultan/storm/schema"
)

// Create renders CREATE statements for a whole schema, enums first.
// NeedsBtreeGist reports whether this schema's DDL depends on the btree_gist
// extension: any exclusion constraint does, because mixing `=` on a scalar
// with `&&` on a range gives the scalar a GIST operator class only that
// extension provides.
//
// Exported because the DDL is not the only thing that must know: a migration
// plan applied to a FRESH database needs the extension before the first
// exclusion constraint, and a plan that omits it works on every long-lived dev
// database (where something installed it years ago) and fails on production
// day one — which is exactly how this gap survived until a container was
// recreated from scratch.
func NeedsBtreeGist(s *schema.Schema) bool {
	for _, t := range s.Tables {
		if len(t.Excludes) > 0 {
			return true
		}
	}
	return false
}

// BtreeGistDDL installs btree_gist, safely under concurrency — see the
// comment at its use in Create.
//
// Installed WITH SCHEMA public, explicitly. Without it an extension lands in
// the first schema of the search path — which, when a migration is replayed
// into a scratch namespace or a model is normalised through one, is the
// scratch schema, and the operator classes vanish with it. A named operator
// class is then "does not exist" from any other schema, and IF NOT EXISTS is
// satisfied by the wrong copy. public is where PostgreSQL's own default puts
// extensions, and it is on every default search path.
const BtreeGistDDL = "DO $storm$ BEGIN CREATE EXTENSION IF NOT EXISTS btree_gist WITH SCHEMA public; " +
	"EXCEPTION WHEN unique_violation OR duplicate_object THEN NULL; END $storm$;"

func Create(s *schema.Schema) string {
	var b strings.Builder
	if NeedsBtreeGist(s) {
		// Wrapped rather than bare because IF NOT EXISTS races with ITSELF:
		// two connections both pass the existence check and one dies on the
		// pg_extension_name_index unique constraint — found by two test
		// packages normalising concurrently, and exactly what two CI jobs or
		// two deploy replicas would do. The emitted SQL has to be safe
		// wherever and however concurrently it is applied.
		b.WriteString(BtreeGistDDL + "\n\n")
	}
	if NeedsPgTrgm(s) {
		b.WriteString(PgTrgmDDL + "\n\n")
	}
	for _, e := range s.Enums {
		b.WriteString(CreateEnum(e))
		b.WriteString("\n")
	}
	if len(s.Enums) > 0 {
		b.WriteString("\n")
	}
	for i, t := range s.Tables {
		if i > 0 {
			b.WriteString("\n")
		}
		b.WriteString(CreateTable(t))
	}
	// Foreign keys come last so table order never matters.
	var fks strings.Builder
	for _, t := range s.Tables {
		for _, fk := range t.ForeignKeys {
			fks.WriteString(AddForeignKey(t, fk))
			fks.WriteString("\n")
		}
	}
	if fks.Len() > 0 {
		b.WriteString("\n")
		b.WriteString(fks.String())
	}
	return b.String()
}

// CreateEnum renders CREATE TYPE ... AS ENUM.
func CreateEnum(e *schema.Enum) string {
	lits := make([]string, len(e.Labels))
	for i, l := range e.Labels {
		lits[i] = quoteLit(l)
	}
	return "CREATE TYPE " + Ident(e.Name) + " AS ENUM (" + strings.Join(lits, ", ") + ");"
}

// CreateTable renders one table plus its indexes.
func CreateTable(t *schema.Table) string {
	var b strings.Builder
	b.WriteString("CREATE TABLE " + Ident(t.Name) + " (\n")

	parts := make([]string, 0, len(t.Columns)+8)
	for _, c := range t.Columns {
		parts = append(parts, "    "+ColumnDef(c))
	}
	if len(t.PrimaryKey) > 0 {
		parts = append(parts, "    PRIMARY KEY ("+identList(t.PrimaryKey)+")")
	}
	for _, u := range t.Uniques {
		parts = append(parts, "    CONSTRAINT "+Ident(u.Name)+" UNIQUE ("+exprList(u.Columns)+")")
	}
	for _, ck := range t.Checks {
		parts = append(parts, "    CONSTRAINT "+Ident(ck.Name)+" CHECK ("+ck.Expr+")")
	}
	for _, ex := range t.Excludes {
		parts = append(parts, "    "+excludeDef(ex))
	}
	b.WriteString(strings.Join(parts, ",\n"))
	b.WriteString("\n);\n")

	for _, ix := range t.Indexes {
		b.WriteString(CreateIndex(t, ix))
		b.WriteString("\n")
	}
	if t.Comment != "" {
		b.WriteString("COMMENT ON TABLE " + Ident(t.Name) + " IS " + quoteLit(t.Comment) + ";\n")
	}
	for _, c := range t.Columns {
		if c.Comment != "" {
			b.WriteString("COMMENT ON COLUMN " + Ident(t.Name) + "." + Ident(c.Name) +
				" IS " + quoteLit(c.Comment) + ";\n")
		}
	}
	return b.String()
}

// ColumnDef renders one column definition.
func ColumnDef(c *schema.Column) string {
	var b strings.Builder
	b.WriteString(Ident(c.Name) + " " + c.Type.SQL())
	if c.Generated != "" {
		b.WriteString(" GENERATED ALWAYS AS (" + c.Generated + ") STORED")
	} else if c.Identity {
		b.WriteString(" GENERATED BY DEFAULT AS IDENTITY")
	} else if c.Default != "" {
		b.WriteString(" DEFAULT " + c.Default)
	}
	if c.NotNull {
		b.WriteString(" NOT NULL")
	}
	return b.String()
}

// CreateIndex renders a CREATE INDEX.
//
// The clauses come in the order pg_get_indexdef prints them, so that what the
// emitter writes and what introspection reads back are the same shape and the
// round trip is a fixpoint: keys, INCLUDE, NULLS NOT DISTINCT, WITH, WHERE.
func CreateIndex(t *schema.Table, ix *schema.Index) string {
	return createIndex(t, ix, false)
}

// CreateIndexConcurrently renders a CREATE INDEX CONCURRENTLY: the build
// that does not block writes to the table while it runs, which on a table
// with traffic is the only build a deployment can afford. It cannot run
// inside a transaction block, so a migration that carries one has to be
// applied as a single statement outside one — see migrate.Change.NoTransaction.
func CreateIndexConcurrently(t *schema.Table, ix *schema.Index) string {
	return createIndex(t, ix, true)
}

// DropIndexConcurrently renders a DROP INDEX CONCURRENTLY, with the same
// constraint.
func DropIndexConcurrently(name string) string {
	return "DROP INDEX CONCURRENTLY " + Ident(name) + ";"
}

func createIndex(t *schema.Table, ix *schema.Index, concurrently bool) string {
	var b strings.Builder
	b.WriteString("CREATE ")
	if ix.Unique {
		b.WriteString("UNIQUE ")
	}
	b.WriteString("INDEX ")
	if concurrently {
		b.WriteString("CONCURRENTLY ")
	}
	b.WriteString(Ident(ix.Name) + " ON " + Ident(t.Name))
	if m := ix.Method; m != "" && m != "btree" {
		b.WriteString(" USING " + m)
	}
	keys := make([]string, len(ix.Columns))
	for i, c := range ix.Columns {
		keys[i] = IndexKey(c)
	}
	b.WriteString(" (" + strings.Join(keys, ", ") + ")")
	if len(ix.Include) > 0 {
		b.WriteString(" INCLUDE (" + identList(ix.Include) + ")")
	}
	if ix.NullsNotDistinct {
		b.WriteString(" NULLS NOT DISTINCT")
	}
	if len(ix.With) > 0 {
		params := make([]string, len(ix.With))
		for i, p := range ix.With {
			params[i] = p.Name + " = " + p.Value
		}
		b.WriteString(" WITH (" + strings.Join(params, ", ") + ")")
	}
	if ix.Where != "" {
		b.WriteString(" WHERE " + ix.Where)
	}
	b.WriteString(";")
	return b.String()
}

// IndexKey renders one key: the column or expression, then its collation,
// operator class, direction and NULL placement — pg_get_indexdef's order.
//
// An expression is always parenthesised. `lower(email)` would parse bare, but
// `n + 1` would not, and one rule that is always right beats a rule that has
// to recognise a function call.
func IndexKey(c schema.IndexColumn) string {
	k := Ident(c.Name)
	if c.Expr {
		k = "(" + c.Name + ")"
	}
	if c.Collate != "" {
		k += " COLLATE " + Ident(c.Collate)
	}
	if c.OpClass != "" {
		k += " " + qualifiedOpClass(c.OpClass)
	}
	if c.Desc {
		k += " DESC"
	}
	switch {
	case c.NullsFirst:
		k += " NULLS FIRST"
	case c.NullsLast:
		k += " NULLS LAST"
	}
	return k
}

// qualifiedOpClass names an operator class so that it resolves from ANY
// schema. One from an extension storm installs itself is in public, by the
// install above, and is qualified as such; one the model already qualified —
// extensions.gin_trgm_ops on a host that keeps them there — is left alone,
// and the install storm emits is a no-op against the copy that exists.
func qualifiedOpClass(class string) string {
	if IsTrgmOpClass(class) {
		return "public." + class
	}
	return class
}

// NeedsPgTrgm reports whether any index asks for a trigram operator class,
// which lives in the pg_trgm extension.
func NeedsPgTrgm(s *schema.Schema) bool {
	for _, t := range s.Tables {
		for _, ix := range t.Indexes {
			for _, c := range ix.Columns {
				if IsTrgmOpClass(c.OpClass) {
					return true
				}
			}
		}
	}
	return false
}

// IsTrgmOpClass reports whether an UNQUALIFIED operator class comes from
// pg_trgm. A qualified one is the model's own statement of where it lives.
func IsTrgmOpClass(class string) bool {
	return class == "gin_trgm_ops" || class == "gist_trgm_ops"
}

// PgTrgmDDL installs pg_trgm, wrapped the same way as btree_gist and for the
// same reason: IF NOT EXISTS races with itself under concurrent appliers.
const PgTrgmDDL = "DO $storm$ BEGIN CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public; " +
	"EXCEPTION WHEN unique_violation OR duplicate_object THEN NULL; END $storm$;"

// Check refuses what the model says that PostgreSQL cannot: the index facts
// that exist for MySQL's sake. Silently dropping them would leave a TEXT
// column's prefix index — the only way MySQL indexes such a column at all —
// as a whole-value index here, which is a different index with a different
// cost, and an invisible index visible.
func Check(s *schema.Schema) error {
	var problems []string
	for _, t := range s.Tables {
		for _, ix := range t.Indexes {
			switch ix.Method {
			case "fulltext", "spatial":
				problems = append(problems, fmt.Sprintf(
					"  %s: index %s is a MySQL %s index — PostgreSQL's full-text search is a tsvector column with a gin index",
					t.Name, ix.Name, strings.ToUpper(ix.Method)))
			}
			if ix.Invisible {
				problems = append(problems, fmt.Sprintf(
					"  %s: index %s is INVISIBLE, which PostgreSQL has no equivalent for — drop it, or leave it visible",
					t.Name, ix.Name))
			}
			for _, c := range ix.Columns {
				if c.Prefix > 0 {
					problems = append(problems, fmt.Sprintf(
						"  %s: index %s indexes a %d-character prefix of %s, which PostgreSQL cannot — "+
							"index the whole column, or an expression: storm.IndexExpr(&m.%s, \"left(%%s, %d)\")",
						t.Name, ix.Name, c.Prefix, c.Name, exportish(c.Name), c.Prefix))
				}
			}
		}
	}
	if len(problems) == 0 {
		return nil
	}
	sort.Strings(problems)
	return fmt.Errorf("this model does not port to PostgreSQL:\n%s", strings.Join(problems, "\n"))
}

// exportish guesses a Go field name from a column name for an error's fix,
// which only has to be recognisable, not exact.
func exportish(col string) string {
	var b strings.Builder
	up := true
	for _, r := range col {
		if r == '_' {
			up = true
			continue
		}
		if up {
			b.WriteString(strings.ToUpper(string(r)))
			up = false
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}

// AddForeignKey renders an ALTER TABLE ... ADD CONSTRAINT ... FOREIGN KEY.
func AddForeignKey(t *schema.Table, fk *schema.ForeignKey) string {
	var b strings.Builder
	b.WriteString("ALTER TABLE " + Ident(t.Name) + " ADD CONSTRAINT " + Ident(fk.Name) +
		" FOREIGN KEY (" + identList(fk.Columns) + ") REFERENCES " + Ident(fk.RefTable) +
		" (" + identList(fk.RefColumns) + ")")
	if fk.OnDelete != "" && fk.OnDelete != schema.NoAction {
		b.WriteString(" ON DELETE " + string(fk.OnDelete))
	}
	if fk.OnUpdate != "" && fk.OnUpdate != schema.NoAction {
		b.WriteString(" ON UPDATE " + string(fk.OnUpdate))
	}
	if fk.Deferrable {
		b.WriteString(" DEFERRABLE INITIALLY DEFERRED")
	}
	b.WriteString(";")
	return b.String()
}

func excludeDef(ex *schema.Exclude) string {
	parts := make([]string, len(ex.Parts))
	for i, p := range ex.Parts {
		if p.Expr {
			parts[i] = "(" + p.Column + ") WITH " + p.Operator
		} else {
			parts[i] = Ident(p.Column) + " WITH " + p.Operator
		}
	}
	s := "CONSTRAINT " + Ident(ex.Name) + " EXCLUDE USING " + ex.Method +
		" (" + strings.Join(parts, ", ") + ")"
	if ex.Where != "" {
		s += " WHERE (" + ex.Where + ")"
	}
	return s
}

// ---- quoting ----

// Ident quotes an identifier. Everything is quoted unconditionally: it is the
// only way to be correct for reserved words and mixed case, and the only
// identifiers that reach here came from a Go field name or an explicit
// override, never from a runtime value.
func Ident(s string) string {
	return `"` + strings.ReplaceAll(s, `"`, `""`) + `"`
}

func maybeIdent(s string, isExpr bool) string {
	if isExpr {
		return s
	}
	return Ident(s)
}

func quoteLit(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}

func identList(names []string) string {
	out := make([]string, len(names))
	for i, n := range names {
		out[i] = Ident(n)
	}
	return strings.Join(out, ", ")
}

// exprList quotes plain names but passes expressions like lower(email) through.
func exprList(names []string) string {
	out := make([]string, len(names))
	for i, n := range names {
		if strings.ContainsAny(n, "()") {
			out[i] = "(" + n + ")"
		} else {
			out[i] = Ident(n)
		}
	}
	return strings.Join(out, ", ")
}

var _ = strconv.Itoa
