package pgddl_test

import (
	"strings"
	"testing"

	"github.com/gsoultan/storm/compile/pgddl"
	"github.com/gsoultan/storm/schema"
)

// A serial is a TYPE in the CREATE TABLE grammar, not a default.
//
// `storm import` used to carry the introspected default verbatim, which put
// the source database's sequence name in the model —
// `bigint DEFAULT nextval('audit_events_seq_seq'::regclass)` — and that DDL
// applies to exactly one database in the world. `storm verify` failed on the
// scratch apply, so an imported model could never be verified.
func TestSerialRendersAsAType(t *testing.T) {
	for _, tc := range []struct {
		typ  string
		want string
	}{
		{schema.TypeInt2, "smallserial"},
		{schema.TypeInt4, "serial"},
		{schema.TypeInt8, "bigserial"},
	} {
		got := pgddl.ColumnDef(&schema.Column{
			Name: "seq", Type: schema.Type{Name: tc.typ}, NotNull: true, Serial: true,
		})
		if !strings.Contains(got, tc.want) {
			t.Errorf("%s: ColumnDef = %q, want %s", tc.typ, got, tc.want)
		}
		if strings.Contains(got, "nextval") {
			t.Errorf("%s: serial rendered a nextval default: %q", tc.typ, got)
		}
	}
}

// Identity is a different fact and keeps its own spelling. Collapsing the two
// would let a model describe a database it then proposes to alter.
func TestIdentityIsNotSerial(t *testing.T) {
	got := pgddl.ColumnDef(&schema.Column{
		Name: "seq", Type: schema.Type{Name: schema.TypeInt8}, NotNull: true, Identity: true,
	})
	if !strings.Contains(got, "GENERATED BY DEFAULT AS IDENTITY") {
		t.Errorf("ColumnDef = %q", got)
	}
	if strings.Contains(got, "serial") {
		t.Errorf("identity rendered as serial: %q", got)
	}
}
