// Code generated by raorm. DO NOT EDIT.
// source: bounded context store

package store

import (
	"context"
	"fmt"

	"github.com/gsoultan/raorm/examples/blog/store/article"
	"github.com/gsoultan/raorm/examples/blog/store/author"
	"github.com/gsoultan/raorm/runtime"
)

// FlushOrder ranks tables so that every table's foreign-key targets rank
// strictly lower. It is computed at generate time from the model, so no
// runtime code inspects a schema and no constraint has to be deferred for
// a graph write to succeed.
var FlushOrder = map[string]int{
	"authors":  0,
	"articles": 1,
}

// NewUnit stages writes across this context and flushes them in foreign-key
// order as one round trip.
func NewUnit() *runtime.Unit { return runtime.NewUnit(FlushOrder) }

// defaultChildLimit caps a relation load. Any constant is arbitrary — too
// low truncates a legitimate load, too high is the unbounded read the dba
// profile vetoes — so what is settled here is only the BEHAVIOUR on
// reaching it: an error, never a partial result. Override per plan with
// ChildLimit.
const defaultChildLimit = 1 << 20

// ArticleWithAuthorRow is articles with its Author loaded.
type ArticleWithAuthorRow struct {
	article.Row
	Author author.Row
}

type ArticleWithAuthorQuery struct {
	q article.Query
}

// ArticleWithAuthor starts the plan.
func ArticleWithAuthor() ArticleWithAuthorQuery { return ArticleWithAuthorQuery{q: article.New()} }

func (p ArticleWithAuthorQuery) Where(ps ...article.Pred) ArticleWithAuthorQuery {
	p.q = p.q.Where(ps...)
	return p
}

func (p ArticleWithAuthorQuery) WhereIf(cond bool, pr article.Pred) ArticleWithAuthorQuery {
	p.q = p.q.WhereIf(cond, pr)
	return p
}

func (p ArticleWithAuthorQuery) Any(ps ...article.Pred) ArticleWithAuthorQuery {
	p.q = p.q.Any(ps...)
	return p
}

func (p ArticleWithAuthorQuery) Not(pr article.Pred) ArticleWithAuthorQuery {
	p.q = p.q.Not(pr)
	return p
}

func (p ArticleWithAuthorQuery) NotAny(ps ...article.Pred) ArticleWithAuthorQuery {
	p.q = p.q.NotAny(ps...)
	return p
}

func (p ArticleWithAuthorQuery) Order(ts ...article.Sort) ArticleWithAuthorQuery {
	p.q = p.q.Order(ts...)
	return p
}

func (p ArticleWithAuthorQuery) Limit(n int64) ArticleWithAuthorQuery {
	p.q = p.q.Limit(n)
	return p
}

func (p ArticleWithAuthorQuery) Offset(n int64) ArticleWithAuthorQuery {
	p.q = p.q.Offset(n)
	return p
}

// After pages the PARENTS past one already seen — keyset pagination over
// the plan. It takes the plan's row type, so the cursor is a row you
// actually received rather than one you had to unwrap.
func (p ArticleWithAuthorQuery) After(r ArticleWithAuthorRow) ArticleWithAuthorQuery {
	p.q = p.q.After(r.Row)
	return p
}

// Err reports a parent query that outgrew its buffers or was given a
// mixed ordering to page. Terminals return it too; this is for checking
// a composed plan before running it.
func (p ArticleWithAuthorQuery) Err() error { return p.q.Err() }

// All runs the plan in exactly TWO round trips. Distinct parent keys are
// de-duplicated before the second, so a thousand rows pointing at three
// orgs fetch three orgs.
func (p ArticleWithAuthorQuery) All(ctx context.Context, ex runtime.Executor) ([]ArticleWithAuthorRow, error) {
	parents, err := p.q.All(ctx, ex, nil)
	if err != nil {
		return nil, err
	}
	if len(parents) == 0 {
		return nil, nil
	}
	out := make([]ArticleWithAuthorRow, len(parents))
	seen := make(map[[16]byte]bool, len(parents))
	ids := make([][16]byte, 0, len(parents))
	for i, r := range parents {
		out[i] = ArticleWithAuthorRow{Row: r}
		key := r.AuthorID
		if !seen[key] {
			seen[key] = true
			ids = append(ids, key)
		}
	}
	if len(ids) == 0 {
		return out, nil
	}
	targets, err := author.New().Unordered().
		Where(author.ID.In(ids...)).
		Limit(int64(len(ids))).
		All(ctx, ex, nil)
	if err != nil {
		return nil, err
	}
	by := make(map[[16]byte]int, len(targets))
	for i := range targets {
		by[targets[i].ID] = i
	}
	for i := range out {
		key := out[i].AuthorID
		j, ok := by[key]
		if !ok {
			// A foreign key pointing at a row that is not there. The database
			// forbids it, so reaching this means the constraint was dropped.
			return nil, fmt.Errorf("raorm: %s references a missing %s row", "articles", "authors")
		}
		out[i].Author = targets[j]
	}
	return out, nil
}

// AuthorWithArticlesRow is authors with its Articles loaded.
//
// Articles is a field HERE and nowhere else: author.Row has no such field, so an
// unloaded relation is not an empty slice, not a lazy fetch and not a
// lint warning — it does not compile.
type AuthorWithArticlesRow struct {
	author.Row
	Articles []article.Row
}

// AuthorWithArticlesQuery builds the plan. Every builder method is redeclared rather than
// embedded: Go has no delegation, and an embedded Query would return
// itself from Where(), dropping straight out of the plan.
type AuthorWithArticlesQuery struct {
	q          author.Query
	childLimit int64
	childOrder []article.Sort
	childTop   int64
}

// AuthorWithArticles starts the plan.
func AuthorWithArticles() AuthorWithArticlesQuery {
	return AuthorWithArticlesQuery{q: author.New(), childLimit: defaultChildLimit}
}

func (p AuthorWithArticlesQuery) Where(ps ...author.Pred) AuthorWithArticlesQuery {
	p.q = p.q.Where(ps...)
	return p
}

func (p AuthorWithArticlesQuery) WhereIf(cond bool, pr author.Pred) AuthorWithArticlesQuery {
	p.q = p.q.WhereIf(cond, pr)
	return p
}

func (p AuthorWithArticlesQuery) Any(ps ...author.Pred) AuthorWithArticlesQuery {
	p.q = p.q.Any(ps...)
	return p
}

func (p AuthorWithArticlesQuery) Not(pr author.Pred) AuthorWithArticlesQuery {
	p.q = p.q.Not(pr)
	return p
}

func (p AuthorWithArticlesQuery) NotAny(ps ...author.Pred) AuthorWithArticlesQuery {
	p.q = p.q.NotAny(ps...)
	return p
}

func (p AuthorWithArticlesQuery) Order(ts ...author.Sort) AuthorWithArticlesQuery {
	p.q = p.q.Order(ts...)
	return p
}

func (p AuthorWithArticlesQuery) Limit(n int64) AuthorWithArticlesQuery {
	p.q = p.q.Limit(n)
	return p
}

func (p AuthorWithArticlesQuery) Offset(n int64) AuthorWithArticlesQuery {
	p.q = p.q.Offset(n)
	return p
}

// After pages the PARENTS past one already seen — keyset pagination over
// the plan. It takes the plan's row type, so the cursor is a row you
// actually received rather than one you had to unwrap.
func (p AuthorWithArticlesQuery) After(r AuthorWithArticlesRow) AuthorWithArticlesQuery {
	p.q = p.q.After(r.Row)
	return p
}

// Err reports a parent query that outgrew its buffers or was given a
// mixed ordering to page. Terminals return it too; this is for checking
// a composed plan before running it.
func (p AuthorWithArticlesQuery) Err() error { return p.q.Err() }

// ChildLimit caps the total children fetched ACROSS ALL PARENTS.
//
// It is a guard, not a page size. Fifty parents with ChildLimit(100) is
// an error, not a hundred children each — the two queries fetch every
// child of every matched parent in one batch, and the limit only exists
// so that batch cannot silently come back partial.
//
// THERE IS NO PER-PARENT LIMIT. "Each parent with its first twenty
// children" is greatest-n-per-group, and doing it in two round trips
// needs LATERAL or row_number(); slicing in Go after the fact would
// fetch everything and only look like a limit. It is not built yet.
//
// To page ONE parent's children — the common case — query the child
// table directly, where Order, After and Limit all work:
//
//	article.New().Where(article.AuthorID.Eq(id)).Order(...).After(last).Limit(20)
func (p AuthorWithArticlesQuery) ChildLimit(n int64) AuthorWithArticlesQuery {
	p.childLimit = n
	return p
}

// ChildTop keeps at most n children PER PARENT — greatest-n-per-group,
// still two round trips.
//
// This is the per-parent limit ChildLimit is not. "Fifty tenants, each
// with its five newest people" is one query, not fifty, because the
// limit is expressed in SQL rather than by looping or by slicing
// afterwards — slicing would fetch every child and only look like a
// limit.
//
// It REQUIRES ChildOrder, and that ordering must be a strict total order.
// "The first three by date" with ties on that date returns an arbitrary
// three, and a different arbitrary three next call — a bug that only
// appears under data the developer did not have. Add the child's primary
// key as a final term if the natural ordering is not unique.
func (p AuthorWithArticlesQuery) ChildTop(n int64) AuthorWithArticlesQuery {
	p.childTop = n
	return p
}

// ChildOrder orders the children within each parent.
//
// Without it they arrive in the child table's default order, which is its
// primary key — defined, but almost never what a caller wanted to show.
func (p AuthorWithArticlesQuery) ChildOrder(ts ...article.Sort) AuthorWithArticlesQuery {
	p.childOrder = ts
	return p
}

// All runs the plan in exactly TWO round trips, whatever the parent count.
//
// The mechanism is `= ANY($1)`: one placeholder binds the whole id list, so
// fifty parents and five thousand produce the same SQL and share one
// compiled statement. No join is involved, which is why M3 was never
// actually blocked on join support.
func (p AuthorWithArticlesQuery) All(ctx context.Context, ex runtime.Executor) ([]AuthorWithArticlesRow, error) {
	parents, err := p.q.All(ctx, ex, nil)
	if err != nil {
		return nil, err
	}
	if len(parents) == 0 {
		// Round two would be `= ANY('{}')`, a guaranteed-empty query. Not
		// issuing it is the difference between costing 2 round trips when
		// there is work and 2 when there is none.
		return nil, nil
	}
	out := make([]AuthorWithArticlesRow, len(parents))
	ids := make([][16]byte, len(parents))
	at := make(map[[16]byte]int, len(parents))
	for i, r := range parents {
		out[i] = AuthorWithArticlesRow{Row: r}
		ids[i] = r.ID
		at[r.ID] = i
	}
	var kids []article.Row
	if p.childTop > 0 {
		// Per-parent limit: one query with the limit expressed in SQL.
		kids, err = article.BatchTopByAuthorID(ctx, ex, ids, p.childTop, p.childOrder...)
	} else {
		// Unordered: the rows are bucketed into a map by parent, so a
		// server-side sort is paid and then destroyed. ChildOrder still
		// applies when given — order WITHIN a parent survives bucketing.
		cq := article.New().Unordered().Where(article.AuthorID.In(ids...)).Limit(p.childLimit)
		if len(p.childOrder) > 0 {
			cq = cq.Order(p.childOrder...)
		}
		kids, err = cq.All(ctx, ex, nil)
	}
	if err != nil {
		return nil, err
	}
	// A partial relation load is worse than a failed one: every count
	// computed from it is wrong and nothing says so. A per-parent load
	// is bounded by construction, so the global guard does not apply.
	if p.childTop == 0 && int64(len(kids)) >= p.childLimit {
		return nil, runtime.ErrChildLimit
	}
	for _, k := range kids {
		if i, ok := at[k.AuthorID]; ok {
			out[i].Articles = append(out[i].Articles, k)
		}
	}
	return out, nil
}

// AuthorFeedRow is authors with 1 relation(s) loaded.
//
// One type per DECLARED plan. Generating a type per With(...)
// combination would be 2^n per entity; you get the plans you named.
type AuthorFeedRow struct {
	author.Row
	Articles []article.Row
}

type AuthorFeedQuery struct {
	q          author.Query
	childLimit int64
}

// AuthorFeed starts the plan. It costs 2 round trips: one for the parents and
// one per relation, whatever the row count.
func AuthorFeed() AuthorFeedQuery {
	return AuthorFeedQuery{q: author.New(), childLimit: defaultChildLimit}
}

func (p AuthorFeedQuery) Where(ps ...author.Pred) AuthorFeedQuery {
	p.q = p.q.Where(ps...)
	return p
}

func (p AuthorFeedQuery) WhereIf(cond bool, pr author.Pred) AuthorFeedQuery {
	p.q = p.q.WhereIf(cond, pr)
	return p
}

func (p AuthorFeedQuery) Any(ps ...author.Pred) AuthorFeedQuery {
	p.q = p.q.Any(ps...)
	return p
}

func (p AuthorFeedQuery) Not(pr author.Pred) AuthorFeedQuery {
	p.q = p.q.Not(pr)
	return p
}

func (p AuthorFeedQuery) NotAny(ps ...author.Pred) AuthorFeedQuery {
	p.q = p.q.NotAny(ps...)
	return p
}

func (p AuthorFeedQuery) Order(ts ...author.Sort) AuthorFeedQuery {
	p.q = p.q.Order(ts...)
	return p
}

func (p AuthorFeedQuery) Limit(n int64) AuthorFeedQuery {
	p.q = p.q.Limit(n)
	return p
}

func (p AuthorFeedQuery) Offset(n int64) AuthorFeedQuery {
	p.q = p.q.Offset(n)
	return p
}

// After pages the PARENTS past one already seen — keyset pagination over
// the plan. It takes the plan's row type, so the cursor is a row you
// actually received rather than one you had to unwrap.
func (p AuthorFeedQuery) After(r AuthorFeedRow) AuthorFeedQuery {
	p.q = p.q.After(r.Row)
	return p
}

// Err reports a parent query that outgrew its buffers or was given a
// mixed ordering to page. Terminals return it too; this is for checking
// a composed plan before running it.
func (p AuthorFeedQuery) Err() error { return p.q.Err() }

// ChildLimit caps each relation's fetch. A guard, not a page size.
func (p AuthorFeedQuery) ChildLimit(n int64) AuthorFeedQuery {
	p.childLimit = n
	return p
}

// All runs the plan in 2 round trips.
func (p AuthorFeedQuery) All(ctx context.Context, ex runtime.Executor) ([]AuthorFeedRow, error) {
	parents, err := p.q.All(ctx, ex, nil)
	if err != nil {
		return nil, err
	}
	if len(parents) == 0 {
		return nil, nil
	}
	out := make([]AuthorFeedRow, len(parents))
	for i, r := range parents {
		out[i] = AuthorFeedRow{Row: r}
	}
	if err := p.load0(ctx, ex, out); err != nil {
		return nil, err
	}
	return out, nil
}

// load0 fetches Articles.
func (p AuthorFeedQuery) load0(ctx context.Context, ex runtime.Executor, out []AuthorFeedRow) error {
	ids := make([][16]byte, len(out))
	at := make(map[[16]byte]int, len(out))
	for i := range out {
		ids[i] = out[i].ID
		at[out[i].ID] = i
	}
	kids, err := article.New().Unordered().Where(article.AuthorID.In(ids...)).Limit(p.childLimit).All(ctx, ex, nil)
	if err != nil {
		return err
	}
	if int64(len(kids)) >= p.childLimit {
		return runtime.ErrChildLimit
	}
	for _, k := range kids {
		if j, ok := at[k.AuthorID]; ok {
			out[j].Articles = append(out[j].Articles, k)
		}
	}
	return nil
}

// AuthorHavingArticles narrows q to rows with at least one matching articles row — the
// filtered semi-join, in one statement. The child predicates are typed
// by the child's own package; ids and values meet only here.
func AuthorHavingArticles(q author.Query, ps ...article.Pred) AuthorHavingArticlesQuery {
	return AuthorHavingArticlesQuery{q: q, c: article.New().Unordered().Where(ps...)}
}

type AuthorHavingArticlesQuery struct {
	q author.Query
	c article.Query
}

var authorHavingArticlesLowering = func() runtime.Lowering {
	lw := author.Lowering()
	parentFrag := lw.Frag
	lw.Frag = func(op, col uint32) runtime.Frag {
		if col >= runtime.ChildColBase {
			return article.FragOf(op, col-runtime.ChildColBase)
		}
		return parentFrag(op, col)
	}
	lw.Exists = func(uint32) string {
		return "EXISTS (SELECT 1 FROM \"articles\" AS \"_raorm_e\" WHERE \"_raorm_e\".\"author_id\" = \"authors\".\"id\""
	}
	return lw
}()

var authorHavingArticlesCache = runtime.NewTreeCache()

func (h AuthorHavingArticlesQuery) stmt(count bool) (*runtime.Stmt, []runtime.Tok) {
	var buf [44]runtime.Tok
	toks := h.q.PredToks(buf[:0])
	parentPreds := len(toks) > 0
	child := h.c.PredToks(nil)
	toks = runtime.OffsetCols(toks, child, runtime.ChildColBase)
	arity := uint32(0)
	if len(child) > 0 {
		arity = 1 // the child stream reduces to one stack entry
	}
	toks = append(toks, runtime.MakeExists(0, arity))
	if parentPreds {
		toks = append(toks, runtime.MakeGroup(runtime.KAnd, 2))
	}
	if !count {
		toks = h.q.OrderToks(toks)
	}
	sel, cnt, limitSfx := author.StmtPieces()
	prefix, suffix := sel, limitSfx
	if count {
		prefix, suffix = cnt, ""
	}
	if st := authorHavingArticlesCache.Get(toks); st != nil {
		return st, toks
	}
	return authorHavingArticlesCache.Put(toks, runtime.SpliceTree(prefix, toks, authorHavingArticlesLowering, suffix)), toks
}

// All runs the composed statement. Bind order is stream order: parent
// values, child values, then the parent's paging.
func (h AuthorHavingArticlesQuery) All(ctx context.Context, ex runtime.Executor) ([]author.Row, error) {
	if err := h.q.Err(); err != nil {
		return nil, err
	}
	if err := h.c.Err(); err != nil {
		return nil, err
	}
	st, _ := h.stmt(false)
	if st.Err != nil {
		return nil, st.Err
	}
	pb := author.GetBinder()
	defer author.PutBinder(pb)
	cb := article.GetBinder()
	defer article.PutBinder(cb)
	args := h.q.BindPreds(pb, nil)
	args = h.c.BindPreds(cb, args)
	args = h.q.BindPaging(pb, args)
	rows, err := ex.Query(ctx, st.SQL, args)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var sl runtime.Slab
	var out []author.Row
	for rows.Next() {
		out = append(out, author.Row{})
		if err := author.Scan(rows.RawValues(), &out[len(out)-1], &sl); err != nil {
			return nil, err
		}
	}
	return out, rows.Err()
}

// Count runs the composed count: no ordering, no paging.
func (h AuthorHavingArticlesQuery) Count(ctx context.Context, ex runtime.Executor) (int64, error) {
	if err := h.q.Err(); err != nil {
		return 0, err
	}
	if err := h.c.Err(); err != nil {
		return 0, err
	}
	st, _ := h.stmt(true)
	if st.Err != nil {
		return 0, st.Err
	}
	pb := author.GetBinder()
	defer author.PutBinder(pb)
	cb := article.GetBinder()
	defer article.PutBinder(cb)
	args := h.q.BindPreds(pb, nil)
	args = h.c.BindPreds(cb, args)
	rows, err := ex.Query(ctx, st.SQL, args)
	if err != nil {
		return 0, err
	}
	defer rows.Close()
	if !rows.Next() {
		return 0, rows.Err()
	}
	return runtime.Int8(rows.RawValues()[0]), rows.Err()
}
