// Code generated by raorm. DO NOT EDIT.
// source: bounded context store

package store

import (
	"context"
	"fmt"

	"github.com/gsoultan/raorm/internal/planspike/store/attachment"
	"github.com/gsoultan/raorm/internal/planspike/store/comment"
	"github.com/gsoultan/raorm/internal/planspike/store/org"
	"github.com/gsoultan/raorm/internal/planspike/store/post"
	"github.com/gsoultan/raorm/internal/planspike/store/user"
	"github.com/gsoultan/raorm/runtime"
)

// FlushOrder ranks tables so that every table's foreign-key targets rank
// strictly lower. It is computed at generate time from the model, so no
// runtime code inspects a schema and no constraint has to be deferred for
// a graph write to succeed.
var FlushOrder = map[string]int{
	"events":      1,
	"orgs":        2,
	"users":       3,
	"posts":       4,
	"comments":    6,
	"attachments": 7,
}

// NewUnit stages writes across this context and flushes them in foreign-key
// order as one round trip.
func NewUnit() *runtime.Unit { return runtime.NewUnit(FlushOrder) }

// defaultChildLimit caps a relation load. Any constant is arbitrary — too
// low truncates a legitimate load, too high is the unbounded read the dba
// profile vetoes — so what is settled here is only the BEHAVIOUR on
// reaching it: an error, never a partial result. Override per plan with
// ChildLimit.
const defaultChildLimit = 1 << 20

// CommentWithAuthorRow is comments with its Author loaded.
type CommentWithAuthorRow struct {
	comment.Row
	Author user.Row
}

type CommentWithAuthorQuery struct {
	q comment.Query
}

// CommentWithAuthor starts the plan.
func CommentWithAuthor() CommentWithAuthorQuery { return CommentWithAuthorQuery{q: comment.New()} }

func (p CommentWithAuthorQuery) Where(ps ...comment.Pred) CommentWithAuthorQuery {
	p.q = p.q.Where(ps...)
	return p
}

func (p CommentWithAuthorQuery) WhereIf(cond bool, pr comment.Pred) CommentWithAuthorQuery {
	p.q = p.q.WhereIf(cond, pr)
	return p
}

func (p CommentWithAuthorQuery) Any(ps ...comment.Pred) CommentWithAuthorQuery {
	p.q = p.q.Any(ps...)
	return p
}

func (p CommentWithAuthorQuery) Not(pr comment.Pred) CommentWithAuthorQuery {
	p.q = p.q.Not(pr)
	return p
}

func (p CommentWithAuthorQuery) NotAny(ps ...comment.Pred) CommentWithAuthorQuery {
	p.q = p.q.NotAny(ps...)
	return p
}

func (p CommentWithAuthorQuery) Order(ts ...comment.Sort) CommentWithAuthorQuery {
	p.q = p.q.Order(ts...)
	return p
}

func (p CommentWithAuthorQuery) Limit(n int64) CommentWithAuthorQuery {
	p.q = p.q.Limit(n)
	return p
}

func (p CommentWithAuthorQuery) Offset(n int64) CommentWithAuthorQuery {
	p.q = p.q.Offset(n)
	return p
}

// After pages the PARENTS past one already seen — keyset pagination over
// the plan. It takes the plan's row type, so the cursor is a row you
// actually received rather than one you had to unwrap.
func (p CommentWithAuthorQuery) After(r CommentWithAuthorRow) CommentWithAuthorQuery {
	p.q = p.q.After(r.Row)
	return p
}

// Err reports a parent query that outgrew its buffers or was given a
// mixed ordering to page. Terminals return it too; this is for checking
// a composed plan before running it.
func (p CommentWithAuthorQuery) Err() error { return p.q.Err() }

// All runs the plan in exactly TWO round trips. Distinct parent keys are
// de-duplicated before the second, so a thousand rows pointing at three
// orgs fetch three orgs.
func (p CommentWithAuthorQuery) All(ctx context.Context, ex runtime.Executor) ([]CommentWithAuthorRow, error) {
	parents, err := p.q.All(ctx, ex, nil)
	if err != nil {
		return nil, err
	}
	if len(parents) == 0 {
		return nil, nil
	}
	out := make([]CommentWithAuthorRow, len(parents))
	seen := make(map[[16]byte]bool, len(parents))
	ids := make([][16]byte, 0, len(parents))
	for i, r := range parents {
		out[i] = CommentWithAuthorRow{Row: r}
		key := r.AuthorID
		if !seen[key] {
			seen[key] = true
			ids = append(ids, key)
		}
	}
	if len(ids) == 0 {
		return out, nil
	}
	targets, err := user.New().Unordered().
		Where(user.ID.In(ids...)).
		Limit(int64(len(ids))).
		All(ctx, ex, nil)
	if err != nil {
		return nil, err
	}
	by := make(map[[16]byte]int, len(targets))
	for i := range targets {
		by[targets[i].ID] = i
	}
	for i := range out {
		key := out[i].AuthorID
		j, ok := by[key]
		if !ok {
			// A foreign key pointing at a row that is not there. The database
			// forbids it, so reaching this means the constraint was dropped.
			return nil, fmt.Errorf("raorm: %s references a missing %s row", "comments", "users")
		}
		out[i].Author = targets[j]
	}
	return out, nil
}

// CommentWithParentRow is comments with its Parent loaded.
type CommentWithParentRow struct {
	comment.Row
	// A pointer because the link is optional. nil means the row has no
	// Parent, which is different from having one that failed to load.
	Parent *comment.Row
}

type CommentWithParentQuery struct {
	q comment.Query
}

// CommentWithParent starts the plan.
func CommentWithParent() CommentWithParentQuery { return CommentWithParentQuery{q: comment.New()} }

func (p CommentWithParentQuery) Where(ps ...comment.Pred) CommentWithParentQuery {
	p.q = p.q.Where(ps...)
	return p
}

func (p CommentWithParentQuery) WhereIf(cond bool, pr comment.Pred) CommentWithParentQuery {
	p.q = p.q.WhereIf(cond, pr)
	return p
}

func (p CommentWithParentQuery) Any(ps ...comment.Pred) CommentWithParentQuery {
	p.q = p.q.Any(ps...)
	return p
}

func (p CommentWithParentQuery) Not(pr comment.Pred) CommentWithParentQuery {
	p.q = p.q.Not(pr)
	return p
}

func (p CommentWithParentQuery) NotAny(ps ...comment.Pred) CommentWithParentQuery {
	p.q = p.q.NotAny(ps...)
	return p
}

func (p CommentWithParentQuery) Order(ts ...comment.Sort) CommentWithParentQuery {
	p.q = p.q.Order(ts...)
	return p
}

func (p CommentWithParentQuery) Limit(n int64) CommentWithParentQuery {
	p.q = p.q.Limit(n)
	return p
}

func (p CommentWithParentQuery) Offset(n int64) CommentWithParentQuery {
	p.q = p.q.Offset(n)
	return p
}

// After pages the PARENTS past one already seen — keyset pagination over
// the plan. It takes the plan's row type, so the cursor is a row you
// actually received rather than one you had to unwrap.
func (p CommentWithParentQuery) After(r CommentWithParentRow) CommentWithParentQuery {
	p.q = p.q.After(r.Row)
	return p
}

// Err reports a parent query that outgrew its buffers or was given a
// mixed ordering to page. Terminals return it too; this is for checking
// a composed plan before running it.
func (p CommentWithParentQuery) Err() error { return p.q.Err() }

// All runs the plan in exactly TWO round trips. Distinct parent keys are
// de-duplicated before the second, so a thousand rows pointing at three
// orgs fetch three orgs.
func (p CommentWithParentQuery) All(ctx context.Context, ex runtime.Executor) ([]CommentWithParentRow, error) {
	parents, err := p.q.All(ctx, ex, nil)
	if err != nil {
		return nil, err
	}
	if len(parents) == 0 {
		return nil, nil
	}
	out := make([]CommentWithParentRow, len(parents))
	seen := make(map[[16]byte]bool, len(parents))
	ids := make([][16]byte, 0, len(parents))
	for i, r := range parents {
		out[i] = CommentWithParentRow{Row: r}
		key, ok := r.ParentID.Get()
		if !ok {
			continue
		}
		if !seen[key] {
			seen[key] = true
			ids = append(ids, key)
		}
	}
	if len(ids) == 0 {
		return out, nil
	}
	targets, err := comment.New().Unordered().
		Where(comment.ID.In(ids...)).
		Limit(int64(len(ids))).
		All(ctx, ex, nil)
	if err != nil {
		return nil, err
	}
	by := make(map[[16]byte]int, len(targets))
	for i := range targets {
		by[targets[i].ID] = i
	}
	for i := range out {
		key, ok := out[i].ParentID.Get()
		if !ok {
			continue
		}
		j, ok := by[key]
		if !ok {
			// A foreign key pointing at a row that is not there. The database
			// forbids it, so reaching this means the constraint was dropped.
			return nil, fmt.Errorf("raorm: %s references a missing %s row", "comments", "comments")
		}
		out[i].Parent = &targets[j]
	}
	return out, nil
}

// CommentWithPostRow is comments with its Post loaded.
type CommentWithPostRow struct {
	comment.Row
	Post post.Row
}

type CommentWithPostQuery struct {
	q comment.Query
}

// CommentWithPost starts the plan.
func CommentWithPost() CommentWithPostQuery { return CommentWithPostQuery{q: comment.New()} }

func (p CommentWithPostQuery) Where(ps ...comment.Pred) CommentWithPostQuery {
	p.q = p.q.Where(ps...)
	return p
}

func (p CommentWithPostQuery) WhereIf(cond bool, pr comment.Pred) CommentWithPostQuery {
	p.q = p.q.WhereIf(cond, pr)
	return p
}

func (p CommentWithPostQuery) Any(ps ...comment.Pred) CommentWithPostQuery {
	p.q = p.q.Any(ps...)
	return p
}

func (p CommentWithPostQuery) Not(pr comment.Pred) CommentWithPostQuery {
	p.q = p.q.Not(pr)
	return p
}

func (p CommentWithPostQuery) NotAny(ps ...comment.Pred) CommentWithPostQuery {
	p.q = p.q.NotAny(ps...)
	return p
}

func (p CommentWithPostQuery) Order(ts ...comment.Sort) CommentWithPostQuery {
	p.q = p.q.Order(ts...)
	return p
}

func (p CommentWithPostQuery) Limit(n int64) CommentWithPostQuery {
	p.q = p.q.Limit(n)
	return p
}

func (p CommentWithPostQuery) Offset(n int64) CommentWithPostQuery {
	p.q = p.q.Offset(n)
	return p
}

// After pages the PARENTS past one already seen — keyset pagination over
// the plan. It takes the plan's row type, so the cursor is a row you
// actually received rather than one you had to unwrap.
func (p CommentWithPostQuery) After(r CommentWithPostRow) CommentWithPostQuery {
	p.q = p.q.After(r.Row)
	return p
}

// Err reports a parent query that outgrew its buffers or was given a
// mixed ordering to page. Terminals return it too; this is for checking
// a composed plan before running it.
func (p CommentWithPostQuery) Err() error { return p.q.Err() }

// All runs the plan in exactly TWO round trips. Distinct parent keys are
// de-duplicated before the second, so a thousand rows pointing at three
// orgs fetch three orgs.
func (p CommentWithPostQuery) All(ctx context.Context, ex runtime.Executor) ([]CommentWithPostRow, error) {
	parents, err := p.q.All(ctx, ex, nil)
	if err != nil {
		return nil, err
	}
	if len(parents) == 0 {
		return nil, nil
	}
	out := make([]CommentWithPostRow, len(parents))
	seen := make(map[[16]byte]bool, len(parents))
	ids := make([][16]byte, 0, len(parents))
	for i, r := range parents {
		out[i] = CommentWithPostRow{Row: r}
		key := r.PostID
		if !seen[key] {
			seen[key] = true
			ids = append(ids, key)
		}
	}
	if len(ids) == 0 {
		return out, nil
	}
	targets, err := post.New().Unordered().
		Where(post.ID.In(ids...)).
		Limit(int64(len(ids))).
		All(ctx, ex, nil)
	if err != nil {
		return nil, err
	}
	by := make(map[[16]byte]int, len(targets))
	for i := range targets {
		by[targets[i].ID] = i
	}
	for i := range out {
		key := out[i].PostID
		j, ok := by[key]
		if !ok {
			// A foreign key pointing at a row that is not there. The database
			// forbids it, so reaching this means the constraint was dropped.
			return nil, fmt.Errorf("raorm: %s references a missing %s row", "comments", "posts")
		}
		out[i].Post = targets[j]
	}
	return out, nil
}

// CommentWithRepliesRow is comments with its Replies loaded.
//
// Replies is a field HERE and nowhere else: comment.Row has no such field, so an
// unloaded relation is not an empty slice, not a lazy fetch and not a
// lint warning — it does not compile.
type CommentWithRepliesRow struct {
	comment.Row
	Replies []comment.Row
}

// CommentWithRepliesQuery builds the plan. Every builder method is redeclared rather than
// embedded: Go has no delegation, and an embedded Query would return
// itself from Where(), dropping straight out of the plan.
type CommentWithRepliesQuery struct {
	q          comment.Query
	childLimit int64
	childOrder []comment.Sort
	childTop   int64
}

// CommentWithReplies starts the plan.
func CommentWithReplies() CommentWithRepliesQuery {
	return CommentWithRepliesQuery{q: comment.New(), childLimit: defaultChildLimit}
}

func (p CommentWithRepliesQuery) Where(ps ...comment.Pred) CommentWithRepliesQuery {
	p.q = p.q.Where(ps...)
	return p
}

func (p CommentWithRepliesQuery) WhereIf(cond bool, pr comment.Pred) CommentWithRepliesQuery {
	p.q = p.q.WhereIf(cond, pr)
	return p
}

func (p CommentWithRepliesQuery) Any(ps ...comment.Pred) CommentWithRepliesQuery {
	p.q = p.q.Any(ps...)
	return p
}

func (p CommentWithRepliesQuery) Not(pr comment.Pred) CommentWithRepliesQuery {
	p.q = p.q.Not(pr)
	return p
}

func (p CommentWithRepliesQuery) NotAny(ps ...comment.Pred) CommentWithRepliesQuery {
	p.q = p.q.NotAny(ps...)
	return p
}

func (p CommentWithRepliesQuery) Order(ts ...comment.Sort) CommentWithRepliesQuery {
	p.q = p.q.Order(ts...)
	return p
}

func (p CommentWithRepliesQuery) Limit(n int64) CommentWithRepliesQuery {
	p.q = p.q.Limit(n)
	return p
}

func (p CommentWithRepliesQuery) Offset(n int64) CommentWithRepliesQuery {
	p.q = p.q.Offset(n)
	return p
}

// After pages the PARENTS past one already seen — keyset pagination over
// the plan. It takes the plan's row type, so the cursor is a row you
// actually received rather than one you had to unwrap.
func (p CommentWithRepliesQuery) After(r CommentWithRepliesRow) CommentWithRepliesQuery {
	p.q = p.q.After(r.Row)
	return p
}

// Err reports a parent query that outgrew its buffers or was given a
// mixed ordering to page. Terminals return it too; this is for checking
// a composed plan before running it.
func (p CommentWithRepliesQuery) Err() error { return p.q.Err() }

// ChildLimit caps the total children fetched ACROSS ALL PARENTS.
//
// It is a guard, not a page size. Fifty parents with ChildLimit(100) is
// an error, not a hundred children each — the two queries fetch every
// child of every matched parent in one batch, and the limit only exists
// so that batch cannot silently come back partial.
//
// THERE IS NO PER-PARENT LIMIT. "Each parent with its first twenty
// children" is greatest-n-per-group, and doing it in two round trips
// needs LATERAL or row_number(); slicing in Go after the fact would
// fetch everything and only look like a limit. It is not built yet.
//
// To page ONE parent's children — the common case — query the child
// table directly, where Order, After and Limit all work:
//
//	comment.New().Where(comment.ParentID.Eq(id)).Order(...).After(last).Limit(20)
func (p CommentWithRepliesQuery) ChildLimit(n int64) CommentWithRepliesQuery {
	p.childLimit = n
	return p
}

// ChildTop keeps at most n children PER PARENT — greatest-n-per-group,
// still two round trips.
//
// This is the per-parent limit ChildLimit is not. "Fifty tenants, each
// with its five newest people" is one query, not fifty, because the
// limit is expressed in SQL rather than by looping or by slicing
// afterwards — slicing would fetch every child and only look like a
// limit.
//
// It REQUIRES ChildOrder, and that ordering must be a strict total order.
// "The first three by date" with ties on that date returns an arbitrary
// three, and a different arbitrary three next call — a bug that only
// appears under data the developer did not have. Add the child's primary
// key as a final term if the natural ordering is not unique.
func (p CommentWithRepliesQuery) ChildTop(n int64) CommentWithRepliesQuery {
	p.childTop = n
	return p
}

// ChildOrder orders the children within each parent.
//
// Without it they arrive in the child table's default order, which is its
// primary key — defined, but almost never what a caller wanted to show.
func (p CommentWithRepliesQuery) ChildOrder(ts ...comment.Sort) CommentWithRepliesQuery {
	p.childOrder = ts
	return p
}

// All runs the plan in exactly TWO round trips, whatever the parent count.
//
// The mechanism is `= ANY($1)`: one placeholder binds the whole id list, so
// fifty parents and five thousand produce the same SQL and share one
// compiled statement. No join is involved, which is why M3 was never
// actually blocked on join support.
func (p CommentWithRepliesQuery) All(ctx context.Context, ex runtime.Executor) ([]CommentWithRepliesRow, error) {
	parents, err := p.q.All(ctx, ex, nil)
	if err != nil {
		return nil, err
	}
	if len(parents) == 0 {
		// Round two would be `= ANY('{}')`, a guaranteed-empty query. Not
		// issuing it is the difference between costing 2 round trips when
		// there is work and 2 when there is none.
		return nil, nil
	}
	out := make([]CommentWithRepliesRow, len(parents))
	ids := make([][16]byte, len(parents))
	at := make(map[[16]byte]int, len(parents))
	for i, r := range parents {
		out[i] = CommentWithRepliesRow{Row: r}
		ids[i] = r.ID
		at[r.ID] = i
	}
	var kids []comment.Row
	if p.childTop > 0 {
		// Per-parent limit: one query with the limit expressed in SQL.
		kids, err = comment.BatchTopByParentID(ctx, ex, ids, p.childTop, p.childOrder...)
	} else {
		// Unordered: the rows are bucketed into a map by parent, so a
		// server-side sort is paid and then destroyed. ChildOrder still
		// applies when given — order WITHIN a parent survives bucketing.
		cq := comment.New().Unordered().Where(comment.ParentID.In(ids...)).Limit(p.childLimit)
		if len(p.childOrder) > 0 {
			cq = cq.Order(p.childOrder...)
		}
		kids, err = cq.All(ctx, ex, nil)
	}
	if err != nil {
		return nil, err
	}
	// A partial relation load is worse than a failed one: every count
	// computed from it is wrong and nothing says so. A per-parent load
	// is bounded by construction, so the global guard does not apply.
	if p.childTop == 0 && int64(len(kids)) >= p.childLimit {
		return nil, runtime.ErrChildLimit
	}
	for _, k := range kids {
		key, ok := k.ParentID.Get()
		if !ok {
			continue
		}
		if i, ok := at[key]; ok {
			out[i].Replies = append(out[i].Replies, k)
		}
	}
	return out, nil
}

// OrgWithChildrenRow is orgs with its Children loaded.
//
// Children is a field HERE and nowhere else: org.Row has no such field, so an
// unloaded relation is not an empty slice, not a lazy fetch and not a
// lint warning — it does not compile.
type OrgWithChildrenRow struct {
	org.Row
	Children []org.Row
}

// OrgWithChildrenQuery builds the plan. Every builder method is redeclared rather than
// embedded: Go has no delegation, and an embedded Query would return
// itself from Where(), dropping straight out of the plan.
type OrgWithChildrenQuery struct {
	q          org.Query
	childLimit int64
	childOrder []org.Sort
	childTop   int64
}

// OrgWithChildren starts the plan.
func OrgWithChildren() OrgWithChildrenQuery {
	return OrgWithChildrenQuery{q: org.New(), childLimit: defaultChildLimit}
}

func (p OrgWithChildrenQuery) Where(ps ...org.Pred) OrgWithChildrenQuery {
	p.q = p.q.Where(ps...)
	return p
}

func (p OrgWithChildrenQuery) WhereIf(cond bool, pr org.Pred) OrgWithChildrenQuery {
	p.q = p.q.WhereIf(cond, pr)
	return p
}

func (p OrgWithChildrenQuery) Any(ps ...org.Pred) OrgWithChildrenQuery {
	p.q = p.q.Any(ps...)
	return p
}

func (p OrgWithChildrenQuery) Not(pr org.Pred) OrgWithChildrenQuery {
	p.q = p.q.Not(pr)
	return p
}

func (p OrgWithChildrenQuery) NotAny(ps ...org.Pred) OrgWithChildrenQuery {
	p.q = p.q.NotAny(ps...)
	return p
}

func (p OrgWithChildrenQuery) Order(ts ...org.Sort) OrgWithChildrenQuery {
	p.q = p.q.Order(ts...)
	return p
}

func (p OrgWithChildrenQuery) Limit(n int64) OrgWithChildrenQuery {
	p.q = p.q.Limit(n)
	return p
}

func (p OrgWithChildrenQuery) Offset(n int64) OrgWithChildrenQuery {
	p.q = p.q.Offset(n)
	return p
}

// After pages the PARENTS past one already seen — keyset pagination over
// the plan. It takes the plan's row type, so the cursor is a row you
// actually received rather than one you had to unwrap.
func (p OrgWithChildrenQuery) After(r OrgWithChildrenRow) OrgWithChildrenQuery {
	p.q = p.q.After(r.Row)
	return p
}

// Err reports a parent query that outgrew its buffers or was given a
// mixed ordering to page. Terminals return it too; this is for checking
// a composed plan before running it.
func (p OrgWithChildrenQuery) Err() error { return p.q.Err() }

// ChildLimit caps the total children fetched ACROSS ALL PARENTS.
//
// It is a guard, not a page size. Fifty parents with ChildLimit(100) is
// an error, not a hundred children each — the two queries fetch every
// child of every matched parent in one batch, and the limit only exists
// so that batch cannot silently come back partial.
//
// THERE IS NO PER-PARENT LIMIT. "Each parent with its first twenty
// children" is greatest-n-per-group, and doing it in two round trips
// needs LATERAL or row_number(); slicing in Go after the fact would
// fetch everything and only look like a limit. It is not built yet.
//
// To page ONE parent's children — the common case — query the child
// table directly, where Order, After and Limit all work:
//
//	org.New().Where(org.ParentID.Eq(id)).Order(...).After(last).Limit(20)
func (p OrgWithChildrenQuery) ChildLimit(n int64) OrgWithChildrenQuery {
	p.childLimit = n
	return p
}

// ChildTop keeps at most n children PER PARENT — greatest-n-per-group,
// still two round trips.
//
// This is the per-parent limit ChildLimit is not. "Fifty tenants, each
// with its five newest people" is one query, not fifty, because the
// limit is expressed in SQL rather than by looping or by slicing
// afterwards — slicing would fetch every child and only look like a
// limit.
//
// It REQUIRES ChildOrder, and that ordering must be a strict total order.
// "The first three by date" with ties on that date returns an arbitrary
// three, and a different arbitrary three next call — a bug that only
// appears under data the developer did not have. Add the child's primary
// key as a final term if the natural ordering is not unique.
func (p OrgWithChildrenQuery) ChildTop(n int64) OrgWithChildrenQuery {
	p.childTop = n
	return p
}

// ChildOrder orders the children within each parent.
//
// Without it they arrive in the child table's default order, which is its
// primary key — defined, but almost never what a caller wanted to show.
func (p OrgWithChildrenQuery) ChildOrder(ts ...org.Sort) OrgWithChildrenQuery {
	p.childOrder = ts
	return p
}

// All runs the plan in exactly TWO round trips, whatever the parent count.
//
// The mechanism is `= ANY($1)`: one placeholder binds the whole id list, so
// fifty parents and five thousand produce the same SQL and share one
// compiled statement. No join is involved, which is why M3 was never
// actually blocked on join support.
func (p OrgWithChildrenQuery) All(ctx context.Context, ex runtime.Executor) ([]OrgWithChildrenRow, error) {
	parents, err := p.q.All(ctx, ex, nil)
	if err != nil {
		return nil, err
	}
	if len(parents) == 0 {
		// Round two would be `= ANY('{}')`, a guaranteed-empty query. Not
		// issuing it is the difference between costing 2 round trips when
		// there is work and 2 when there is none.
		return nil, nil
	}
	out := make([]OrgWithChildrenRow, len(parents))
	ids := make([][16]byte, len(parents))
	at := make(map[[16]byte]int, len(parents))
	for i, r := range parents {
		out[i] = OrgWithChildrenRow{Row: r}
		ids[i] = r.ID
		at[r.ID] = i
	}
	var kids []org.Row
	if p.childTop > 0 {
		// Per-parent limit: one query with the limit expressed in SQL.
		kids, err = org.BatchTopByParentID(ctx, ex, ids, p.childTop, p.childOrder...)
	} else {
		// Unordered: the rows are bucketed into a map by parent, so a
		// server-side sort is paid and then destroyed. ChildOrder still
		// applies when given — order WITHIN a parent survives bucketing.
		cq := org.New().Unordered().Where(org.ParentID.In(ids...)).Limit(p.childLimit)
		if len(p.childOrder) > 0 {
			cq = cq.Order(p.childOrder...)
		}
		kids, err = cq.All(ctx, ex, nil)
	}
	if err != nil {
		return nil, err
	}
	// A partial relation load is worse than a failed one: every count
	// computed from it is wrong and nothing says so. A per-parent load
	// is bounded by construction, so the global guard does not apply.
	if p.childTop == 0 && int64(len(kids)) >= p.childLimit {
		return nil, runtime.ErrChildLimit
	}
	for _, k := range kids {
		key, ok := k.ParentID.Get()
		if !ok {
			continue
		}
		if i, ok := at[key]; ok {
			out[i].Children = append(out[i].Children, k)
		}
	}
	return out, nil
}

// OrgWithParentRow is orgs with its Parent loaded.
type OrgWithParentRow struct {
	org.Row
	// A pointer because the link is optional. nil means the row has no
	// Parent, which is different from having one that failed to load.
	Parent *org.Row
}

type OrgWithParentQuery struct {
	q org.Query
}

// OrgWithParent starts the plan.
func OrgWithParent() OrgWithParentQuery { return OrgWithParentQuery{q: org.New()} }

func (p OrgWithParentQuery) Where(ps ...org.Pred) OrgWithParentQuery {
	p.q = p.q.Where(ps...)
	return p
}

func (p OrgWithParentQuery) WhereIf(cond bool, pr org.Pred) OrgWithParentQuery {
	p.q = p.q.WhereIf(cond, pr)
	return p
}

func (p OrgWithParentQuery) Any(ps ...org.Pred) OrgWithParentQuery {
	p.q = p.q.Any(ps...)
	return p
}

func (p OrgWithParentQuery) Not(pr org.Pred) OrgWithParentQuery {
	p.q = p.q.Not(pr)
	return p
}

func (p OrgWithParentQuery) NotAny(ps ...org.Pred) OrgWithParentQuery {
	p.q = p.q.NotAny(ps...)
	return p
}

func (p OrgWithParentQuery) Order(ts ...org.Sort) OrgWithParentQuery {
	p.q = p.q.Order(ts...)
	return p
}

func (p OrgWithParentQuery) Limit(n int64) OrgWithParentQuery {
	p.q = p.q.Limit(n)
	return p
}

func (p OrgWithParentQuery) Offset(n int64) OrgWithParentQuery {
	p.q = p.q.Offset(n)
	return p
}

// After pages the PARENTS past one already seen — keyset pagination over
// the plan. It takes the plan's row type, so the cursor is a row you
// actually received rather than one you had to unwrap.
func (p OrgWithParentQuery) After(r OrgWithParentRow) OrgWithParentQuery {
	p.q = p.q.After(r.Row)
	return p
}

// Err reports a parent query that outgrew its buffers or was given a
// mixed ordering to page. Terminals return it too; this is for checking
// a composed plan before running it.
func (p OrgWithParentQuery) Err() error { return p.q.Err() }

// All runs the plan in exactly TWO round trips. Distinct parent keys are
// de-duplicated before the second, so a thousand rows pointing at three
// orgs fetch three orgs.
func (p OrgWithParentQuery) All(ctx context.Context, ex runtime.Executor) ([]OrgWithParentRow, error) {
	parents, err := p.q.All(ctx, ex, nil)
	if err != nil {
		return nil, err
	}
	if len(parents) == 0 {
		return nil, nil
	}
	out := make([]OrgWithParentRow, len(parents))
	seen := make(map[[16]byte]bool, len(parents))
	ids := make([][16]byte, 0, len(parents))
	for i, r := range parents {
		out[i] = OrgWithParentRow{Row: r}
		key, ok := r.ParentID.Get()
		if !ok {
			continue
		}
		if !seen[key] {
			seen[key] = true
			ids = append(ids, key)
		}
	}
	if len(ids) == 0 {
		return out, nil
	}
	targets, err := org.New().Unordered().
		Where(org.ID.In(ids...)).
		Limit(int64(len(ids))).
		All(ctx, ex, nil)
	if err != nil {
		return nil, err
	}
	by := make(map[[16]byte]int, len(targets))
	for i := range targets {
		by[targets[i].ID] = i
	}
	for i := range out {
		key, ok := out[i].ParentID.Get()
		if !ok {
			continue
		}
		j, ok := by[key]
		if !ok {
			// A foreign key pointing at a row that is not there. The database
			// forbids it, so reaching this means the constraint was dropped.
			return nil, fmt.Errorf("raorm: %s references a missing %s row", "orgs", "orgs")
		}
		out[i].Parent = &targets[j]
	}
	return out, nil
}

// OrgWithUsersRow is orgs with its Users loaded.
//
// Users is a field HERE and nowhere else: org.Row has no such field, so an
// unloaded relation is not an empty slice, not a lazy fetch and not a
// lint warning — it does not compile.
type OrgWithUsersRow struct {
	org.Row
	Users []user.Row
}

// OrgWithUsersQuery builds the plan. Every builder method is redeclared rather than
// embedded: Go has no delegation, and an embedded Query would return
// itself from Where(), dropping straight out of the plan.
type OrgWithUsersQuery struct {
	q          org.Query
	childLimit int64
	childOrder []user.Sort
	childTop   int64
}

// OrgWithUsers starts the plan.
func OrgWithUsers() OrgWithUsersQuery {
	return OrgWithUsersQuery{q: org.New(), childLimit: defaultChildLimit}
}

func (p OrgWithUsersQuery) Where(ps ...org.Pred) OrgWithUsersQuery {
	p.q = p.q.Where(ps...)
	return p
}

func (p OrgWithUsersQuery) WhereIf(cond bool, pr org.Pred) OrgWithUsersQuery {
	p.q = p.q.WhereIf(cond, pr)
	return p
}

func (p OrgWithUsersQuery) Any(ps ...org.Pred) OrgWithUsersQuery {
	p.q = p.q.Any(ps...)
	return p
}

func (p OrgWithUsersQuery) Not(pr org.Pred) OrgWithUsersQuery {
	p.q = p.q.Not(pr)
	return p
}

func (p OrgWithUsersQuery) NotAny(ps ...org.Pred) OrgWithUsersQuery {
	p.q = p.q.NotAny(ps...)
	return p
}

func (p OrgWithUsersQuery) Order(ts ...org.Sort) OrgWithUsersQuery {
	p.q = p.q.Order(ts...)
	return p
}

func (p OrgWithUsersQuery) Limit(n int64) OrgWithUsersQuery {
	p.q = p.q.Limit(n)
	return p
}

func (p OrgWithUsersQuery) Offset(n int64) OrgWithUsersQuery {
	p.q = p.q.Offset(n)
	return p
}

// After pages the PARENTS past one already seen — keyset pagination over
// the plan. It takes the plan's row type, so the cursor is a row you
// actually received rather than one you had to unwrap.
func (p OrgWithUsersQuery) After(r OrgWithUsersRow) OrgWithUsersQuery {
	p.q = p.q.After(r.Row)
	return p
}

// Err reports a parent query that outgrew its buffers or was given a
// mixed ordering to page. Terminals return it too; this is for checking
// a composed plan before running it.
func (p OrgWithUsersQuery) Err() error { return p.q.Err() }

// ChildLimit caps the total children fetched ACROSS ALL PARENTS.
//
// It is a guard, not a page size. Fifty parents with ChildLimit(100) is
// an error, not a hundred children each — the two queries fetch every
// child of every matched parent in one batch, and the limit only exists
// so that batch cannot silently come back partial.
//
// THERE IS NO PER-PARENT LIMIT. "Each parent with its first twenty
// children" is greatest-n-per-group, and doing it in two round trips
// needs LATERAL or row_number(); slicing in Go after the fact would
// fetch everything and only look like a limit. It is not built yet.
//
// To page ONE parent's children — the common case — query the child
// table directly, where Order, After and Limit all work:
//
//	user.New().Where(user.OrgID.Eq(id)).Order(...).After(last).Limit(20)
func (p OrgWithUsersQuery) ChildLimit(n int64) OrgWithUsersQuery {
	p.childLimit = n
	return p
}

// ChildTop keeps at most n children PER PARENT — greatest-n-per-group,
// still two round trips.
//
// This is the per-parent limit ChildLimit is not. "Fifty tenants, each
// with its five newest people" is one query, not fifty, because the
// limit is expressed in SQL rather than by looping or by slicing
// afterwards — slicing would fetch every child and only look like a
// limit.
//
// It REQUIRES ChildOrder, and that ordering must be a strict total order.
// "The first three by date" with ties on that date returns an arbitrary
// three, and a different arbitrary three next call — a bug that only
// appears under data the developer did not have. Add the child's primary
// key as a final term if the natural ordering is not unique.
func (p OrgWithUsersQuery) ChildTop(n int64) OrgWithUsersQuery {
	p.childTop = n
	return p
}

// ChildOrder orders the children within each parent.
//
// Without it they arrive in the child table's default order, which is its
// primary key — defined, but almost never what a caller wanted to show.
func (p OrgWithUsersQuery) ChildOrder(ts ...user.Sort) OrgWithUsersQuery {
	p.childOrder = ts
	return p
}

// All runs the plan in exactly TWO round trips, whatever the parent count.
//
// The mechanism is `= ANY($1)`: one placeholder binds the whole id list, so
// fifty parents and five thousand produce the same SQL and share one
// compiled statement. No join is involved, which is why M3 was never
// actually blocked on join support.
func (p OrgWithUsersQuery) All(ctx context.Context, ex runtime.Executor) ([]OrgWithUsersRow, error) {
	parents, err := p.q.All(ctx, ex, nil)
	if err != nil {
		return nil, err
	}
	if len(parents) == 0 {
		// Round two would be `= ANY('{}')`, a guaranteed-empty query. Not
		// issuing it is the difference between costing 2 round trips when
		// there is work and 2 when there is none.
		return nil, nil
	}
	out := make([]OrgWithUsersRow, len(parents))
	ids := make([][16]byte, len(parents))
	at := make(map[[16]byte]int, len(parents))
	for i, r := range parents {
		out[i] = OrgWithUsersRow{Row: r}
		ids[i] = r.ID
		at[r.ID] = i
	}
	var kids []user.Row
	if p.childTop > 0 {
		// Per-parent limit: one query with the limit expressed in SQL.
		kids, err = user.BatchTopByOrgID(ctx, ex, ids, p.childTop, p.childOrder...)
	} else {
		// Unordered: the rows are bucketed into a map by parent, so a
		// server-side sort is paid and then destroyed. ChildOrder still
		// applies when given — order WITHIN a parent survives bucketing.
		cq := user.New().Unordered().Where(user.OrgID.In(ids...)).Limit(p.childLimit)
		if len(p.childOrder) > 0 {
			cq = cq.Order(p.childOrder...)
		}
		kids, err = cq.All(ctx, ex, nil)
	}
	if err != nil {
		return nil, err
	}
	// A partial relation load is worse than a failed one: every count
	// computed from it is wrong and nothing says so. A per-parent load
	// is bounded by construction, so the global guard does not apply.
	if p.childTop == 0 && int64(len(kids)) >= p.childLimit {
		return nil, runtime.ErrChildLimit
	}
	for _, k := range kids {
		if i, ok := at[k.OrgID]; ok {
			out[i].Users = append(out[i].Users, k)
		}
	}
	return out, nil
}

// PostWithAuthorRow is posts with its Author loaded.
type PostWithAuthorRow struct {
	post.Row
	Author user.Row
}

type PostWithAuthorQuery struct {
	q post.Query
}

// PostWithAuthor starts the plan.
func PostWithAuthor() PostWithAuthorQuery { return PostWithAuthorQuery{q: post.New()} }

func (p PostWithAuthorQuery) Where(ps ...post.Pred) PostWithAuthorQuery {
	p.q = p.q.Where(ps...)
	return p
}

func (p PostWithAuthorQuery) WhereIf(cond bool, pr post.Pred) PostWithAuthorQuery {
	p.q = p.q.WhereIf(cond, pr)
	return p
}

func (p PostWithAuthorQuery) Any(ps ...post.Pred) PostWithAuthorQuery {
	p.q = p.q.Any(ps...)
	return p
}

func (p PostWithAuthorQuery) Not(pr post.Pred) PostWithAuthorQuery {
	p.q = p.q.Not(pr)
	return p
}

func (p PostWithAuthorQuery) NotAny(ps ...post.Pred) PostWithAuthorQuery {
	p.q = p.q.NotAny(ps...)
	return p
}

func (p PostWithAuthorQuery) Order(ts ...post.Sort) PostWithAuthorQuery {
	p.q = p.q.Order(ts...)
	return p
}

func (p PostWithAuthorQuery) Limit(n int64) PostWithAuthorQuery {
	p.q = p.q.Limit(n)
	return p
}

func (p PostWithAuthorQuery) Offset(n int64) PostWithAuthorQuery {
	p.q = p.q.Offset(n)
	return p
}

// After pages the PARENTS past one already seen — keyset pagination over
// the plan. It takes the plan's row type, so the cursor is a row you
// actually received rather than one you had to unwrap.
func (p PostWithAuthorQuery) After(r PostWithAuthorRow) PostWithAuthorQuery {
	p.q = p.q.After(r.Row)
	return p
}

// Err reports a parent query that outgrew its buffers or was given a
// mixed ordering to page. Terminals return it too; this is for checking
// a composed plan before running it.
func (p PostWithAuthorQuery) Err() error { return p.q.Err() }

// All runs the plan in exactly TWO round trips. Distinct parent keys are
// de-duplicated before the second, so a thousand rows pointing at three
// orgs fetch three orgs.
func (p PostWithAuthorQuery) All(ctx context.Context, ex runtime.Executor) ([]PostWithAuthorRow, error) {
	parents, err := p.q.All(ctx, ex, nil)
	if err != nil {
		return nil, err
	}
	if len(parents) == 0 {
		return nil, nil
	}
	out := make([]PostWithAuthorRow, len(parents))
	seen := make(map[[16]byte]bool, len(parents))
	ids := make([][16]byte, 0, len(parents))
	for i, r := range parents {
		out[i] = PostWithAuthorRow{Row: r}
		key := r.AuthorID
		if !seen[key] {
			seen[key] = true
			ids = append(ids, key)
		}
	}
	if len(ids) == 0 {
		return out, nil
	}
	targets, err := user.New().Unordered().
		Where(user.ID.In(ids...)).
		Limit(int64(len(ids))).
		All(ctx, ex, nil)
	if err != nil {
		return nil, err
	}
	by := make(map[[16]byte]int, len(targets))
	for i := range targets {
		by[targets[i].ID] = i
	}
	for i := range out {
		key := out[i].AuthorID
		j, ok := by[key]
		if !ok {
			// A foreign key pointing at a row that is not there. The database
			// forbids it, so reaching this means the constraint was dropped.
			return nil, fmt.Errorf("raorm: %s references a missing %s row", "posts", "users")
		}
		out[i].Author = targets[j]
	}
	return out, nil
}

// PostWithCommentsRow is posts with its Comments loaded.
//
// Comments is a field HERE and nowhere else: post.Row has no such field, so an
// unloaded relation is not an empty slice, not a lazy fetch and not a
// lint warning — it does not compile.
type PostWithCommentsRow struct {
	post.Row
	Comments []comment.Row
}

// PostWithCommentsQuery builds the plan. Every builder method is redeclared rather than
// embedded: Go has no delegation, and an embedded Query would return
// itself from Where(), dropping straight out of the plan.
type PostWithCommentsQuery struct {
	q          post.Query
	childLimit int64
	childOrder []comment.Sort
	childTop   int64
}

// PostWithComments starts the plan.
func PostWithComments() PostWithCommentsQuery {
	return PostWithCommentsQuery{q: post.New(), childLimit: defaultChildLimit}
}

func (p PostWithCommentsQuery) Where(ps ...post.Pred) PostWithCommentsQuery {
	p.q = p.q.Where(ps...)
	return p
}

func (p PostWithCommentsQuery) WhereIf(cond bool, pr post.Pred) PostWithCommentsQuery {
	p.q = p.q.WhereIf(cond, pr)
	return p
}

func (p PostWithCommentsQuery) Any(ps ...post.Pred) PostWithCommentsQuery {
	p.q = p.q.Any(ps...)
	return p
}

func (p PostWithCommentsQuery) Not(pr post.Pred) PostWithCommentsQuery {
	p.q = p.q.Not(pr)
	return p
}

func (p PostWithCommentsQuery) NotAny(ps ...post.Pred) PostWithCommentsQuery {
	p.q = p.q.NotAny(ps...)
	return p
}

func (p PostWithCommentsQuery) Order(ts ...post.Sort) PostWithCommentsQuery {
	p.q = p.q.Order(ts...)
	return p
}

func (p PostWithCommentsQuery) Limit(n int64) PostWithCommentsQuery {
	p.q = p.q.Limit(n)
	return p
}

func (p PostWithCommentsQuery) Offset(n int64) PostWithCommentsQuery {
	p.q = p.q.Offset(n)
	return p
}

// After pages the PARENTS past one already seen — keyset pagination over
// the plan. It takes the plan's row type, so the cursor is a row you
// actually received rather than one you had to unwrap.
func (p PostWithCommentsQuery) After(r PostWithCommentsRow) PostWithCommentsQuery {
	p.q = p.q.After(r.Row)
	return p
}

// Err reports a parent query that outgrew its buffers or was given a
// mixed ordering to page. Terminals return it too; this is for checking
// a composed plan before running it.
func (p PostWithCommentsQuery) Err() error { return p.q.Err() }

// ChildLimit caps the total children fetched ACROSS ALL PARENTS.
//
// It is a guard, not a page size. Fifty parents with ChildLimit(100) is
// an error, not a hundred children each — the two queries fetch every
// child of every matched parent in one batch, and the limit only exists
// so that batch cannot silently come back partial.
//
// THERE IS NO PER-PARENT LIMIT. "Each parent with its first twenty
// children" is greatest-n-per-group, and doing it in two round trips
// needs LATERAL or row_number(); slicing in Go after the fact would
// fetch everything and only look like a limit. It is not built yet.
//
// To page ONE parent's children — the common case — query the child
// table directly, where Order, After and Limit all work:
//
//	comment.New().Where(comment.PostID.Eq(id)).Order(...).After(last).Limit(20)
func (p PostWithCommentsQuery) ChildLimit(n int64) PostWithCommentsQuery {
	p.childLimit = n
	return p
}

// ChildTop keeps at most n children PER PARENT — greatest-n-per-group,
// still two round trips.
//
// This is the per-parent limit ChildLimit is not. "Fifty tenants, each
// with its five newest people" is one query, not fifty, because the
// limit is expressed in SQL rather than by looping or by slicing
// afterwards — slicing would fetch every child and only look like a
// limit.
//
// It REQUIRES ChildOrder, and that ordering must be a strict total order.
// "The first three by date" with ties on that date returns an arbitrary
// three, and a different arbitrary three next call — a bug that only
// appears under data the developer did not have. Add the child's primary
// key as a final term if the natural ordering is not unique.
func (p PostWithCommentsQuery) ChildTop(n int64) PostWithCommentsQuery {
	p.childTop = n
	return p
}

// ChildOrder orders the children within each parent.
//
// Without it they arrive in the child table's default order, which is its
// primary key — defined, but almost never what a caller wanted to show.
func (p PostWithCommentsQuery) ChildOrder(ts ...comment.Sort) PostWithCommentsQuery {
	p.childOrder = ts
	return p
}

// All runs the plan in exactly TWO round trips, whatever the parent count.
//
// The mechanism is `= ANY($1)`: one placeholder binds the whole id list, so
// fifty parents and five thousand produce the same SQL and share one
// compiled statement. No join is involved, which is why M3 was never
// actually blocked on join support.
func (p PostWithCommentsQuery) All(ctx context.Context, ex runtime.Executor) ([]PostWithCommentsRow, error) {
	parents, err := p.q.All(ctx, ex, nil)
	if err != nil {
		return nil, err
	}
	if len(parents) == 0 {
		// Round two would be `= ANY('{}')`, a guaranteed-empty query. Not
		// issuing it is the difference between costing 2 round trips when
		// there is work and 2 when there is none.
		return nil, nil
	}
	out := make([]PostWithCommentsRow, len(parents))
	ids := make([][16]byte, len(parents))
	at := make(map[[16]byte]int, len(parents))
	for i, r := range parents {
		out[i] = PostWithCommentsRow{Row: r}
		ids[i] = r.ID
		at[r.ID] = i
	}
	var kids []comment.Row
	if p.childTop > 0 {
		// Per-parent limit: one query with the limit expressed in SQL.
		kids, err = comment.BatchTopByPostID(ctx, ex, ids, p.childTop, p.childOrder...)
	} else {
		// Unordered: the rows are bucketed into a map by parent, so a
		// server-side sort is paid and then destroyed. ChildOrder still
		// applies when given — order WITHIN a parent survives bucketing.
		cq := comment.New().Unordered().Where(comment.PostID.In(ids...)).Limit(p.childLimit)
		if len(p.childOrder) > 0 {
			cq = cq.Order(p.childOrder...)
		}
		kids, err = cq.All(ctx, ex, nil)
	}
	if err != nil {
		return nil, err
	}
	// A partial relation load is worse than a failed one: every count
	// computed from it is wrong and nothing says so. A per-parent load
	// is bounded by construction, so the global guard does not apply.
	if p.childTop == 0 && int64(len(kids)) >= p.childLimit {
		return nil, runtime.ErrChildLimit
	}
	for _, k := range kids {
		if i, ok := at[k.PostID]; ok {
			out[i].Comments = append(out[i].Comments, k)
		}
	}
	return out, nil
}

// UserWithOrgRow is users with its Org loaded.
type UserWithOrgRow struct {
	user.Row
	Org org.Row
}

type UserWithOrgQuery struct {
	q user.Query
}

// UserWithOrg starts the plan.
func UserWithOrg() UserWithOrgQuery { return UserWithOrgQuery{q: user.New()} }

func (p UserWithOrgQuery) Where(ps ...user.Pred) UserWithOrgQuery {
	p.q = p.q.Where(ps...)
	return p
}

func (p UserWithOrgQuery) WhereIf(cond bool, pr user.Pred) UserWithOrgQuery {
	p.q = p.q.WhereIf(cond, pr)
	return p
}

func (p UserWithOrgQuery) Any(ps ...user.Pred) UserWithOrgQuery {
	p.q = p.q.Any(ps...)
	return p
}

func (p UserWithOrgQuery) Not(pr user.Pred) UserWithOrgQuery {
	p.q = p.q.Not(pr)
	return p
}

func (p UserWithOrgQuery) NotAny(ps ...user.Pred) UserWithOrgQuery {
	p.q = p.q.NotAny(ps...)
	return p
}

func (p UserWithOrgQuery) Order(ts ...user.Sort) UserWithOrgQuery {
	p.q = p.q.Order(ts...)
	return p
}

func (p UserWithOrgQuery) Limit(n int64) UserWithOrgQuery {
	p.q = p.q.Limit(n)
	return p
}

func (p UserWithOrgQuery) Offset(n int64) UserWithOrgQuery {
	p.q = p.q.Offset(n)
	return p
}

// After pages the PARENTS past one already seen — keyset pagination over
// the plan. It takes the plan's row type, so the cursor is a row you
// actually received rather than one you had to unwrap.
func (p UserWithOrgQuery) After(r UserWithOrgRow) UserWithOrgQuery {
	p.q = p.q.After(r.Row)
	return p
}

// Err reports a parent query that outgrew its buffers or was given a
// mixed ordering to page. Terminals return it too; this is for checking
// a composed plan before running it.
func (p UserWithOrgQuery) Err() error { return p.q.Err() }

// All runs the plan in exactly TWO round trips. Distinct parent keys are
// de-duplicated before the second, so a thousand rows pointing at three
// orgs fetch three orgs.
func (p UserWithOrgQuery) All(ctx context.Context, ex runtime.Executor) ([]UserWithOrgRow, error) {
	parents, err := p.q.All(ctx, ex, nil)
	if err != nil {
		return nil, err
	}
	if len(parents) == 0 {
		return nil, nil
	}
	out := make([]UserWithOrgRow, len(parents))
	seen := make(map[[16]byte]bool, len(parents))
	ids := make([][16]byte, 0, len(parents))
	for i, r := range parents {
		out[i] = UserWithOrgRow{Row: r}
		key := r.OrgID
		if !seen[key] {
			seen[key] = true
			ids = append(ids, key)
		}
	}
	if len(ids) == 0 {
		return out, nil
	}
	targets, err := org.New().Unordered().
		Where(org.ID.In(ids...)).
		Limit(int64(len(ids))).
		All(ctx, ex, nil)
	if err != nil {
		return nil, err
	}
	by := make(map[[16]byte]int, len(targets))
	for i := range targets {
		by[targets[i].ID] = i
	}
	for i := range out {
		key := out[i].OrgID
		j, ok := by[key]
		if !ok {
			// A foreign key pointing at a row that is not there. The database
			// forbids it, so reaching this means the constraint was dropped.
			return nil, fmt.Errorf("raorm: %s references a missing %s row", "users", "orgs")
		}
		out[i].Org = targets[j]
	}
	return out, nil
}

// UserWithPostsRow is users with its Posts loaded.
//
// Posts is a field HERE and nowhere else: user.Row has no such field, so an
// unloaded relation is not an empty slice, not a lazy fetch and not a
// lint warning — it does not compile.
type UserWithPostsRow struct {
	user.Row
	Posts []post.Row
}

// UserWithPostsQuery builds the plan. Every builder method is redeclared rather than
// embedded: Go has no delegation, and an embedded Query would return
// itself from Where(), dropping straight out of the plan.
type UserWithPostsQuery struct {
	q          user.Query
	childLimit int64
	childOrder []post.Sort
	childTop   int64
}

// UserWithPosts starts the plan.
func UserWithPosts() UserWithPostsQuery {
	return UserWithPostsQuery{q: user.New(), childLimit: defaultChildLimit}
}

func (p UserWithPostsQuery) Where(ps ...user.Pred) UserWithPostsQuery {
	p.q = p.q.Where(ps...)
	return p
}

func (p UserWithPostsQuery) WhereIf(cond bool, pr user.Pred) UserWithPostsQuery {
	p.q = p.q.WhereIf(cond, pr)
	return p
}

func (p UserWithPostsQuery) Any(ps ...user.Pred) UserWithPostsQuery {
	p.q = p.q.Any(ps...)
	return p
}

func (p UserWithPostsQuery) Not(pr user.Pred) UserWithPostsQuery {
	p.q = p.q.Not(pr)
	return p
}

func (p UserWithPostsQuery) NotAny(ps ...user.Pred) UserWithPostsQuery {
	p.q = p.q.NotAny(ps...)
	return p
}

func (p UserWithPostsQuery) Order(ts ...user.Sort) UserWithPostsQuery {
	p.q = p.q.Order(ts...)
	return p
}

func (p UserWithPostsQuery) Limit(n int64) UserWithPostsQuery {
	p.q = p.q.Limit(n)
	return p
}

func (p UserWithPostsQuery) Offset(n int64) UserWithPostsQuery {
	p.q = p.q.Offset(n)
	return p
}

// After pages the PARENTS past one already seen — keyset pagination over
// the plan. It takes the plan's row type, so the cursor is a row you
// actually received rather than one you had to unwrap.
func (p UserWithPostsQuery) After(r UserWithPostsRow) UserWithPostsQuery {
	p.q = p.q.After(r.Row)
	return p
}

// Err reports a parent query that outgrew its buffers or was given a
// mixed ordering to page. Terminals return it too; this is for checking
// a composed plan before running it.
func (p UserWithPostsQuery) Err() error { return p.q.Err() }

// ChildLimit caps the total children fetched ACROSS ALL PARENTS.
//
// It is a guard, not a page size. Fifty parents with ChildLimit(100) is
// an error, not a hundred children each — the two queries fetch every
// child of every matched parent in one batch, and the limit only exists
// so that batch cannot silently come back partial.
//
// THERE IS NO PER-PARENT LIMIT. "Each parent with its first twenty
// children" is greatest-n-per-group, and doing it in two round trips
// needs LATERAL or row_number(); slicing in Go after the fact would
// fetch everything and only look like a limit. It is not built yet.
//
// To page ONE parent's children — the common case — query the child
// table directly, where Order, After and Limit all work:
//
//	post.New().Where(post.AuthorID.Eq(id)).Order(...).After(last).Limit(20)
func (p UserWithPostsQuery) ChildLimit(n int64) UserWithPostsQuery {
	p.childLimit = n
	return p
}

// ChildTop keeps at most n children PER PARENT — greatest-n-per-group,
// still two round trips.
//
// This is the per-parent limit ChildLimit is not. "Fifty tenants, each
// with its five newest people" is one query, not fifty, because the
// limit is expressed in SQL rather than by looping or by slicing
// afterwards — slicing would fetch every child and only look like a
// limit.
//
// It REQUIRES ChildOrder, and that ordering must be a strict total order.
// "The first three by date" with ties on that date returns an arbitrary
// three, and a different arbitrary three next call — a bug that only
// appears under data the developer did not have. Add the child's primary
// key as a final term if the natural ordering is not unique.
func (p UserWithPostsQuery) ChildTop(n int64) UserWithPostsQuery {
	p.childTop = n
	return p
}

// ChildOrder orders the children within each parent.
//
// Without it they arrive in the child table's default order, which is its
// primary key — defined, but almost never what a caller wanted to show.
func (p UserWithPostsQuery) ChildOrder(ts ...post.Sort) UserWithPostsQuery {
	p.childOrder = ts
	return p
}

// All runs the plan in exactly TWO round trips, whatever the parent count.
//
// The mechanism is `= ANY($1)`: one placeholder binds the whole id list, so
// fifty parents and five thousand produce the same SQL and share one
// compiled statement. No join is involved, which is why M3 was never
// actually blocked on join support.
func (p UserWithPostsQuery) All(ctx context.Context, ex runtime.Executor) ([]UserWithPostsRow, error) {
	parents, err := p.q.All(ctx, ex, nil)
	if err != nil {
		return nil, err
	}
	if len(parents) == 0 {
		// Round two would be `= ANY('{}')`, a guaranteed-empty query. Not
		// issuing it is the difference between costing 2 round trips when
		// there is work and 2 when there is none.
		return nil, nil
	}
	out := make([]UserWithPostsRow, len(parents))
	ids := make([][16]byte, len(parents))
	at := make(map[[16]byte]int, len(parents))
	for i, r := range parents {
		out[i] = UserWithPostsRow{Row: r}
		ids[i] = r.ID
		at[r.ID] = i
	}
	var kids []post.Row
	if p.childTop > 0 {
		// Per-parent limit: one query with the limit expressed in SQL.
		kids, err = post.BatchTopByAuthorID(ctx, ex, ids, p.childTop, p.childOrder...)
	} else {
		// Unordered: the rows are bucketed into a map by parent, so a
		// server-side sort is paid and then destroyed. ChildOrder still
		// applies when given — order WITHIN a parent survives bucketing.
		cq := post.New().Unordered().Where(post.AuthorID.In(ids...)).Limit(p.childLimit)
		if len(p.childOrder) > 0 {
			cq = cq.Order(p.childOrder...)
		}
		kids, err = cq.All(ctx, ex, nil)
	}
	if err != nil {
		return nil, err
	}
	// A partial relation load is worse than a failed one: every count
	// computed from it is wrong and nothing says so. A per-parent load
	// is bounded by construction, so the global guard does not apply.
	if p.childTop == 0 && int64(len(kids)) >= p.childLimit {
		return nil, runtime.ErrChildLimit
	}
	for _, k := range kids {
		if i, ok := at[k.AuthorID]; ok {
			out[i].Posts = append(out[i].Posts, k)
		}
	}
	return out, nil
}

// OrgTreeRow is orgs with 2 relation(s) loaded.
//
// One type per DECLARED plan. Generating a type per With(...)
// combination would be 2^n per entity; you get the plans you named.
type OrgTreeRow struct {
	org.Row
	Children []org.Row
	Users    []user.Row
}

type OrgTreeQuery struct {
	q          org.Query
	childLimit int64
}

// OrgTree starts the plan. It costs 3 round trips: one for the parents and
// one per relation, whatever the row count.
func OrgTree() OrgTreeQuery {
	return OrgTreeQuery{q: org.New(), childLimit: defaultChildLimit}
}

func (p OrgTreeQuery) Where(ps ...org.Pred) OrgTreeQuery {
	p.q = p.q.Where(ps...)
	return p
}

func (p OrgTreeQuery) WhereIf(cond bool, pr org.Pred) OrgTreeQuery {
	p.q = p.q.WhereIf(cond, pr)
	return p
}

func (p OrgTreeQuery) Any(ps ...org.Pred) OrgTreeQuery {
	p.q = p.q.Any(ps...)
	return p
}

func (p OrgTreeQuery) Not(pr org.Pred) OrgTreeQuery {
	p.q = p.q.Not(pr)
	return p
}

func (p OrgTreeQuery) NotAny(ps ...org.Pred) OrgTreeQuery {
	p.q = p.q.NotAny(ps...)
	return p
}

func (p OrgTreeQuery) Order(ts ...org.Sort) OrgTreeQuery {
	p.q = p.q.Order(ts...)
	return p
}

func (p OrgTreeQuery) Limit(n int64) OrgTreeQuery {
	p.q = p.q.Limit(n)
	return p
}

func (p OrgTreeQuery) Offset(n int64) OrgTreeQuery {
	p.q = p.q.Offset(n)
	return p
}

// After pages the PARENTS past one already seen — keyset pagination over
// the plan. It takes the plan's row type, so the cursor is a row you
// actually received rather than one you had to unwrap.
func (p OrgTreeQuery) After(r OrgTreeRow) OrgTreeQuery {
	p.q = p.q.After(r.Row)
	return p
}

// Err reports a parent query that outgrew its buffers or was given a
// mixed ordering to page. Terminals return it too; this is for checking
// a composed plan before running it.
func (p OrgTreeQuery) Err() error { return p.q.Err() }

// ChildLimit caps each relation's fetch. A guard, not a page size.
func (p OrgTreeQuery) ChildLimit(n int64) OrgTreeQuery {
	p.childLimit = n
	return p
}

// All runs the plan in 3 round trips.
func (p OrgTreeQuery) All(ctx context.Context, ex runtime.Executor) ([]OrgTreeRow, error) {
	parents, err := p.q.All(ctx, ex, nil)
	if err != nil {
		return nil, err
	}
	if len(parents) == 0 {
		return nil, nil
	}
	out := make([]OrgTreeRow, len(parents))
	for i, r := range parents {
		out[i] = OrgTreeRow{Row: r}
	}
	if err := p.load0(ctx, ex, out); err != nil {
		return nil, err
	}
	if err := p.load1(ctx, ex, out); err != nil {
		return nil, err
	}
	return out, nil
}

// load0 fetches Children.
func (p OrgTreeQuery) load0(ctx context.Context, ex runtime.Executor, out []OrgTreeRow) error {
	ids := make([][16]byte, len(out))
	at := make(map[[16]byte]int, len(out))
	for i := range out {
		ids[i] = out[i].ID
		at[out[i].ID] = i
	}
	kids, err := org.New().Unordered().Where(org.ParentID.In(ids...)).Limit(p.childLimit).All(ctx, ex, nil)
	if err != nil {
		return err
	}
	if int64(len(kids)) >= p.childLimit {
		return runtime.ErrChildLimit
	}
	for _, k := range kids {
		key, ok := k.ParentID.Get()
		if !ok {
			continue
		}
		if j, ok := at[key]; ok {
			out[j].Children = append(out[j].Children, k)
		}
	}
	return nil
}

// load1 fetches Users.
func (p OrgTreeQuery) load1(ctx context.Context, ex runtime.Executor, out []OrgTreeRow) error {
	ids := make([][16]byte, len(out))
	at := make(map[[16]byte]int, len(out))
	for i := range out {
		ids[i] = out[i].ID
		at[out[i].ID] = i
	}
	kids, err := user.New().Unordered().Where(user.OrgID.In(ids...)).Limit(p.childLimit).All(ctx, ex, nil)
	if err != nil {
		return err
	}
	if int64(len(kids)) >= p.childLimit {
		return runtime.ErrChildLimit
	}
	for _, k := range kids {
		if j, ok := at[k.OrgID]; ok {
			out[j].Users = append(out[j].Users, k)
		}
	}
	return nil
}

// UserFeedPosts is a posts with its own relations loaded. A posts inside this plan is
// not the same type as a bare one — the extra fields exist only where
// the plan said to load them, which is the guarantee one level down.
type UserFeedPosts struct {
	post.Row
	Comments []comment.Row
}

// UserFeedRow is users with 2 relation(s) loaded.
//
// One type per DECLARED plan. Generating a type per With(...)
// combination would be 2^n per entity; you get the plans you named.
type UserFeedRow struct {
	user.Row
	Posts []UserFeedPosts
	Org   org.Row
}

type UserFeedQuery struct {
	q          user.Query
	childLimit int64
}

// UserFeed starts the plan. It costs 3 round trips: one for the parents and
// one per relation, whatever the row count.
func UserFeed() UserFeedQuery {
	return UserFeedQuery{q: user.New(), childLimit: defaultChildLimit}
}

func (p UserFeedQuery) Where(ps ...user.Pred) UserFeedQuery {
	p.q = p.q.Where(ps...)
	return p
}

func (p UserFeedQuery) WhereIf(cond bool, pr user.Pred) UserFeedQuery {
	p.q = p.q.WhereIf(cond, pr)
	return p
}

func (p UserFeedQuery) Any(ps ...user.Pred) UserFeedQuery {
	p.q = p.q.Any(ps...)
	return p
}

func (p UserFeedQuery) Not(pr user.Pred) UserFeedQuery {
	p.q = p.q.Not(pr)
	return p
}

func (p UserFeedQuery) NotAny(ps ...user.Pred) UserFeedQuery {
	p.q = p.q.NotAny(ps...)
	return p
}

func (p UserFeedQuery) Order(ts ...user.Sort) UserFeedQuery {
	p.q = p.q.Order(ts...)
	return p
}

func (p UserFeedQuery) Limit(n int64) UserFeedQuery {
	p.q = p.q.Limit(n)
	return p
}

func (p UserFeedQuery) Offset(n int64) UserFeedQuery {
	p.q = p.q.Offset(n)
	return p
}

// After pages the PARENTS past one already seen — keyset pagination over
// the plan. It takes the plan's row type, so the cursor is a row you
// actually received rather than one you had to unwrap.
func (p UserFeedQuery) After(r UserFeedRow) UserFeedQuery {
	p.q = p.q.After(r.Row)
	return p
}

// Err reports a parent query that outgrew its buffers or was given a
// mixed ordering to page. Terminals return it too; this is for checking
// a composed plan before running it.
func (p UserFeedQuery) Err() error { return p.q.Err() }

// ChildLimit caps each relation's fetch. A guard, not a page size.
func (p UserFeedQuery) ChildLimit(n int64) UserFeedQuery {
	p.childLimit = n
	return p
}

// All runs the plan in 3 round trips.
func (p UserFeedQuery) All(ctx context.Context, ex runtime.Executor) ([]UserFeedRow, error) {
	parents, err := p.q.All(ctx, ex, nil)
	if err != nil {
		return nil, err
	}
	if len(parents) == 0 {
		return nil, nil
	}
	out := make([]UserFeedRow, len(parents))
	for i, r := range parents {
		out[i] = UserFeedRow{Row: r}
	}
	if err := p.load0(ctx, ex, out); err != nil {
		return nil, err
	}
	if err := p.load1(ctx, ex, out); err != nil {
		return nil, err
	}
	return out, nil
}

// load0 fetches Posts.
func (p UserFeedQuery) load0(ctx context.Context, ex runtime.Executor, out []UserFeedRow) error {
	ids := make([][16]byte, len(out))
	at := make(map[[16]byte]int, len(out))
	for i := range out {
		ids[i] = out[i].ID
		at[out[i].ID] = i
	}
	kids, err := post.New().Unordered().Where(post.AuthorID.In(ids...)).Limit(p.childLimit).All(ctx, ex, nil)
	if err != nil {
		return err
	}
	if int64(len(kids)) >= p.childLimit {
		return runtime.ErrChildLimit
	}
	for _, k := range kids {
		if j, ok := at[k.AuthorID]; ok {
			out[j].Posts = append(out[j].Posts, UserFeedPosts{Row: k})
		}
	}
	if err := p.load0_0(ctx, ex, out); err != nil {
		return err
	}
	return nil
}

// load0_0 fetches Comments, through each Posts.
func (p UserFeedQuery) load0_0(ctx context.Context, ex runtime.Executor, out []UserFeedRow) error {
	// Every child of every parent, flattened once so the fetch is one query.
	n := 0
	for i := range out {
		n += len(out[i].Posts)
	}
	if n == 0 {
		return nil
	}
	ids := make([][16]byte, 0, n)
	type atload0_0 struct{ i, j int }
	at := make(map[[16]byte]atload0_0, n)
	for i := range out {
		for j := range out[i].Posts {
			k := out[i].Posts[j].ID
			ids = append(ids, k)
			at[k] = atload0_0{i, j}
		}
	}
	kids, err := comment.New().Unordered().Where(comment.PostID.In(ids...)).Limit(p.childLimit).All(ctx, ex, nil)
	if err != nil {
		return err
	}
	if int64(len(kids)) >= p.childLimit {
		return runtime.ErrChildLimit
	}
	for _, k := range kids {
		if a, ok := at[k.PostID]; ok {
			out[a.i].Posts[a.j].Comments = append(out[a.i].Posts[a.j].Comments, k)
		}
	}
	return nil
}

// load1 fetches Org.
func (p UserFeedQuery) load1(ctx context.Context, ex runtime.Executor, out []UserFeedRow) error {
	seen := make(map[[16]byte]bool, len(out))
	ids := make([][16]byte, 0, len(out))
	for i := range out {
		key := out[i].OrgID
		if !seen[key] {
			seen[key] = true
			ids = append(ids, key)
		}
	}
	if len(ids) == 0 {
		return nil
	}
	targets, err := org.New().Unordered().Where(org.ID.In(ids...)).Limit(int64(len(ids))).All(ctx, ex, nil)
	if err != nil {
		return err
	}
	by := make(map[[16]byte]int, len(targets))
	for i := range targets {
		by[targets[i].ID] = i
	}
	for i := range out {
		key := out[i].OrgID
		j, ok := by[key]
		if !ok {
			return fmt.Errorf("raorm: %s references a missing %s row", "users", "orgs")
		}
		out[i].Org = targets[j]
	}
	return nil
}

// UserSummaryRow is users with 1 relation(s) loaded.
//
// One type per DECLARED plan. Generating a type per With(...)
// combination would be 2^n per entity; you get the plans you named.
type UserSummaryRow struct {
	user.Row
	Org org.Row
}

type UserSummaryQuery struct {
	q          user.Query
	childLimit int64
}

// UserSummary starts the plan. It costs 2 round trips: one for the parents and
// one per relation, whatever the row count.
func UserSummary() UserSummaryQuery {
	return UserSummaryQuery{q: user.New(), childLimit: defaultChildLimit}
}

func (p UserSummaryQuery) Where(ps ...user.Pred) UserSummaryQuery {
	p.q = p.q.Where(ps...)
	return p
}

func (p UserSummaryQuery) WhereIf(cond bool, pr user.Pred) UserSummaryQuery {
	p.q = p.q.WhereIf(cond, pr)
	return p
}

func (p UserSummaryQuery) Any(ps ...user.Pred) UserSummaryQuery {
	p.q = p.q.Any(ps...)
	return p
}

func (p UserSummaryQuery) Not(pr user.Pred) UserSummaryQuery {
	p.q = p.q.Not(pr)
	return p
}

func (p UserSummaryQuery) NotAny(ps ...user.Pred) UserSummaryQuery {
	p.q = p.q.NotAny(ps...)
	return p
}

func (p UserSummaryQuery) Order(ts ...user.Sort) UserSummaryQuery {
	p.q = p.q.Order(ts...)
	return p
}

func (p UserSummaryQuery) Limit(n int64) UserSummaryQuery {
	p.q = p.q.Limit(n)
	return p
}

func (p UserSummaryQuery) Offset(n int64) UserSummaryQuery {
	p.q = p.q.Offset(n)
	return p
}

// After pages the PARENTS past one already seen — keyset pagination over
// the plan. It takes the plan's row type, so the cursor is a row you
// actually received rather than one you had to unwrap.
func (p UserSummaryQuery) After(r UserSummaryRow) UserSummaryQuery {
	p.q = p.q.After(r.Row)
	return p
}

// Err reports a parent query that outgrew its buffers or was given a
// mixed ordering to page. Terminals return it too; this is for checking
// a composed plan before running it.
func (p UserSummaryQuery) Err() error { return p.q.Err() }

// ChildLimit caps each relation's fetch. A guard, not a page size.
func (p UserSummaryQuery) ChildLimit(n int64) UserSummaryQuery {
	p.childLimit = n
	return p
}

// All runs the plan in 2 round trips.
func (p UserSummaryQuery) All(ctx context.Context, ex runtime.Executor) ([]UserSummaryRow, error) {
	parents, err := p.q.All(ctx, ex, nil)
	if err != nil {
		return nil, err
	}
	if len(parents) == 0 {
		return nil, nil
	}
	out := make([]UserSummaryRow, len(parents))
	for i, r := range parents {
		out[i] = UserSummaryRow{Row: r}
	}
	if err := p.load0(ctx, ex, out); err != nil {
		return nil, err
	}
	return out, nil
}

// load0 fetches Org.
func (p UserSummaryQuery) load0(ctx context.Context, ex runtime.Executor, out []UserSummaryRow) error {
	seen := make(map[[16]byte]bool, len(out))
	ids := make([][16]byte, 0, len(out))
	for i := range out {
		key := out[i].OrgID
		if !seen[key] {
			seen[key] = true
			ids = append(ids, key)
		}
	}
	if len(ids) == 0 {
		return nil
	}
	targets, err := org.New().Unordered().Where(org.ID.In(ids...)).Limit(int64(len(ids))).All(ctx, ex, nil)
	if err != nil {
		return err
	}
	by := make(map[[16]byte]int, len(targets))
	for i := range targets {
		by[targets[i].ID] = i
	}
	for i := range out {
		key := out[i].OrgID
		j, ok := by[key]
		if !ok {
			return fmt.Errorf("raorm: %s references a missing %s row", "users", "orgs")
		}
		out[i].Org = targets[j]
	}
	return nil
}

// AttachmentWithSubjectRow is attachments with its Subject resolved.
//
// One field per variant, at most one of them non-nil — the same shape the
// database enforces. A single interface field would be smaller to write
// and would give every caller a type assertion to get wrong.
type AttachmentWithSubjectRow struct {
	attachment.Row
	Post    *post.Row
	Comment *comment.Row
	User    *user.Row
}

type AttachmentWithSubjectQuery struct {
	q attachment.Query
}

// AttachmentWithSubject starts the plan. TWO round trips: one for the rows, one BATCHED
// query carrying every variant lookup.
func AttachmentWithSubject() AttachmentWithSubjectQuery {
	return AttachmentWithSubjectQuery{q: attachment.New()}
}

func (p AttachmentWithSubjectQuery) Where(ps ...attachment.Pred) AttachmentWithSubjectQuery {
	p.q = p.q.Where(ps...)
	return p
}

func (p AttachmentWithSubjectQuery) WhereIf(cond bool, pr attachment.Pred) AttachmentWithSubjectQuery {
	p.q = p.q.WhereIf(cond, pr)
	return p
}

func (p AttachmentWithSubjectQuery) Any(ps ...attachment.Pred) AttachmentWithSubjectQuery {
	p.q = p.q.Any(ps...)
	return p
}

func (p AttachmentWithSubjectQuery) Not(pr attachment.Pred) AttachmentWithSubjectQuery {
	p.q = p.q.Not(pr)
	return p
}

func (p AttachmentWithSubjectQuery) NotAny(ps ...attachment.Pred) AttachmentWithSubjectQuery {
	p.q = p.q.NotAny(ps...)
	return p
}

func (p AttachmentWithSubjectQuery) Order(ts ...attachment.Sort) AttachmentWithSubjectQuery {
	p.q = p.q.Order(ts...)
	return p
}

func (p AttachmentWithSubjectQuery) Limit(n int64) AttachmentWithSubjectQuery {
	p.q = p.q.Limit(n)
	return p
}

func (p AttachmentWithSubjectQuery) Offset(n int64) AttachmentWithSubjectQuery {
	p.q = p.q.Offset(n)
	return p
}

// After pages the PARENTS past one already seen — keyset pagination over
// the plan. It takes the plan's row type, so the cursor is a row you
// actually received rather than one you had to unwrap.
func (p AttachmentWithSubjectQuery) After(r AttachmentWithSubjectRow) AttachmentWithSubjectQuery {
	p.q = p.q.After(r.Row)
	return p
}

// Err reports a parent query that outgrew its buffers or was given a
// mixed ordering to page. Terminals return it too; this is for checking
// a composed plan before running it.
func (p AttachmentWithSubjectQuery) Err() error { return p.q.Err() }

func (p AttachmentWithSubjectQuery) All(ctx context.Context, ex runtime.Executor) ([]AttachmentWithSubjectRow, error) {
	rows, err := p.q.All(ctx, ex, nil)
	if err != nil {
		return nil, err
	}
	if len(rows) == 0 {
		return nil, nil
	}
	out := make([]AttachmentWithSubjectRow, len(rows))
	ids0 := make([][16]byte, 0, len(rows))
	ids1 := make([][16]byte, 0, len(rows))
	ids2 := make([][16]byte, 0, len(rows))
	for i, r := range rows {
		out[i] = AttachmentWithSubjectRow{Row: r}
		if id, ok := r.PostID.Get(); ok {
			ids0 = append(ids0, id)
		}
		if id, ok := r.CommentID.Get(); ok {
			ids1 = append(ids1, id)
		}
		if id, ok := r.UserID.Get(); ok {
			ids2 = append(ids2, id)
		}
	}

	// One BatchOp per variant that has any ids at all: a variant nothing
	// referenced costs no statement, so an arc used one way at a time is
	// as cheap as a plain relation.
	var ops []runtime.BatchOp
	var which []int
	if len(ids0) > 0 {
		bnd0 := post.GetBinder()
		defer post.PutBinder(bnd0)
		// The binder owns the argument slice, so it must outlive the
		// batch — releasing it before Batch runs would hand the driver
		// arguments another goroutine may already be overwriting.
		sql0, args0 := post.New().Unordered().Where(post.ID.In(ids0...)).Limit(int64(len(ids0))).Prepare(bnd0)
		ops = append(ops, runtime.BatchOp{SQL: sql0, Args: args0, WantRows: true})
		which = append(which, 0)
	}
	if len(ids1) > 0 {
		bnd1 := comment.GetBinder()
		defer comment.PutBinder(bnd1)
		// The binder owns the argument slice, so it must outlive the
		// batch — releasing it before Batch runs would hand the driver
		// arguments another goroutine may already be overwriting.
		sql1, args1 := comment.New().Unordered().Where(comment.ID.In(ids1...)).Limit(int64(len(ids1))).Prepare(bnd1)
		ops = append(ops, runtime.BatchOp{SQL: sql1, Args: args1, WantRows: true})
		which = append(which, 1)
	}
	if len(ids2) > 0 {
		bnd2 := user.GetBinder()
		defer user.PutBinder(bnd2)
		// The binder owns the argument slice, so it must outlive the
		// batch — releasing it before Batch runs would hand the driver
		// arguments another goroutine may already be overwriting.
		sql2, args2 := user.New().Unordered().Where(user.ID.In(ids2...)).Limit(int64(len(ids2))).Prepare(bnd2)
		ops = append(ops, runtime.BatchOp{SQL: sql2, Args: args2, WantRows: true})
		which = append(which, 2)
	}
	if len(ops) == 0 {
		return out, nil
	}

	by0 := make(map[[16]byte]int, len(ids0))
	var got0 []post.Row
	by1 := make(map[[16]byte]int, len(ids1))
	var got1 []comment.Row
	by2 := make(map[[16]byte]int, len(ids2))
	var got2 []user.Row
	err = ex.Batch(ctx, ops, func(n int, rs runtime.Rows, _ int64, err error) error {
		if err != nil {
			return err
		}
		switch which[n] {
		case 0:
			var sl runtime.Slab
			for rs.Next() {
				got0 = append(got0, post.Row{})
				if err := post.Scan(rs.RawValues(), &got0[len(got0)-1], &sl); err != nil {
					return err
				}
			}
		case 1:
			var sl runtime.Slab
			for rs.Next() {
				got1 = append(got1, comment.Row{})
				if err := comment.Scan(rs.RawValues(), &got1[len(got1)-1], &sl); err != nil {
					return err
				}
			}
		case 2:
			var sl runtime.Slab
			for rs.Next() {
				got2 = append(got2, user.Row{})
				if err := user.Scan(rs.RawValues(), &got2[len(got2)-1], &sl); err != nil {
					return err
				}
			}
		}
		return nil
	})
	if err != nil {
		return nil, err
	}

	for j := range got0 {
		by0[got0[j].ID] = j
	}
	for j := range got1 {
		by1[got1[j].ID] = j
	}
	for j := range got2 {
		by2[got2[j].ID] = j
	}
	for i := range out {
		if id, ok := out[i].PostID.Get(); ok {
			if j, ok := by0[id]; ok {
				out[i].Post = &got0[j]
			}
		}
		if id, ok := out[i].CommentID.Get(); ok {
			if j, ok := by1[id]; ok {
				out[i].Comment = &got1[j]
			}
		}
		if id, ok := out[i].UserID.Get(); ok {
			if j, ok := by2[id]; ok {
				out[i].User = &got2[j]
			}
		}
	}
	return out, nil
}
