package toolbootstrap

import (
	"bytes"
	"errors"
	"fmt"
	"go/format"
	"strconv"
	"strings"

	tooldiscover "github.com/gsoultan/storm/tool/discover"
)

// Source renders the bootstrap main that used to be written by hand.
//
// It is separated from running it so the output can be golden-tested: this is
// generated code emitted into somebody else's module, which is precisely the
// class of thing that shipped broken in v0.1.0 because nothing ever built it.
func Source(r *tooldiscover.Result) ([]byte, error) { return SourceFor(r, nil) }

// modelless reports whether cmd is one that must work in a module that has no
// models yet.
//
// `import` is the only one, and it is the whole on-ramp: it prints the model
// implied by an existing database. Demanding a model before it will run is a
// chicken-and-egg that locks out the single person the command exists for — an
// adopter holding a schema and no storm code. It shipped that way because the
// outsider check ran import *after* the stranger's module already had a model,
// which is the one ordering under which it cannot fail.
func modelless(args []string) bool {
	return len(args) > 0 && args[0] == "import"
}

// oracleDriver is the database/sql driver storm's Oracle support is written
// against. Named here rather than taken from a flag: a driver is a wire
// protocol implementation, and two of them are not interchangeable at the
// level storm reads — runtime/valdec's mappings were measured against this one
// (see internal/oraclespike). A different driver needs its own measurement,
// not a different string.
const oracleDriver = "github.com/sijms/go-ora/v2"

// driverFor is the database/sql driver a command's dialect needs, or "".
func driverFor(args []string) string {
	for i, a := range args {
		switch {
		case a == "-dialect" && i+1 < len(args):
			if isOracle(args[i+1]) {
				return oracleDriver
			}
		case strings.HasPrefix(a, "-dialect="):
			if isOracle(strings.TrimPrefix(a, "-dialect=")) {
				return oracleDriver
			}
		}
	}
	return ""
}

func isOracle(s string) bool { return s == "oracle" || s == "ora" }

// SourceFor is Source for a known command, so a command that needs no model is
// not refused for lacking one.
func SourceFor(r *tooldiscover.Result, args []string) ([]byte, error) {
	if len(r.Models) == 0 && !modelless(args) {
		// A file that does not parse hides every model in it. Saying "no
		// models found" first would send the developer looking for a missing
		// declaration instead of the typo they just made.
		if len(r.Unparsed) > 0 {
			return nil, errors.New(
				"no models found, because " + strconv.Itoa(len(r.Unparsed)) +
					" file(s) did not parse:\n       " + strings.Join(r.Unparsed, "\n       "))
		}
		return nil, errors.New(
			"no models found in " + r.Module.Path + "\n" +
				"       a model is a struct that embeds storm.Model, or has a Schema/Plans/Projections\n" +
				"       method, or carries //storm:model — see docs/EXAMPLE.md §1")
	}

	// Aliases, not package names: two packages in one module may share a
	// clause (foo/model and bar/model both say `package model`), and the
	// bootstrap has to import both. Numbering by sorted import path keeps the
	// output byte-identical across runs.
	alias := map[string]string{}
	pkgs := r.Packages()
	for i, p := range pkgs {
		alias[p] = "p" + strconv.Itoa(i)
	}

	var b bytes.Buffer
	b.WriteString("// Code generated by storm. DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// This is the bootstrap storm used to ask you to write. It exists for the\n")
	b.WriteString("// length of one command and is then removed.\n")
	b.WriteString("package main\n\n")
	b.WriteString("import (\n")
	if len(r.Queries) > 0 {
		b.WriteString("\t" + strconv.Quote(stormPath) + "\n")
	}
	b.WriteString("\t" + strconv.Quote(stormPath+"/tool") + "\n\n")
	// The database/sql DRIVER, blank-imported, for a target that goes through
	// one. storm's own clients need no registration — a *msdrv.Conn is passed
	// directly — but Oracle is adapted over database/sql, and database/sql
	// resolves a driver by NAME from a global registry that something has to
	// have written to.
	//
	// It goes in the BOOTSTRAP rather than in storm, and that is the point: a
	// prebuilt `storm` binary cannot link every driver, and the adopter's
	// module already has the one they chose, at the version they chose. If it
	// does not, `go run` says which package is missing, which is the same
	// answer missingToolDep gives for storm/tool itself.
	if drv := driverFor(args); drv != "" {
		b.WriteString("\t_ " + strconv.Quote(drv) + "\n\n")
	}
	for _, p := range pkgs {
		fmt.Fprintf(&b, "\t%s %s\n", alias[p], strconv.Quote(p))
	}
	b.WriteString(")\n\n")

	b.WriteString("func main() {\n\ttool.Main(\n\t\t[]any{\n")
	for _, m := range r.Models {
		fmt.Fprintf(&b, "\t\t\t&%s.%s{}, // %s\n", alias[m.ImportPath], m.TypeName, m.Why)
	}
	// Unions travel with the models: Build takes ...any and sets them aside,
	// because a union has no table and cannot be registered as one.
	for _, u := range r.Unions {
		fmt.Fprintf(&b, "\t\t\t%s.%s, // declared union\n", alias[u.ImportPath], u.VarName)
	}
	b.WriteString("\t\t},\n")
	if len(r.Queries) == 0 {
		b.WriteString("\t\tnil,\n")
	} else {
		b.WriteString("\t\t[]storm.RawDecl{\n")
		for _, q := range r.Queries {
			fmt.Fprintf(&b, "\t\t\t%s.%s,\n", alias[q.ImportPath], q.VarName)
		}
		b.WriteString("\t\t},\n")
	}
	b.WriteString("\t)\n}\n")

	// Formatting is not cosmetic here: if this does not parse, the error the
	// developer sees is in a file they did not write and cannot see.
	src, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("synthesized bootstrap does not parse (this is a storm bug): %w\n%s", err, b.String())
	}
	return src, nil
}
