package toolbootstrap

import (
	"go/parser"
	"go/token"
	"path/filepath"
	"strings"
	"testing"

	tooldiscover "github.com/gsoultan/storm/tool/discover"
)

// This is generated code emitted into somebody else's module — the exact class
// of thing that shipped broken in v0.1.0 because nothing ever built it. So the
// golden is the whole file, not a substring: a change to it should be a change
// someone chose.

const golden = `// Code generated by storm. DO NOT EDIT.
//
// This is the bootstrap storm used to ask you to write. It exists for the
// length of one command and is then removed.
package main

import (
	"github.com/gsoultan/storm"
	"github.com/gsoultan/storm/tool"

	p0 "example.com/basic/billing"
	p1 "example.com/basic/model"
)

func main() {
	tool.Main(
		[]any{
			&p0.Invoice{}, // embeds storm.Model
			&p1.Member{},  // embeds storm.Model
			&p1.Region{},  // has a Schema method
			&p1.Tagged{},  // //storm:model
			&p1.Team{},    // embeds storm.Model
		},
		[]storm.RawDecl{
			p1.Declared,
			p1.Purge,
			p1.Top,
		},
	)
}
`

func fixture(t *testing.T, name string) *tooldiscover.Result {
	t.Helper()
	r, err := tooldiscover.Discover(filepath.Join("..", "discover", "testdata", name))
	if err != nil {
		t.Fatal(err)
	}
	return r
}

func TestSourceGolden(t *testing.T) {
	got, err := Source(fixture(t, "basic"))
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != golden {
		t.Errorf("bootstrap source changed:\n--- got ---\n%s\n--- want ---\n%s", got, golden)
	}
}

// Two packages in one module may share a package clause. Importing both
// without aliases does not compile, and the failure lands in a file the
// developer did not write.
func TestAliasesAreUniquePerPackage(t *testing.T) {
	src, err := Source(fixture(t, "basic"))
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{`p0 "example.com/basic/billing"`, `p1 "example.com/basic/model"`} {
		if !strings.Contains(string(src), want) {
			t.Errorf("missing aliased import %s", want)
		}
	}
}

func TestSourceParses(t *testing.T) {
	src, err := Source(fixture(t, "basic"))
	if err != nil {
		t.Fatal(err)
	}
	if _, err := parser.ParseFile(token.NewFileSet(), "main.go", src, 0); err != nil {
		t.Fatalf("synthesized bootstrap does not parse: %v", err)
	}
}

// Generated output has to be byte-identical across runs and machines, and this
// file feeds the generator. Map iteration order reaching it would show up as
// an intermittent diff in the adopter's store, which is the worst way to find
// out.
func TestSourceIsDeterministic(t *testing.T) {
	first, err := Source(fixture(t, "basic"))
	if err != nil {
		t.Fatal(err)
	}
	for i := 0; i < 20; i++ {
		got, err := Source(fixture(t, "basic"))
		if err != nil {
			t.Fatal(err)
		}
		if string(got) != string(first) {
			t.Fatalf("run %d differs from the first", i)
		}
	}
}

// A module with no models must say so in terms of the rules, because the
// developer's next question is always "what counts as a model?".
func TestNoModelsExplainsTheRules(t *testing.T) {
	r := &tooldiscover.Result{Module: &tooldiscover.Module{Path: "example.com/empty", Root: "/tmp"}}
	_, err := Source(r)
	if err == nil {
		t.Fatal("an empty module produced a bootstrap")
	}
	for _, want := range []string{"embeds storm.Model", "Schema", "//storm:model"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("error does not mention %q: %v", want, err)
		}
	}
}

// The omitted-import case: with no raw queries the storm import would be
// unused, and an unused import is a compile error.
func TestNoQueriesOmitsTheStormImport(t *testing.T) {
	r := fixture(t, "basic")
	r.Queries = nil
	src, err := Source(r)
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(src), `"github.com/gsoultan/storm"`+"\n") {
		t.Error("storm is imported but nothing uses it; this does not compile")
	}
	if !strings.Contains(string(src), "nil,") {
		t.Error("expected a nil query list")
	}
	if _, err := parser.ParseFile(token.NewFileSet(), "main.go", src, 0); err != nil {
		t.Fatal(err)
	}
}
